### ISSUE TITLE
problem with template and <list> (empty)

### ISSUE THREAD

**Issue by kolorslab** [picandocodigo/List-Category-Posts#10]
<Hi,

i use this plugin to display 4 thumnails with a pagination it works not very well cause i have empty LI `
<ul class="lcp_catlist">
li> <li> <a href="#"><img src="http://www.image.jpg" class="thumbnews wp-post-image" alt="" " /></a></li><li> <li>`

i use the default template and in my page i call a category with this code :

<p>[catlist id=3628 template=default catlink=no title=no thumbnail=yes thumbnail_size=260,178 thumbnail_size=thumbnail thumbnail_class=thumbnews post_title=no content=no]</p>

`
it semms it was ok without thumbnails and we see the pro in the code.

and i must give "8" to the number posts to have my 4 yjumbails on a list on 2 rows in a div.

we see the TITLE is not in the heref but in the ALB image tag...

if someone can help me i have finsihed and i have problem only on it,

i have put a jquery.pahinate so i load all posts and i display only 4 but i need to put 8 to have 4 on front

thanks,

http://wordpress.org/extend/plugins/list-category-posts/

**Comment by zymeth25** [comment]
I guess this is stale and can be closed.
