### ISSUE TITLE
Plugin Compatibility Issue

### ISSUE THREAD

**Issue by paulthomson-me** [picandocodigo/List-Category-Posts#100]
Plugin seems to be 'semi' incompatible with plugin 'Remove Posts in Category From Homepage' - http://wordpress.org/plugins/remove-posts-in-category-from-homepage/

Highlighting issue as there are probably many other plugins which do similar filtering that could be affected. Not sure if an 'issue' with this plugin or others.

Most of the arguments in the shortcode work apart from the filtering of the category.

Thanks,
Paul

**Comment by zymeth25** [comment]
Can be closed the 'Remove Posts in Category From Homepage' plugin has not been maintained for over 2 years.
