### ISSUE TITLE
Shortcode option to display tags for each displayed post?

### ISSUE THREAD

**Issue by brit77** [picandocodigo/List-Category-Posts#103]
I think this is a feature request, unless there is a way to do this that I'm not seeing!

Basically, a shortcode parameter to display any tags attached to a post would be very handy.

Many thanks!

**Comment by zymeth25** [comment]
I started putting this together:
https://github.com/picandocodigo/List-Category-Posts/compare/master...zymeth25:display-tags

Should there also be a parameter to make a link of each post tag, similar to `catlink`? And another one to set a html tag to wrap each post tag with?

**Comment by brit77** [comment]
This would be most useful if it functioned like catlist with an option like catlink.

**Comment by zymeth25** [comment]
Yes, I agree with the `catlink` like behaviour. So what do you think it should look like by default: tags displayed next to post title, comma separated?

**Comment by brit77** [comment]
It's been a while since I've used this, so I don't quite remember how it works! If there is no way to custom place the elements, then I'd say either after the title is fine, as is comma separated.

**Comment by zymeth25** [comment]
Once the feature is added you can customize placememt using CSS, so no need to worry about that. I'm only asking for ideas on how to implement it. It could be like this:
`tag1, tag2, tag3`
Or auto wrapped in html by default:
`<span>tag1</span><span>tag1</span>`
And there are many other options

**Comment by brit77** [comment]
Auto-wrapped in html and allowing for adding classes would give the most flexibility.

**Comment by zymeth25** [comment]
Ok, will keep thinking about the implementation. Thanks!

**Comment by zymeth25** [comment]
I've more or less finished working on this, new parameters would be:
* `posts_tags` - if set to 'yes' will enable posts tags display
* `posts_tags_tag` and `posts_tag_class` - they work like other parameters described [here](https://github.com/picandocodigo/List-Category-Posts/wiki/HTML-&-CSS-Customization)
* `posts_tags_prefix` - a string to display before the tags **but within the posts_tags_tag** if set, default: empty
* `posts_tags_glue` - a string to insert between the tags default: ', '
* `posts_tags_inner` - html tag to wrap each post's tag with, if set will also automatically add classes based on post's tag's slug, i. e. if the slug is 'news' then `<span class="tag-news">News</span>`; default: empty
* `taglink` - works just like `catlink`, each tag is a link to the tag's page, 'yes' to enable, default: 'no'

What do you think of the parameters' names? 

Link to the code is in my first comment in this thread.

**Comment by brit77** [comment]
Looks good to me.

**Comment by picandocodigo** [comment]
Bumping this so stale doesn't close it.
