### ISSUE TITLE
Something strange with pagination

### ISSUE THREAD

**Issue by denvist** [picandocodigo/List-Category-Posts#111]
Hello!

I have 15 posts: 1 of them in "Uncategorized" category, others 14 in category "weekly-wisdom"

When i use this code: `[catlist numberposts=8 pagination=yes]` everything is ok.

But when i want filter posts by category `[catlist name=weekly-wisdom numberposts=8 pagination=yes]` i've got something strange: pagination have 2 pages each show 6 posts.

Sorry for my terrible english :|

**Comment by zymeth25** [comment]
Can be closed, probably a bug in an earlier version, now works perfectly fine.
