### ISSUE TITLE
Adding Custom Post Types Support

### ISSUE THREAD

**Issue by medical-hero** [picandocodigo/List-Category-Posts#123]
Hi,
I'd like to use this nice plugin to list custom types. This would be useful for many people.

In my case I am setting up a multilanguage portfolio and showcase site with custom types and 3 to 5 related taxonomies. So I want to to order the artifacts (posts) by taxonomies like projects, types of work, types of businesses and so on.

**Comment by smootsa** [comment]
+1

**Comment by conschneider** [comment]
Hi there, 

If you take a look at `list-category-posts.php` you will see a whole bunch of parameters, `post_type` is among them. 

So what you can do is use the shortcode like this `[catlist post_type="custom-post-type-slug"]`. 

Kind regards,
