### ISSUE TITLE
LCP interfering with sticky posts?

### ISSUE THREAD

**Issue by cpearmain** [picandocodigo/List-Category-Posts#124]
Love LCP - it has made the construction of my first WP site so much easier.

Now it is simple to force new posts in a given category to appear on the relevant pages. However, I have run into a problem whereby 'Sticky' posts in a given category don't stick at the top of the page.

I don't know whether this is a WP issue or one with LCP. Can anyone assist please?

**Comment by zymeth25** [comment]
It is not 'interfering', this is default WP behavior. In WP sticky posts are not prepended on category archive pages, so the LCP plugin doesn't prepend them when you specify a category in your shortode.

**Comment by zymeth25** [comment]
Can be closed.
