### ISSUE TITLE
Custom field display broken after 0.50.3 => 0.51 update

### ISSUE THREAD

**Issue by rothbert** [picandocodigo/List-Category-Posts#125]
Using a template (row_of_2.php) in a child theme  - custom fields disappared after update, debug output  - 

NOTICE: wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php:340 - Trying to get property of non-object
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/parent-theme-name/page.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, ListCategoryPosts::catlist_func, CatListDisplayer->__construct, CatListDisplayer->define_template, CatListDisplayer->template, require('/themes/child-theme-name/list-category-posts/row_of_2.php'), CatListDisplayer->get_custom_fields

Might have something to do the file renaming?

**Comment by zymeth25** [comment]
Can be closed, issue no longer present and related to an old version.
