### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by subnoodle** [picandocodigo/List-Category-Posts#127]
Hi,
i've seen that plugin and it look awesome.
Then i installed it on a multisite. The installation worked very fine. The status was "network activated".
Then i visited the plugin section of one of the multisite.
It came true, that the instance of the multisite does not show the plugin, although it's "network activated".

Form this behavior i conclude, that the plugin is not multisite-able.

How big would be the effort to get it multi site able?

Thank you,
  Thomas

**Comment by SooBahkDo** [comment]
Hello subnoodle,

You may find that when network activated the functionality works on all subsites on the network.

Since List Category Posts has no menu items, the only thing that would appear in subsite menus is the settings menu item.

**Comment by zymeth25** [comment]
Can be closed, as of now the plugin flies on multisite :wink:
