### ISSUE TITLE
wrongly redirected to search result page after trying to save global max posts to show

### ISSUE THREAD

**Issue by jjgh** [picandocodigo/List-Category-Posts#129]
Hello, I'm using last Wordpress and I'm seeing that if I try to save the global maximum number of post to show I'm redirected to the search result output page, saying that no posts have been found.
I've tried setting it to -1, 0 or a positive number, but behaviour does not change.
What could it be?

**Comment by Baldoius** [comment]
Me to :)

**Comment by picandocodigo** [comment]
Hi, thanks for reporting this. This has been fixed on version 0.52 with this commit: https://github.com/picandocodigo/List-Category-Posts/commit/84bd05a00444256f28e825a881dd43b02b15cece

Please check it out and if it doesn't work for you, reopen this issue. Thanks!
