### ISSUE TITLE
custom fields values don't show in my list

### ISSUE THREAD

**Issue by dakinibilyana** [picandocodigo/List-Category-Posts#13]
Hello, 
I'm using the Plugin List Category to show a list of posts and I use it with the parameters: 
[catlist name=talleres thumbnail=yes thumbnail_size=52,52 excerpt=yes customfield_display=featured]
I have value for this custom field but for some reason it doesn't show on the page. 
I tried with different parameters, still nothing. do I have the syntax wrong or something?
any help will be greatly appreciated, i've been struggling with this for few days now. 
thanks a lot in advance.

**Comment by mmatthews1981** [comment]
@picandocodigo I need a demo if how this feature is supposed to work

**Comment by zymeth25** [comment]
Can be closed, issue no longer present.
