### ISSUE TITLE
Multiple category doesn t work

### ISSUE THREAD

**Issue by nemanjaradevic** [picandocodigo/List-Category-Posts#131]
[catlist id=33+35 numberposts=5]

while if i just put a single category it works

also post status same bug

[catlist id=12 template=seminarpage post_status=publish+future orderby=date catlink=yes ]

if i just put one of the two works great

https://wordpress.org/support/topic/add-multiple-post_statuspublishfuture?replies=1#post-6402277

**Comment by picandocodigo** [comment]
@nemanjaradevic Check out the latest version on wordpress.org: 0.52. [This small fix](https://github.com/picandocodigo/List-Category-Posts/commit/84bd05a00444256f28e825a881dd43b02b15cece#diff-70ec36c0a290685879fc645c16436ff7R271) could be what wasn't working for you. Let me know if it works after you update. Thanks!

**Comment by picandocodigo** [comment]
Closing this issue since I haven't had any reply from @nemanjaradevic

**Comment by nemanjaradevic** [comment]
all good there thanks

Regards

Nemanja Radevic
M:99588509
E:nemanja@radevic.com
