### ISSUE TITLE
Removing filters interfering with filters set by other plugins

### ISSUE THREAD

**Issue by zulkamal** [picandocodigo/List-Category-Posts#132]
I ran into an issue where LCP broke another plugin (Advanced Custom Fields). Digging through the code, the issue was caused by LCP calling `remove_all_filters('posts_where')` during `set_lcp_parameters()`. It would seem that calling `remove_all_filters()` should be avoided. 

Changing this to be more specific fixes it for me:
`remove_filter('posts_where', array( $this, 'starting_with'));`

I'll submit a pull request if the fix is ok.

**Comment by picandocodigo** [comment]
@zulkamal please, submit the Pull Request whenever you think it's ready. Thanks!

**Comment by zulkamal** [comment]
submitted!
