### ISSUE TITLE
About the length of the same amount post_title display

### ISSUE THREAD

**Issue by FancyGary** [picandocodigo/List-Category-Posts#133]
I want to deal with the title which contain Chinese character, because at present the difference of title is large.
So, I modified the function "get_post_title" of file "lcp-catlistdisplayer.php", and I realized what I want to.
I strongly suggest this plugin can realized this function.

Here is a bug I found.
function "get_post_title" of file "plugins\list-category-posts\include\lcp-catlistdisplayer.php"
       if( strlen($lcp_post_title) >= intval($this->params['title_limit']) )
the judgment is not rigorous, thus will be better:
       if( strlen($lcp_post_title) < strlen($lcp_post_title_old) )

**Comment by FancyGary** [comment]
@picandocodigo  

My English is not good.
There is a code suggestion in Issue #133, and I'm looking forward your browsing.
Thanks in advance!

**Comment by picandocodigo** [comment]
@FancyGary There's a suggestion in #143 which might help you, do you know if that fix would work when using Chinese characters? If I don't get a Pull Request there, I'll modify the code in the plugin anyway.

Thanks!
