### ISSUE TITLE
Post body text on homepage does not match post.

### ISSUE THREAD

**Issue by babalooch** [picandocodigo/List-Category-Posts#142]
I am using your plugin on the homepage of a wordpress site http://feinworks.org/

The posts are displaying except the text I see is not the text in the posts - it is old text from previous edits of the posts.  How do I get these to work properly.  No matter what I do I cannot seem to edit the text of posts on the website.  The titles of the posts seem to edit just fine.  

Thanks in advance for the response.

**Comment by Sophist-UK** [comment]
Do you have a caching plugin?

**Comment by babalooch** [comment]
Thanks so much for the quick response.
I do not think so but sometimes you don't really know everything a plugin is doing.
I have included a PDF showing all the active plugins, the home page code for your plugin a sample of the posts and a copy of how the current home page displays.
Thanks again
Paul

**Comment by Sophist-UK** [comment]
It is no good sending a PDF in a reply to GitHub as it doesn't make it into the GitHub issue.

**Comment by babalooch** [comment]
Ok 
can you get jpg's or is there another way to send it to you?
Thanks
Paul

**Comment by Sophist-UK** [comment]
Stop using emails to reply and use the web link where you can drag and drop or upload images.

**Comment by babalooch** [comment]
Sending three images outlining the issue

![2015 0320 feinworks plugins and posts_page_1](https://cloud.githubusercontent.com/assets/11563612/6772627/0cb897e0-d0d9-11e4-9700-2149c720c40b.jpg)
![2015 0320 feinworks plugins and posts_page_2](https://cloud.githubusercontent.com/assets/11563612/6772628/0cb9255c-d0d9-11e4-9e89-2e4c3ce116a9.jpg)
![2015 0320 feinworks plugins and posts_page_3](https://cloud.githubusercontent.com/assets/11563612/6772629/0cb9f8d8-d0d9-11e4-9571-bacfa1d2d497.jpg)

**Comment by zymeth25** [comment]
Cannot reproduce this, probably an old and no longer present issue with compatibility. Can be closed.
