### ISSUE TITLE
title_limit are not working correctly

### ISSUE THREAD

**Issue by MustangZhong** [picandocodigo/List-Category-Posts#143]
if the words in title are combined with ascii character and multi-byte characters (for example Chinese), it will make the word encoding incorrect.

**Comment by MustangZhong** [comment]
to solve this issue, just simply replace 'substr' to wp_trim_words in lcp-catlistdisplayer.php line 414.

**Comment by picandocodigo** [comment]
@MustangZhong would you mind doing a Pull Request from your commit? Thank you!

**Comment by Sophist-UK** [comment]
Unfortunately not quite as simple as this...

1. You need to check length using a multi-byte aware function in the previous line.
2. The title_limit is specified in characters, whilst wp_trim_words is specified in words.

However we could use wp_trim_words in include/lcp_catlist.php function lcp_trim_excerpt.

**Comment by Sophist-UK** [comment]
Did #149 fix this for you @MustangZhong ?

**Comment by MustangZhong** [comment]
I think this issued has been fixed.@Sophist-UK
