### ISSUE TITLE
Fatal error: Call to undefined method CatListDisplayer::stuffFunction()

### ISSUE THREAD

**Issue by lernoupi** [picandocodigo/List-Category-Posts#151]
Hi,

I'm working two years with the List-Category-Posts plugin. So far, without any problems. Since a few days however, I'm confronted with the following 'fatal error': 

Fatal error: Call to undefined method CatListDisplayer::stuffFunction() in /var/www/vhosts/hasseltbt.be/httpdocs/wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php on line 297. 

Any idea why this error turns up and how to fix it? Thanks for your help.

This is my website: www.hasseltbt.be. 

Pieter

**Comment by Sophist-UK** [comment]
Looks like there is a $ missing on line 297 in include/lcp-catlistdisplayer.php. Here are lines 296-300:
```
      if (!empty($this->params[$entity . '_class'])):
        $result = $this->stuffFunction($single, $this->params[$entity . '_tag'], $this->params[$entity . '_class']);
      else:
        $result = $this->$stuffFunction($single, $this->params[$entity . '_tag']);
      endif;
```

I will create a PR.

**Comment by lernoupi** [comment]
Thanks a lot Sophist-UK! This solves the problem!
