### ISSUE TITLE
catlink title empty with more than one List Category Posts widget

### ISSUE THREAD

**Issue by Anguel** [picandocodigo/List-Category-Posts#155]
I have two List Category Posts widgets on a page - one is set to display posts from the current category, the other is set to display posts from a specific category. Both have catlink set as their title. Unfortunately, the widget that should display from the current category does not display any title and returns an empty <a href=""></a>
The other widget works as expected.

**Comment by Sophist-UK** [comment]
Have you set instances for these to avoid conflicts of ids?

**Comment by Anguel** [comment]
Sorry, I am not sure how to set instances. I have two widgets and I enter "catlink" (without the quotes) as their titles. The widget that does not work is set to "Current category". If I understand correctly it should detect the category of a post and display it in the title. It seems to detect the category as it correctly lists other posts from the current category. But it does not show any title.

**Comment by Sophist-UK** [comment]
I am not sure about the widgets as I use shortcodes on my site - do you have a public URL that I can look at with the two widgets?

Also check the javascript console to see if you are getting any js errors.

**Comment by Anguel** [comment]
Sorry, I cannot provide a public link at this time. The problem is with the widget. No JS errors, the a href is just empty, had posted this above but github "ate" my html tags. Now I removed the other widget and still the same problem. It looks like "Current Category" setting in the widget just does not work with "catlink" in title for some reason.

**Comment by Sophist-UK** [comment]
You don't need to set "catlink" as the title of the widget for the specific category as that is fixed - ave you tried entering your own title to see if that helps?

**Comment by Anguel** [comment]
As described above, it actually works with "catlink" but only if I select to list posts from a *specific* category. However, if I want it to dynamically fetch the category of the post -> "Current Category" choice in the widget, it does not work anymore.
