### ISSUE TITLE
Plugins filtering on the_content do not work correctly

### ISSUE THREAD

**Issue by Sophist-UK** [picandocodigo/List-Category-Posts#156]
This plugin applies filters (correctly) on the_content (at lcp-catlist.php line 297), however if these plugins (like simple-tags) want the post-id of the content or check what type of page this is, then they can produce invalid results.
1. This plugin needs to make get_the_ID work correctly whilst in "the loop" so that content plugins work on the specific post currently processing e.g. in the case of simple_tags to pick up their taxonomy entries;
2. This plugin effectively converts a single (page or post) into a blog or archive. So whilst in the loop this needs to make the is_feed, is_home, is_singular, is_single, is_page etc. work as expected whilst in "the loop" and then to reset them back again when we ext "the loop". (Again simple-tags checks the type of page when deciding whether to show the tags for the post.)

I am still researching, trying to work out how to save, set and reset these, and then I will need to decide exactly what needs to change whilst in the loop. Any help that people can give would be appreciated.

**Comment by Sophist-UK** [comment]
P.S. There is also an in_the_loop function which needs to produce the correct result.

**Comment by Sophist-UK** [comment]
Regarding point 1. above, in lcp-catlist.php at around line 56 we create the query for the catlist loop. However I think we should probably follow the template shown [here](https://codex.wordpress.org/The_Loop#Multiple_Loops_Example_2) to save the existing query, create our own query and then restore the original query once catlist has finished.

**Comment by Sophist-UK** [comment]
I have tried to make this change, but (so fa at least) it just screws it up. {sigh}

**Comment by Sophist-UK** [comment]
Fixed by #157.

I decided that setting the conditional tags was probably not possible - just too many different possibilities for the user to choose to be able to know what to set or clear.

**Comment by zymeth25** [comment]
Can be closed.
