### ISSUE TITLE
0.6 breaks templates

### ISSUE THREAD

**Issue by mokummusic** [picandocodigo/List-Category-Posts#158]
I'm not sure if its just custom templates, but several users on the Wordpress Support forum, including myself have experienced the following error.

Fatal error: Call to undefined method CatList::get_categories_posts()

 The 'get_categories_posts' function was removed in the "Fix the Loop' commit on May 3rd.

**Comment by nuss** [comment]
I was just about to post a report on this issue as well: the function get_categories_posts() has been removed in `/include/lcp-catlist.php`. I'm using a custom template within `list-category-posts` in my theme but I guess it would be broken too if I used the default template within the plugin's  `templates` directory...

**Comment by picandocodigo** [comment]
Just reverted the changes on version 0.60.1. We need to figure out a way to support templates while using a new loop. Wish I had more time to check this out and test it. At least the new version should fix these issues.

Thanks and sorry for the inconvenience.

**Comment by Sophist-UK** [comment]
You just need to add the missing routine back in.  I did check that the was not other code using it,  but I guess I must have missed something.
