### ISSUE TITLE
Getting 'Notice' error

### ISSUE THREAD

**Issue by cantonkid** [picandocodigo/List-Category-Posts#160]
Hi,

I've been getting a 'notice' error of some kind on the page where I use the List-Category-Posts app.

Notice: Undefined index: QUERY_STRING in /hermes/bosnaweb04a/b2246/glo.cantonkid/wp-content/plugins/list-category-posts/include/lcp-catlist.php on line 74

It appears for every category usage I have applied to the page.

actual page is here: http://kong-cast.com/east-screen-west-screen/episodes

I have tried deactivating and reactivating and creating a new page.

It was working fine before, so I am not sure if its due the last update of WP or some other feature / plugin. Any help with this is much appreciated.

**Comment by bibz** [comment]
Hello,
Have your tried to uninstall and then reinstall the plugin as well?
What version of WordPress / the plugin are you using? Have you tried without any other plugin activated?

Also, are you using the widget or a shortcode? In the later case, please post here your example.

**Comment by picandocodigo** [comment]
This should have fixed the issue: https://github.com/picandocodigo/List-Category-Posts/commit/cadb1560e4673476762c46b5eba18e456dce840a#diff-70ec36c0a290685879fc645c16436ff7R99

@cantonkid please let me know if you're still having problems with this, otherwise I'll close this issue. Thanks!

**Comment by cantonkid** [comment]
Hi Mr. Briano,

Yes, your fix has corrected the issue.  Thanks very much for your help with this :-)

best regards

Paul

**Comment by picandocodigo** [comment]
Awesome, thanks!
