### ISSUE TITLE
Filter by name & post_type cannot coexist after update

### ISSUE THREAD

**Issue by shizus** [picandocodigo/List-Category-Posts#168]
I used to have this shortcode on my page:

`[catlist name="bands" post_type="bands" orderby=title order=asc thumbnail=yes thumbnail_size=thumbnail pagination=yes numberposts=15]`

The result was this http://farhatguitar.com/bands/

These shortcodes used to have the same result:

`[catlist name=bands post_type="bands" orderby=title order=asc thumbnail=yes thumbnail_size=thumbnail pagination=yes numberposts=15]`

`[catlist id=3 post_type="bands" orderby=title order=asc thumbnail=yes thumbnail_size=thumbnail pagination=yes numberposts=15]`

After updating the plugin this week without changing anything the result is this:

http://demo.farhatguitar.com/bands-broken/

Only when I erased the "name" attribute it worked as expected:

[catlist post_type="bands" orderby=title order=asc thumbnail=yes thumbnail_size=thumbnail pagination=yes numberposts=15]

**Comment by icm** [comment]
I have the same issue! Did you figure out a temporary fix?

**Comment by shizus** [comment]
I just went to a previous version. Do know how to do it? If not let me know and I will fork and upload the version I'm using so you can just copy-paste it

**Comment by XenesisXenon** [comment]
It actually appears that name= is broken. All my categories stopped working once I updated to 0.63 and they use name entirely.

**Comment by zymeth25** [comment]
Can be closed. This issue has been fixed and the above shortcodes all work.
