### ISSUE TITLE
Post 4.3 upgrade - constructor method for WP_Widget is deprecated

### ISSUE THREAD

**Issue by bishless** [picandocodigo/List-Category-Posts#169]
After upgrading to WordPress 4.3 on my staging install, I noticed the error in title appearing all over my site (frontend and backend). I deactivated all my plugins and the error went away. After activating them one at a time, I found _LCP_ was the culprit for me.

![](https://cldup.com/qHjAjARTXn.png)

Here's how I fixed it termporarily/locally:

In `include/lcp-widget.php` change line 12:

```
// parent::WP_Widget(false, $name = __('List Category Posts','list-category-posts'), $opts);
parent::__construct(false, $name = __('List Category Posts','list-category-posts'), $opts);
```

See [**Deprecating PHP4 style constructors in WordPress 4.3**](https://make.wordpress.org/core/2015/07/02/deprecating-php4-style-constructors-in-wordpress-4-3/) for more info.

**Comment by picandocodigo** [comment]
@bishles, this was fixed on version 0.63, please update and open a new ticket if you have any further issues.

Thanks!
