### ISSUE TITLE
Update version number

### ISSUE THREAD

**Issue by shaneonabike** [picandocodigo/List-Category-Posts#171]
This is a really simple point but since Wordpress checks if there are app updates it keeps telling me that there is a new one. When I updated it ... things got broken because I was using the version from GitHub which is more recent (I believe). All was well when I downloaded the Github version and replaced it.

Could we just bump the version number up so it doesn't conflict?

Thank you for an awesome AWESOME plugin!

**Comment by bibz** [comment]
Just a note to stress out that the **tags** and the **releases** have not been used recently, maybe we could do something about that too :)

**Comment by picandocodigo** [comment]
@bibz Yep, since we have to tag every version in WordPress' SVN repo anyway, I hadn't been using tags or releases on GitHub. But it could be a good idea from now on. As soon as I add something new I'll bumb the version @shaneonabike and try to keep a bigger version number on GitHub. Thanks!

**Comment by bibz** [comment]
Food for thoughts:
 - [A successful Git branching model (Vincent Driessen)](http://nvie.com/posts/a-successful-git-branching-model/)
 - [A collection of Git extensions (namely `git-flow`)](https://github.com/nvie/gitflow) to support the aforementioned model
 - [An overview of how to use `git-flow` to follow Vincent Driessen's workflow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)

Last but not least, @GaryJones published an enhanced version of [a shell script](https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy) to deploy a git plugin repository to WP.org's SVN repository.
(Note that I haven't tested this script, but it seems to really ease the deploy-to-WP process.)

**Comment by zymeth25** [comment]
Can be closed.
