### ISSUE TITLE
Deactivated after update and more important SLOW!

### ISSUE THREAD

**Issue by janpolet** [picandocodigo/List-Category-Posts#172]
Version 0.64 is not activated after the update, which is weird.

What's more important though is that the plugin has become terribly slow. Unusable even.
Loading a page with a shortcode which loads a category with only 4 posts, takes seconds. 15 sometimes!!
Loading the same content using the url for that catogory goes fast.
So what could be wrong?

I really hope this can be fixed 'cause I love this plugin.
Right now I have to turn it off and use workarounds 'cause the plugin is really causing problems.

Best regards,

Jan Polet

**Comment by bibz** [comment]
Hello Jan,

About the deactivation, it is an expected behaviour when updating from a version < 0.63.
I proposed an update (74592d1388950a4bb2d1cce526e7c8bdc8672c1c) of the plugin base file that got accepted for version 0.63. [As stated](https://wordpress.org/support/topic/after-upgrade-posts-not-showing-only-parameters?replies=7#post-7354205) by William Earnhardt, Wordpress thinks that the plugin has been removed because of the name change.
There is no other fix than activating the plugin once again.

On the speed issue, could you please provide the shortcode and, if possible, the generated HTML?
You can also try rolling back to the version you were using before to check that it is indeed caused by the plugin update.

**Comment by janpolet** [comment]
On of the shortcode being used is: [catlist name=Voorpagina content=yes orderby=date order=desc].

This is the original page, now a test page, with that shortcode:
http://www.skyhighcreations.nl/?page_id=4708

This is the page, with the same content, redirected to the url of the same category:
http://www.skyhighcreations.nl/

This category has just 4 posts.

The site is in Dutch.
Querying other categories with shortcodes results in the same issue.
I hadn't really looked at the site for a while. I just updated all the plugins and stuff, so I don't know when the site started to become slow. The person posting on the site thought it was his Internet connection.

Hope this information helps.

Tnx!!

Jan

**Comment by bibz** [comment]
I cannot reproduce the behaviour you mentioned using the profiler of my browser.
Both pages took around 4.75 seconds to fully load for a second time (that is the static content was cached on my computer, I just reloaded the page).
If I force-reload the pages, they both require 7 seconds (+- 1 second).

Can you tail down exactly what you experience as slow?

**Comment by janpolet** [comment]
Loading the page with the plugin's shortcode take from 9 till 15 seconds.
The link to the specific category loads in under 2 seconds.

**Comment by janpolet** [comment]
This is another example:

Page with shortcode: http://www.skyhighcreations.nl/?page_id=4931

Direct url to the category: http://www.skyhighcreations.nl/?cat=5&order=asc

Jan

**Comment by bibz** [comment]
By tailing down, I mean measure using your browser profiler for instance and then report here the results.
My own measurements report that the actual page (the HTML code) takes from 50 to 500ms to get generated and sent back to my browser. For both pages. That is not significant to say something about the code generation done by the shortcode. But maybe the rendering time of what is generated is longer. It needs more investigation.

Both Firefox and Chrome have embedded profiling tools (other should have too).

Beware, on your second example the two pages are different: the one without the shortcode also displays the sidebar. The map takes some time to load on my computer and can bias the results.

**Comment by janpolet** [comment]
Sorry about the second example. I created the page in a hurry and forgot to select the sidebar template. They're the same now.
I'll look in to the browsers profiler. Never measured pages down to the ms before.
The difference is so huge in this case.

**Comment by bibz** [comment]
Well, the thing is that I cannot see this *hugeness* on my side (hence the ms measurement). So you need to tell me exactly what your problem is.

**Comment by janpolet** [comment]
Can't figure out how to use it in Firefox.
I came as far as using F12, Recording Performance, loading a page, stopping recording and seeing many results. Can't seem to find the total time it took to load the entire page.
Sorry!

**Comment by janpolet** [comment]
![2015-08-31 12 51 08](https://cloud.githubusercontent.com/assets/14051799/9577257/6a6741c2-4fdf-11e5-8e82-b91a2bae9654.png)
With shortcode.
![2015-08-31 12 51 19](https://cloud.githubusercontent.com/assets/14051799/9577258/6a6835e6-4fdf-11e5-9b1e-c050e36182d6.png)
URL to category.

**Comment by bibz** [comment]
Could you please provide the network duration of the page asset?

On my computer, here are the results (Chrome and Firefox, first line):

![First example with Chrome (124ms)](https://cloud.githubusercontent.com/assets/5141956/9582484/e4d3f8d0-5005-11e5-8c82-34384abf2271.png)

![Second example with Firefox (156ms)](https://cloud.githubusercontent.com/assets/5141956/9582482/e4a7a406-5005-11e5-8fce-781235709ed2.png)

**Comment by janpolet** [comment]
I hope this is what you asked for.
![2015-09-01 13 44 16](https://cloud.githubusercontent.com/assets/14051799/9603291/0f2956de-50b0-11e5-9f80-e017343311f6.png)
![2015-09-01 13 45 52](https://cloud.githubusercontent.com/assets/14051799/9603292/0f2af110-50b0-11e5-96e7-523ad38bbb1d.png)

**Comment by bibz** [comment]
Yes, thank you. Wow! That's an impressive difference!
We now have to figure out why you experience such a delay and I don't.
The thing is, this is the duration corresponding to the request being treated and the result sent back to you.
The behaviour is not consistent with what I am experiencing (no significant difference).

Have you tried deactivating every plugins but LCP?

**Comment by bibz** [comment]
Also, you should compare the equivalent pages because they do not have the same amount of objects embedded (+ size, + # of requests, ...).

**Comment by janpolet** [comment]
I've deactivated all plugins I thought could make a difference.

The pages should be the same.
http://www.skyhighcreations.nl/?page_id=4931 uses shortcode [catlist name=Agenda numberposts=10 content=yes orderby=date order=asc pagination=yes].
http://www.skyhighcreations.nl/?cat=5&order=asc uses category 5 which has the name Agenda and the amount of posts is the same. It is missing the title the page with the shortcode has, so the layout is a bit different. The content isn't though. Am I missing something?

**Comment by bibz** [comment]
I am still not experiencing the issue you face (both pages are retrieved in ~100ms several times).
Are you connected in WP? Maybe this could be an issue with the SQL request and some filters on the user currently logged-in.

**Comment by janpolet** [comment]
There's something weird going on!!
I forced a page reload two times. Same page! Look at the difference of the amount of requests!!
![2015-09-01 14 09 25](https://cloud.githubusercontent.com/assets/14051799/9603774/53568ae0-50b3-11e5-9a3f-c04ec1f4ee08.png)
![2015-09-01 14 09 58](https://cloud.githubusercontent.com/assets/14051799/9603775/535696ca-50b3-11e5-8330-968e450712b5.png)
How is that possible?

**Comment by bibz** [comment]
Can you comment out the embedded map?
Anything external content would be good actually, so we can reliably measure what is happening.

**Comment by janpolet** [comment]
I communicated with the specific hosting provider as well. They also noticed the difference and basically told me the site isn't optimized. They used a Google tool to test the page and told me the amount of requests is exceptionally high.
I'm using basic WordPress with plugins that are widely used, so what can I do?!

**Comment by janpolet** [comment]
Well one thing WordPress is lacking is an option to disable a widget. If I want to get rid of the embedded map in the sidebar, I have to delete it.
I can disable the NextGEN plugin, which will get rid of the changing image on the top of the sidebar, but I already tried that. Is doesn't make a difference.

**Comment by bibz** [comment]
You can drag-and-drop a widget in the "disabled" zone so that it keeps its content.

**Comment by janpolet** [comment]
I can get rid of the sidebar on the page using the shortcode. I can't when using the url to the category.

**Comment by janpolet** [comment]
Ah, great! The map is gone now. Anything else?

**Comment by bibz** [comment]
100 requests is definitely a high amount.
You would want to lower that number by: 1) optimising your content delivery (i.e. compress and gather the scripts in one file, the stylesheets too), 2) finding optimised plugins (i.e. no plugins that are constantly activated even if they do nothing), 3) looking at tutorials on SEO.

A lot of resources are available for WP administrators, even WP plugins to test your installation.

**Comment by janpolet** [comment]
Do I have to change the way WordPress works?
The way scripts are used is defined in the WordPress code, right?
I'm using a standard theme and well known plugins.
Can you tell me what SEO has to do with this?
I know how to use WordPress and add and change things, but I'm not a coder. That's beyond my knowledge, I'm afraid.

**Comment by janpolet** [comment]
Could you name a few plugins that could help test the installation?
I'd appreciate it a lot.

**Comment by bibz** [comment]
You should definitely have a look at the [official documentation](https://codex.wordpress.org/WordPress_Optimization) on how to optimise WP, they explain it better and in a thoroughly fashion.

I mentioned SEO because you also need to optimise how the content is delivered to the SE. For instance, Google takes into account the duration required and the number of requests it has to do to get one (complete) page.

**Comment by bibz** [comment]
For the time being, is it possible to deactivate *all* of your plugins except LCP?
You would want to do this locally or on a dedicated instance to be sure not to break the live website. We need to figure out if LCP is the problem here, and if it is, what is happening.

**Comment by janpolet** [comment]
OK! Thanks for the link.
It's weird that I, the hosting provider and the person posting on the site can notice the difference in the time it takes to load both pages and you can not. Very strange.
The issue only arises when the shortcodes are used.

**Comment by bibz** [comment]
I do agree that this is a peculiar situation.
That is why I strongly suggest you to test this *locally*.
The content I am delivered may very well be cached in some way.

**Comment by janpolet** [comment]
It's not a high traffic website and the server has resources to spare.
Not using the shortcodes seems to be working great.
Which, again, doesn't make sense because the content should be the same.
The link to the official information is about large, high traffic sites and caching and stuff.
Going into all of that would make sense when the site was slow always and not just when using 'List Category Posts'.
I don't know what to make of this.

**Comment by bibz** [comment]
You have a fair point.
By testing the plugin locally, you eliminate one uncertainty factor (which is the network availability). You replace the server parameter by your computer, which is still better because you can trace your computer resources more easily than those of the server.

I'd be glad to help you with this one (local testing) but I am not sure that sharing your site's content would be such a great idea.

Maybe @picandocodigo knows a good way to debug his plugin.

**Comment by bibz** [comment]
> Not using the shortcodes seems to be working great.
> Which, again, doesn't make sense because the content should be the same.

The content is the same but the request to retrieve it may not be. Plus, you need some extra computation from the plugin to generate this request.

**Comment by janpolet** [comment]
Well this is what the provider sent me.
![screen shot 2015-08-26 at 12 04 02 pm](https://cloud.githubusercontent.com/assets/14051799/9604745/97cdf2b6-50b9-11e5-8b68-e415e53ec89e.png)

**Comment by janpolet** [comment]
Thanks a lot for your time and effort, Borjan.
Thanks for offering to help testing. How would that work?
And why do you think sharing the content is not a good idea?

**Comment by bibz** [comment]
You are welcome Jan, I know how it feels when things do not work the way they should be.
Well, the idea is to set up a web-server on your machine, install WP, and then replicate the installation you have online. Then you would try to tail down the issue. It is basically the same as you were doing remotely. But you don't have to experience the latency and delays of the network. Plus if your web-server is running on a managed hosting, you do not control what is happening (this should not be a problem as shown by the graph you just provided, it seems that the CPU is often enough idle).

If you are comfortable with sharing the whole content of your website, then you could export it within WP (Dashboard > Tools > Export). That would give us the textual content, which should be a good starting point.
You can either send me an e-mail (dev -at- my-first-name -dot- my-last-name -dot- fr) or share it with the whole world if you want to.

**Comment by janpolet** [comment]
I'll export the site when my NAS is done upgrading the firmware.
My NAS has a webserver as well, but it's really slow, so that wouldn't really work.
I also have a backup of the WordPress folder. It's about 1.6Gb big. There are a lot of photo albums in NextGEN Gallery.
The XML file is about 4.5Mb. Is that right?

**Comment by bibz** [comment]
Yes, that's why I want to avoid as much as possible the transfer of all your media.
Let's stick with the textual content for now ;)

**Comment by janpolet** [comment]
Sent you an email. Hope I got the address right! :)

**Comment by janpolet** [comment]
Well, if the media is needed, one WeTransfer session would do it! :)

**Comment by bibz** [comment]
E-mail received.
I'll set this up in a virtual machine and see if I can reproduce the issue only with textual content.

**Comment by janpolet** [comment]
WOW! Thanks!!!!!!
I'm also trying to import the file into WordPress on my NAS.
It's slow, but maybe it helps.
At the importer I also checked: "Download and import file attachments". Does that mean it's also going to find all the files on the site? 1.6Gb of data, or isn't that a problem? Never done this before.

**Comment by bibz** [comment]
It seems that this is the expected behaviour, yes.
The [documentation](http://codex.wordpress.org/Importing_Content#WordPress) states:
> WordPress will then import each of the posts, comments, and categories contained in the uploaded file into your blog. In addition, you can import attachment by checking the "Download and import file attachments" option.

**Comment by janpolet** [comment]
The WordPress folder is now about 800Mb! I did get an error though, so I don't know if it completely correctly.
Is there a way to undo the import? Sorry for asking newbie questions.

**Comment by bibz** [comment]
I tried both ways, with and without checking the box.
If you *do* check it, WP will try to import attached files by downloading them locally.
If you do *not* check it, WP will link attached files to their original address (as stated in the export).

The import failed on some (a lot?) files even when I checked the box. The size difference between the two imports is about 400MB.

I am not a WP expert either, my easiest fix is to remove the installation and re-do it. A quick and dirty hack ;-)

On the issue note, I do now experience it too. Without the shortcode the page requires around 200ms and with the shortcode it requires around 4s. So, here we go, I can now confirm the issue :)

**Comment by janpolet** [comment]
I also did a test on my NAS.

It took the category link to load in 882ms.
The page with the shortcode took 13306ms.
WOW!!

**Comment by bibz** [comment]
I think I may have pinned down the issue to the posts' contents being filtered intensively.
Can you try to update your shortcodes with `[catlist ... content=full]` instead of `content=yes` please?

**Comment by janpolet** [comment]
Woah!!!!

**Comment by janpolet** [comment]
I had to double check, but changing "content=yes" to "content=full" did the trick!!
How is that possible??

**Comment by bibz** [comment]
Good news!
When `content` is set to `full`, the content is basically retrieved and rendered.
But when `content` is set to `yes`, the plugin looks through the whole content for the *more link* to truncate the content if found. And this search can be quite intensive on long texts.

In other words, the [documentation](https://wordpress.org/plugins/list-category-posts/other_notes/) states:
> Show the excerpt or full content of the post. If there's a  tag in the post, then it will behave just as WordPress does: only show the content previous to the more tag. Default is 'no'. Ex: [catlist content=yes]
>
>Show the full content of the post regardless of whether there is a  tag in the post. Ex: [catlist content=full]

The issue should be closed now :-)

**Comment by janpolet** [comment]
I read that too.
WOW!
I've been using this plugin for a long time. Either it has been added after I started using it, or I overlooked that completely! The list of arguments/options has been greatly extended.
Thanks so much! You solved it! I really appreciate it!
Issue closed! ;)

**Comment by bibz** [comment]
(psst, you forgot to actually close the issue)

**Comment by janpolet** [comment]
Sorry!
TNX!!

**Comment by picandocodigo** [comment]
Wow, thank you very much @bibz! You are awesome :metal: 

I should really take a look at that text searching for the *more* string...

**Comment by bibz** [comment]
I was actually wondering if this was needed.
There is already the parameter `excerpt` to display the post excerpt (and generate it if needed). This feature may very well be outdated.
Furthermore, when using the `content` parameter, one does not expect the plugin to truncate the post content as (s)he specifically asked it.

The incriminated function `get_content` is located in `include/lcp-catlist.php`.
