### ISSUE TITLE
Linking the Date

### ISSUE THREAD

**Issue by ashikai** [picandocodigo/List-Category-Posts#173]
The page I'm playing with for reference: http://talesstudio.com/lackeysailing/projects/taico/

Current shortcode being displayed on that page: [catlist name="taico" dateformat="l F dS, Y" date=yes ]

Problem: I'm trying to set this shortcode up so that it'll only display the HYPERLINKED DATE of posts within a category. I just want to be able to HYPERLINK the POST DATE (which seems weird, I know, but it's what I need for this site).

I've tried messing around in lcp-catlistdisplayer, lcp-catlist (I mostly just break things in here), and the default.php template. I've done extensive experiments with the template and as far as I can tell it hasn't changed the page output at all (or at least, what's displayed on the page I linked above never changes). I don't know if I have a compatibility issue there or what.

I'm probably overlooking something extremely obvious but I would be very grateful if someone could point me in the right direction! Thank you very much!

**Comment by bibz** [comment]
Hi ashikai,

first of all, you can hide the post titles with the option `no_post_titles`. Or you can use a custom template as described in [the documentation](https://wordpress.org/plugins/list-category-posts/other_notes/#Template-System) (the default template located in the *templates* directory is documented as well).
Your shortcode could then be `[catlist name="taico" date="yes" dateformat="l F dS, Y" no_post_titles="yes"]`.

Then, about the post link for the post date, it is not yet available as an option.
I have written a small patch that you can test as-is.
Just [download my patched version as a zip file](https://github.com/bibz/List-Category-Posts/archive/feature_link_dates.zip) and install as a usual plugin.

**Comment by ashikai** [comment]
OMG Thank you so much! That was WAY more than I expected! You are amazing! \QAQ/
