### ISSUE TITLE
Allow category count in morelink

### ISSUE THREAD

**Issue by pderksen** [picandocodigo/List-Category-Posts#175]
Would love to do something like http://docs.helpscout.net/ does for each category link (i.e. `9 articles`).

**Comment by picandocodigo** [comment]
@pderksen you can use these parameters:
`[catlist id=1 catlink=yes category_count=yes]`

This will show the posts count in the category. If you want to use just the number in your template, you can call this function:
```php
$lcp_display_output .= $this->get_category_count();
```

I'm updating the default.php template to show the usage of the category post count parameter.

**Comment by pderksen** [comment]
@picandocodigo Thanks! Working great for the extra output, but it seems if I remove `category_count=yes` from the shortcode to hide the count in the category header, it also hides it in any extra output I make that uses `$this->get_category_count();`
