### ISSUE TITLE
morelink_class not working with templates

### ISSUE THREAD

**Issue by pderksen** [picandocodigo/List-Category-Posts#176]
Using your default template or a custom one I'm not able to get the attribute `morelink_class` to tack on a css class to the <a> tag. Works without a template though.

Example:
`[catlist template="default" name="general" morelink="View all articles" morelink_class="st-btn st-btn-mini"]`

https://github.com/picandocodigo/List-Category-Posts/blob/master/templates/default.php#L107-107

**Comment by picandocodigo** [comment]
@pderksen Hi, thanks for reporting this. There's a bug in the template code. In your template, where it says:
```php
$lcp_display_output .= $this->catlist->get_morelink();
```

It should say instead:
```php
$lcp_display_output .= $this->get_morelink();
```

I'm updating the code for the next version, but in the meantime please test this and let me know if it's working for you.

Thanks!

**Comment by pderksen** [comment]
@picandocodigo I'm testing after you already pushed the release including this fix.

`$this->get_morelink();` is working, but I'd like to somehow pass category_count to it so the link is something like this:

`<a href="my-class" href=".../my-category/">View all articles (12)</a>`

This possible with this shortcode and/or template?

Thanks again for fixing the `morelink_class` attribute so quickly!
