### ISSUE TITLE
Category count in morelink (add'l tweaks)

### ISSUE THREAD

**Issue by pderksen** [picandocodigo/List-Category-Posts#179]
Recently you made some updates concerning 2 related issues: #175, #176

I commented once more on each of those issues after they were closed, but thought maybe a synopsis here of what I'm still looking for would help.

In my case I do _not_ want to show category count in the header, but I do want to show it in the more_link text. Currently, with category_count=yes, it will show in the header regardless. Is there a way to only include it in more_link?

I'm trying to get the more link to render in this format (assume 12 is the category count):

`<a href="my-class" href=".../my-category/">View all articles (12)</a>`

Is this possible now or are additional tweaks required?

I'm already using a custom template as well.

Thanks again for all your work on this plugin!

**Comment by picandocodigo** [comment]
I'll look into this for next version. Thanks!
