### ISSUE TITLE
Styling the current page element in pagination (tweak).

### ISSUE THREAD

**Issue by chadschulz** [picandocodigo/List-Category-Posts#180]
When styling my pagination in .lcp_paginator I've encountered a few themes that have unique "button" styling for the current page non-link versus the other page links.
I'm able to style the links by using .lcp_paginator a {}. However, the current page is only wrapped in li without any class and cannot be easily styled.

If you go to line 202 in lcp-catlistdisplayer.php:
 ```
$link = "<li>$current_page</li>";
```
and change it to: 
```
$link = "<li><span class='current'>$current_page</span></li>";
```
you create a span class that can be styled for the current page "button".

This shouldn't break anybody's styling as it only adds an addition element inside that would inherit already existing css on the li element. Yet, now we can simply style that non-link uniquely beyond just the text/font.

Thanks for any consideration (I'm lazy and would like to not have to customize lcp on every update),
Chad

p.s. this is a brilliant plugin I've been using for years.

**Comment by picandocodigo** [comment]
Thanks @chadschulz, that's a great and simple contribution :smile:

**Comment by chadschulz** [comment]
Sorry,
I noticed on a wordpress forum post for lcp that you intend to wrap the current_page in only a li element with class='lcp_currentpage'.
This still will not allow full customization of the css. Unless there's an internal element like span, only the text and font can be styled differently.
If there's an internal span element inside the li (just like the a element inside the other page links) than everything can be styled (background-color, padding, border, height/width, etc...).
I've literally tried every variation of css and js hacks I know to get this working without any core lcp modifications and it is simply impossible unless the code is as I originally posted:

`$link = "<li><span class='lcp_currentpage'>$current_page</span></li>";`

Again, I can make this change manually upon every update. But, it appears as though at least one other person is trying to get this working, as well. And it's such a simple, non-destructive fix.

Thanks,
Chad

**Comment by picandocodigo** [comment]
@chadschulz You can customize almost everything with the class in the `li`, at least all the elements you mentioned.

Here's an example:
```css
.lcp_currentpage{
	background-color: #333;
	color: #fff;
	padding: 1px 20px !important;
	margin: 10px !important;
	height: 40px;
	border: dashed 4px #f00 !important;
}
```

![screenshot from 2015-10-18 12-51-39](https://cloud.githubusercontent.com/assets/689327/10564779/75ae9ab8-759f-11e5-8c23-91c36d3a6527.png)

Is there any other specific customization you haven't been able to achieve without the span? I tried not including a span to keep it as lean as possible, but if there's a good reason to add it I might add it.

Thanks!

**Comment by chadschulz** [comment]
You're absolutely right. As long as I get a distinct class for the li element I was able to successfully style my buttons.

I worked on this problem so long I ended up losing the forest for the trees.

I'm so very sorry for any wasted time.

Thanks,
Chad

**Comment by picandocodigo** [comment]
That's fine, no time was wasted! 

It usually happens when you get stuck on a problem, so no worries. Great to know you figured it out :smile:
