### ISSUE TITLE
Do you have any suggestions how I can build in some customisation

### ISSUE THREAD

**Issue by wilsonf1** [picandocodigo/List-Category-Posts#186]
Hi Fernando 

I hope you are well. I spoke to you via email back in July 2014!

Our website still uses List Category Posts and it's an essential plugin for the functionality. So thank you!

The only issue it's painful for me to update as we make 2 modifcations to the code for it to work how we want it. If I give you the file name, line numbers and edits we make, are you able to try and think of a way we could potentially put some filters into functions.php to get the same effects wihout having to modify the plugin? Here goes anyway:

lcp-catlistdisplayer.php

After line 150:     $this->lcp_output .= $this->get_pagination();

We add:

// Added by James Wilson
$this->lcp_output = updateToPerfectURLs($this->lcp_output);

( updateToPerfectURLs() is function that simply does some string replaces on the URL's to make them how we want )

After Line 245: $lcp_display_output = '<'. $tag . $class . '>';

We add:

// Added by James Wilson - Start
$icon = get_field('icon', $single->ID);
$image_attributes = wp_get_attachment_image_src($icon, array(50,39));

$attachment_meta = wp_get_attachment($icon);    

$lcp_display_output .= "<img class=\"post_icon\" src=\"" . $image_attributes[0] . "\" alt=\"" . $attachment_meta['alt'] . "\" />";
// Added by James Wilson - End  

So we basically add in icons to each link.

Is there anything that can be done to either potentially build this in either to the plugin or the functions.php?

One idea is you create a new file called something like custom-functions.php

Then after line 150 you could have something like:

$this->lcp_output = $customfunctions->modify_build_output($this->lcp_output);

The plugin would come with the modify_build_output function empty (just returning the input).

But I could then have my own custom-functions.php file ready to just upload after updating the plugin, with my own code inside. That would create the same effect?

Same again for the my second edits on line 245.

Look forward to hearing your feedback.

**Comment by zymeth25** [comment]
Can be closed. There is no need to change any pulgin files. Everything described above can be done in a template.
