### ISSUE TITLE
post_type not working showing pages by default

### ISSUE THREAD

**Issue by Matt2012** [picandocodigo/List-Category-Posts#187]
I am seeing pages and posts even though it should default to posts I have tried adding it manually still doesn't filter out pages.

```
[catlist id=23,24,25,44 excerpt=yes pagination=yes excerpt_strip=yes thumbnail=yes template="version1" numberposts=10 excerpt_overwrite=no excerpt_size=50 post_type="post" posts_morelink="Read more"]
```

I am using Version 0.64 (I wanted to solve issue before upgrading).

**Comment by zymeth25** [comment]
Can be closed, issue no longer present.
