### ISSUE TITLE
ORDERBY is stuck on descending mode, cannot change the order on posts

### ISSUE THREAD

**Issue by pmmanage** [picandocodigo/List-Category-Posts#188]
Hi, 
I am trying to use the plugin and I notice that the orderby doesn't work. This occurs when I use a shortcode, and when I use the widget. If I have orderby as ASC or DESC (either by typing those values in the shortcode, or by choosing ascending or descending in the dropdown) ... the order doesn't actually change! It stays in descending no matter what. 

Can you help troubleshoot this?

Thanks

**Comment by PanaromicTiger** [comment]
I'm facing the same issue. Is there a work around or maybe a fix for this issue?

**Comment by arcticmouse** [comment]
i also have the same issue.

**Comment by arcticmouse** [comment]
orderby doesnt work for me either, through the widget or with a shortcode.

**Comment by Sophist-UK** [comment]
> I'm facing the same issue. Is there a work around or maybe a fix for this issue?

Yes - read the code, work out why it isn't working, code a fix and submit it as a PR.

**Comment by Sophist-UK** [comment]
Or read the [documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/More-parameters-you-can-use).

`orderby` is the field that is used to sort by. You need to use `order=asc` for ascending order.

**Comment by arcticmouse** [comment]
i am using the shortcode per the documentation, which i have read. just reporting in because this is clearly still an ongoing issue for the plugin.

**Comment by Sophist-UK** [comment]
Please post the exact shortcode you are using so we can see your parameters.

**Comment by Sophist-UK** [comment]
Also please try using `order=ASC` rather than `order=asc` as it may be case sensitive.

**Comment by zymeth25** [comment]
Can be closed, issue no longer present.
