### ISSUE TITLE
Not working with latest version of WP

### ISSUE THREAD

**Issue by pankaj-asp** [picandocodigo/List-Category-Posts#190]
Hi fernandobt,

Your plugin is awesome, but however it is not working with latest version of WP.

There are so many peoples who are facing this issue, can you suggest any quick fix, so many websites are down.

Please assist us.

**Comment by chantalcoolsma** [comment]
Confirmed. If you use:

`[catlist id=4 numberposts=99 orderby=title order=asc date=no author=no]`

it works okay. If you set _numberposts_ to -1 or above 99, the result is a white page.

**Comment by pankaj-asp** [comment]
Thanks @chantalcoolsma 

Thanks for suggestion but this solution didn't worked, though I have re-installed thrice and seems there was some cache issues or something was not updating accordingly from database.

Now its working fine.
