### ISSUE TITLE
two different get_excerpt functions

### ISSUE THREAD

**Issue by mmatthews1981** [picandocodigo/List-Category-Posts#194]
Is there a reason there are two functions named get_excerpt? one is lcp_catlist.php:359, takes one arg, the other lcp_catlistdisplayer.php:355, takes three args. should it be refactored to distinguish between the two, depending on how many args are sent to the function?

**Comment by picandocodigo** [comment]
@mmatthews1981 the get_excerpt function in `lcp_catlistdisplayer` is just a wrapper for display. The one in `lcp-catlist` just gets the excerpt, so the one in `lcp_catlistdisplayer` assigns styles, html classes or tags, the display parameters. Feel free to refactor them to distinguish their functionality.

**Comment by zymeth25** [comment]
I actually think it's better to leave it as is. Template functions in the Displayer are generally just wrappers so maybe it's better to use corresponding method names so that the relationship is clear.
