### ISSUE TITLE
Latest WP update broke my pages

### ISSUE THREAD

**Issue by imehesz** [picandocodigo/List-Category-Posts#199]
hello,

I have several pages with the following content:
`[catlist post_type=CUSTOM_POST_TYPE template=list-page numberposts=17 taxonomy="CUSTOM-TAXONOMY" tags=SOMETAG pagination=yes]`

This was working as expected until the latest WP version (4.5.1).
I don't see any error messages, but the posts just don't show up. (actually they show up if I use the tool _without the custom taxonomy_, but it's essential in my case)

Any help is appreciated.

thanks,
--imre

**Comment by zymeth25** [comment]
Can be closed. As of now, the shortcode requires both `taxonomy` and `terms` parameters to work. Explanation is in the documentation.
