### ISSUE TITLE
customfield_class customfield_tag are broken

### ISSUE THREAD

**Issue by amirhabibi** [picandocodigo/List-Category-Posts#201]
Hi !

These functions (used by shortcode) are broken in the latest version :

[catlist name="evenement" customfield_display_name="no" customfield_orderby=date numberposts=5 customfield_display=date customfield_class=css customfield_tag=span]

Errors : 

Notice: Undefined variable: css_class in /..../wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php on line 411

Notice: Undefined variable: tag in /..../wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php on line 411

In the generated code : 

Just the custom field content, not even the default DIV or css class

Thanks :)

**Comment by vacuus** [comment]
Hey, I think I solved this. The get_custom_fields function was only assigning a value to $tag or $css_class if the params key mapped to an empty or null value. I'll create a pull request.

**Comment by amirhabibi** [comment]
Thanks a lot @vacuus !! I'll wait the new version. I don't wan't to mod the plugin.

**Comment by picandocodigo** [comment]
@amirhabibi this should be fixed in version 0.70 thanks to @vacuus. Please update and let me know if we can close this issue.

**Comment by zymeth25** [comment]
Can be closed. Fixed in #202 . Issue not present now.
