### ISSUE TITLE
Thumbnails to left  

### ISSUE THREAD

**Issue by lewatt23** [picandocodigo/List-Category-Posts#204]
Hello  everyone please  can someone help  me out, i have tried all  kind og method to sent the post thumbnails to the left  but i does not seems  to work ... i dont  know why ?? i  have read  tons  of articles on that  but i can still  do  it please  one help  me  please .  
here is my  code  
[catlist name="cameroon gce O level past Papiers " numberposts=10

thumbnail=yes thumbnail_class=posts-list  thumbnail_size=70,70 ]

here  is  my  stlyle
.posts-list img {
   float: left;
}
running on wordpress 4.6

my websit www.cgce-revision.com  ( that's the homepage  you can find some the  error there  )
thanks  in advance

**Comment by picandocodigo** [comment]
@lewatt23 Change the css code to just set the style for the class. Not `.posts-list img`, just `.posts-list`:
```
.posts-list{
  float: left;
}
```
You can also add a `clear` property for the list items not to overlap:
```
.posts-list{
	float: left;
}

.lcp_catlist li{
	clear: both;
}
```

**Comment by lewatt23** [comment]
thanks for the help but i tried it but it does not still work

**Comment by picandocodigo** [comment]
@lewatt23 Are you sure you added the CSS I wrote to the theme's stylesheet? I added this code with Firefox's style editor and the thumbnails get aligned to the left:


![Demo](http://i.imgur.com/P0PCTkn.gif)

**Comment by lewatt23** [comment]
thanks so much i found the problem , i did not put my code at the top  of the  style sheet  thanks so much am so greatfull @picandocodigo
