### ISSUE TITLE
AND not working?

### ISSUE THREAD

**Issue by DonLiborio** [picandocodigo/List-Category-Posts#205]
I have a few posts with in both categories "sega" and "nintendo". Choosing them individually works:

[catlist name=sega]
[catlist name=nintendo]

But I get an empty list with this:

[catlist name=sega+nintendo]

Running Wordpress 4.6.1 and List Category Posts 0.70

Is anyone having the same problem? Am I doing something wrong? Thanks!

**Comment by DonLiborio** [comment]
Sorry, it works as expected with posts, but I tried to use it in combination with the "Post Tags and Categories for Pages" plugin. The "+" doesn't work with Categories in pages, which is outside the expected behavior. My apologies.

**Comment by DonLiborio** [comment]
So, categories on pages added through "Post Tags and Categories" work for single categories (`[catlist name=sega]`) or with "OR" (`[catlist name=sega,nintendo]`) but not with "AND" (`[catlist name=sega+nintendo]`). Why? Is there anything I can do to modify the code to make it work? Thanks!

**Comment by DonLiborio** [comment]
` [catlist name=sega+nintendo post_type="page"]` did the trick!

**Comment by zymeth25** [comment]
Can be closed.
