### ISSUE TITLE
Showing all new posts instead of category posts.

### ISSUE THREAD

**Issue by Primarie** [picandocodigo/List-Category-Posts#206]
Hello, can you please check on my website, the plugin is showing all posts, and not category posts... tho' i changed category names few times .. donno what to do maybe is getting in conflict with other plugin ?

http://tzinahrecords.info/sept-24-nowhere-opening-party-w-crocodile-soup/

Let me know if you can help. Thank you

**Comment by zymeth25** [comment]
If you expect support @Primarie you need to at least provide the shortcode you are using. Otherwise we can't even begin to help.

**Comment by Primarie** [comment]
<h1 style="text-align: center;">TZINAH RECORDS RECENT UPDATES:</h1>
[catlist name=TZINAH ON BLACK, TZINAH PODCAST, TZINAH RECORDS NEWS, TZINAH RELEASES, TZINAH SHOWCASE]

I use to have just one category, but since it does not work i use it like this now.

**Comment by Primarie** [comment]
U can check here: http://tzinahrecords.info/seia-interview-tzinah-podcast-january-2018/

**Comment by zymeth25** [comment]
Ok, thanks for the shortcode.

If you want to select several categories you need to put them between quotes, like this:  `[catlist name="TZINAH ON BLACK, TZINAH PODCAST, TZINAH RECORDS NEWS, TZINAH RELEASES, TZINAH SHOWCASE"]`

It works in my tests so if you get your syntax right it should work as well.

**Comment by zymeth25** [comment]
Seems to be resolved.

**Comment by Primarie** [comment]
Thanks

**Comment by zymeth25** [comment]
Can be closed.
