### ISSUE TITLE
no_post_titles not working

### ISSUE THREAD

**Issue by brunocalado** [picandocodigo/List-Category-Posts#207]
I used no_post_title=yes and it does not remove the titles.

`[catlist name=ciencias template=radioagencia date=yes numberposts=9 dateformat='j/F/Y' thumbnail=yes no_post_titles=yes]`  

By commenting the line bellow on the template file, I got the desired outcome. 
`//$lcp_display_output .= $this->get_post_title($post, 'h3', 'lcp_title_radioagencia');`

**Comment by Rahmon** [comment]
Hi,  @brunocalado .

The "no_post_titles" parameter is working. It's your template file that output the titles.

**Comment by brunocalado** [comment]
That's true. I just tried with: 

`[catlist name=ciencias date=yes numberposts=9 dateformat='j/F/Y' thumbnail=yes no_post_titles=yes]`

And it didn't show the title.

But is there a way to a custom template work with this parameter? When I use a custom template this parameter becomes useless.

**Comment by zymeth25** [comment]
Duplicate of #244 
Can be closed.
