### ISSUE TITLE
Make each div post clickable?

### ISSUE THREAD

**Issue by baswijdenes** [picandocodigo/List-Category-Posts#210]
Hi,

First: I love your plugin! I've been using it over a year on my main page and it's one of the best WordPress Plugins.

I have an idea though, could you make the div clickable instead of the link or thumbnail? Or do I need to use jQuery for that? 

Thanks in advance,

Bas

**Comment by zymeth25** [comment]
@baswijdenes Which div? By default this plugin uses no div elements.

**Comment by zymeth25** [comment]
Stale issue. Can be closed.
