### ISSUE TITLE
How to order posts by number field (number) 10 after 9 not 1 ?

### ISSUE THREAD

**Issue by donuzz** [picandocodigo/List-Category-Posts#211]
How to order posts by custom field (number) 10 after 9 ?

Ex: `[catlist name=tutorial customfield_orderby=chapter order=ASC]`

Now 10 show after 1.

**Chapter – Post Title**
1 – Title 1
10 – Title 10
2 – Title 2
3 – Title 3
4 – Title 4
5 – Title 5
6 – Title 6
7 – Title 7
8 – Title 8
9 – Title 9

I need...

**Chapter – Post Title**
1 – Title 1
2 – Title 2
3 – Title 3
4 – Title 4
5 – Title 5
6 – Title 6
7 – Title 7
8 – Title 8
9 – Title 9
10 – Title 10

**Comment by julia-r** [comment]
I have 2 Ideas:

1) Check if your custom field has the type of an integer. If it is a string, it might be sorted like this.
2) Try changing your custom field so the one digit numbers have a 0 in front of them (1 -> 01)

**Comment by zymeth25** [comment]
Can be closed, solved by @julia-r 🙂
