### ISSUE TITLE
List Category Posts not working

### ISSUE THREAD

**Issue by lyssiixnole** [picandocodigo/List-Category-Posts#213]
I pasted into the text section of my page and it is only showing up on my main page as the text for the page.  www.fromlyssiiwithlove.com check it out please.  What am I doing wrong?

**Comment by Sophist-UK** [comment]
Have you tried `[catlist name="food"]`?

**Comment by lyssiixnole** [comment]
I did and it shows up on the main page under the picture and title of the page likenits content.  Did you see it? Www.fromlyssiiwithlove.com

**Comment by Sophist-UK** [comment]
I saw it without the `"`.

Another possibility is that you have put it in a text widget which does not support shortcodes. There is a plugin (which you will need to search for) which gives you an alternative text widget which does support shortcodes.

**Comment by picandocodigo** [comment]
Hey @Sophist-UK 👋, long time no see. Thanks for helping out!

@lyssiixnole if you want to use the shortcode in a text widget, you can use a plugin as @Sophist-UK suggests, or follow [these instructions in the FAQ](https://github.com/picandocodigo/List-Category-Posts/blob/master/doc/FAQ.md#widget).

It looks like the shortcode could be in the theme files too. If you want to use the shortcode in the theme files, you need to wrap it around some PHP code:
```php
<?php echo do_shortcode('[catlist name="food"]'); ?>
```

**Comment by lyssiixnole** [comment]
Where are the theme files? And what would putting it in the theme files do vs putting them where they belong in the page ? This seems like a pain in the ass for getting a plugin that should just do it lol

**Comment by Sophist-UK** [comment]
I would not recommend modifying the theme files as this takes the technical skills needed and site maintenance to a whole new level. Sorry that I can;t remember the name of the plugin though.

**Comment by lyssiixnole** [comment]
So how do I get this to work for me ? I to the page, ,clicked edit page and entered [catlist name=food] and it ends up showing up on my main page as the content!  I have a CSS section for my theme where I'm supposed to enter all short codes but I don't know how to specify which page needs what cause I'm assuming that's how I would differentiate what the coding is for.

**Comment by Sophist-UK** [comment]
CSS sections are NOT where you enter shortcodes.

hen you say you "go to the page" and click "edit page" can you show us a screen shot?

**Comment by lyssiixnole** [comment]
Thank you for dealing with me. I don't have the option to put a picture in here

**Comment by lyssiixnole** [comment]
![img_6548](https://cloud.githubusercontent.com/assets/23220355/19966862/09510aa4-a1a4-11e6-8c0d-9ddd3cb871af.PNG)
![img_6549](https://cloud.githubusercontent.com/assets/23220355/19966861/094c304c-a1a4-11e6-98dc-06850c366fad.PNG)

**Comment by Sophist-UK** [comment]
Are you sure you have activated the LCP plugin?

It looks like you have done the right thing. (I don't think it makes a difference entering it in Text mode rather than Visual mode.)

**Comment by lyssiixnole** [comment]
![img_6551](https://cloud.githubusercontent.com/assets/23220355/19970058/35b8435c-a1b1-11e6-8d78-ac466fd839ef.PNG)


Yea I even got another crappy plugin and it didn't do what I wanted ! I'm gonna contact the theme guy than you

**Comment by Sophist-UK** [comment]
Yes - it could be that your theme doesn't include support for short-codes. So that should be your next step.

**Comment by zymeth25** [comment]
Can be closed, clearly the issue was with a faulty theme that didn't render shortcodes.
