### ISSUE TITLE
Is it possible to use current page's category for conditional_title?

### ISSUE THREAD

**Issue by peterallcdn** [picandocodigo/List-Category-Posts#214]
On each page, I'm displaying a list of other pages that belong to the same category as the current page. I'd like this list to have a heading/title. If I understand correctly, I can use conditional_title to specify a static heading/title. I'm hoping however that it's possible to use the current page's category as the heading/title. This way I don't have to worry about editing the heading/title for each page as it'll be done automatically.

Is this possible and if so, how?

Thanks!

**Comment by zymeth25** [comment]
Yes, it's possible. Please read the documentation first!
>catname – Show the title of the category (or categories), works exactly as catlink, but it doesn’t add a link to the category.

Example:
`[catlist categorypage=yes catname=yes catname_tag=h1 catname_class=my-class]`

Issue can be closed.
