### ISSUE TITLE
Title after thumbnail

### ISSUE THREAD

**Issue by olivellaf** [picandocodigo/List-Category-Posts#216]
Hi,

First of all, thank you for the plugin. At the moment, it seems is a good one.

I wanted to know how to print the title after the thumbnail. I have to touch the template? 

**My current "shortcode" is:**

[catlist name=news thumbnail_class=thumb-content no_post_titles=yes excerpt_tag=p excerpt_class=c_excerpt post_status=publish thumbnail=yes force_thumbnail=yes thumbnail_size=large excerpt=yes excerpt_size=15 posts_morelink="Read more"]

**Current CSS classes**
`.lcp_catlist {
    list-style: none;
    display: inline-flex;
    width: 100%;
    margin: 0;
    padding: 0;
}

.lcp_catlist li {
    background-color: #eee;
    text-align: center;
}

.lcp_catlist li a img {
    height: 319px;
}

.lcp_catlist li p {
    padding: 25px 15px;
}

.lcp_catlist li h3 {
    padding: 15px;
    font-weight: 700;
    text-transform: uppercase;
    font-size: 18px;
}

.c_excerpt {
    background-color: white;
}

.lcp_catlist li a:last-child {
    background-color: #ffba00;
    padding: 10px;
    margin: 7px 0;
}

.lcp_catlist li a:last-child:hover {
    opacity: 0.4;
}`

**Comment by HeresJohnyOrg** [comment]
Hi,

I rearranged the order in templates/default.php, moved this line: 

`$lcp_display_output .= $this->get_thumbnail($single);`

To be above these lines:
`if ( empty($this->params['no_post_titles']) || !empty($this->params['no_post_titles']) && $this->params['no_post_titles'] !== 'yes' ) {
    $lcp_display_output .= $this->get_post_title($single);
}`

**Comment by vacuus** [comment]
You might want to try using a flexbox chage the order of items. Check this out: https://stackoverflow.com/questions/7425665/switching-the-order-of-block-elements-with-css

**Comment by zymeth25** [comment]
Can be closed, two valid solutions mentioned above.
