### ISSUE TITLE
How do I just show the categories with numbers of posts?

### ISSUE THREAD

**Issue by a4jp-com** [picandocodigo/List-Category-Posts#219]
How do I just show the categories with numbers of posts?

I can see heaps of settings but I just want to know how to show all categories as links in a list with the number of posts in brackets.

**Comment by picandocodigo** [comment]
@a4jp-com this plugin shows posts from a category, it doesn't list the categories. You might want to try [List Categories](https://wordpress.org/plugins/list-categories/), which does exactly what you're looking for with the `show_count` parameter:
`[categories show_count=1]`
