### ISSUE TITLE
Category Page

### ISSUE THREAD

**Issue by amommasjoy** [picandocodigo/List-Category-Posts#223]
I have my cat page set up to show all posts from one category, they are showing the full posts (they are short) in 3 columns. I would like them to display on post below another, so it looks just like a regular blog page. Can anyone help me with that?

**Comment by vacuus** [comment]
This sounds like something to do with your site's CSS. Github is meant to be used more for development  purposes (reporting bugs, requesting enhancements, submitting changes, etc.).

I'm not sure how well you know CSS but these pages may be helpful
* https://developer.mozilla.org/en-US/docs/Learn/CSS
* http://www.w3schools.com/css/

**Comment by zymeth25** [comment]
Can be closed. Totally agree with @vacuus
