### ISSUE TITLE
Update Vagrant and Test Files

### ISSUE THREAD

**Issue by vacuus** [picandocodigo/List-Category-Posts#224]
I tried running the unit tests but PHPUnit complained that my version of PHP was too old. Vagrant's bootstrap is old (ex. phpunit is available from the official Ubuntu repos). I think the Vagrant configuration should be updated to use Xenial (Ubuntu 16.04).

**Comment by vacuus** [comment]
I started working on something here: https://github.com/vacuus/List-Category-Posts/tree/update_testing .

**Comment by picandocodigo** [comment]
That's awesome! I haven't updated my running Vagrant instance in a while, so this is long overdue. Thanks!!!!

**Comment by vacuus** [comment]
Here's the first Travis CI build: https://travis-ci.org/vacuus/List-Category-Posts/jobs/190846464 . I'm trying to validate with [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) (phpcs line in .travis.yaml)

**Comment by vacuus** [comment]
@picandocodigo Do you want to lint the code? I should probably check with you before I update the code to pass the phpcs test. If so, what rules should we follow? I like the idea of using WordPress Coding Standards, though they require tabs instead of spaces for indents. The code currently uses spaces. What would you like to do?

**Comment by picandocodigo** [comment]
Thanks for this work!!!

i considered using WP's Coding Standards before, but didn't agree with some of them. Tabs vs. spaces is a big one, but yeah, if it can be linted with some exceptions such as that, that would be ok.

**Comment by vacuus** [comment]
Yeah, that's doable. See this commit: https://github.com/vacuus/List-Category-Posts/commit/4982b30892c7de85d2501c3594fbfe3efcea5e22 . The current code uses two spaces for indentation so I wrote a rule to enforce that.

Are there any other rules you don't agree with? I can update code to follow whatever ruleset we decide on.

**Comment by vacuus** [comment]
Hi @picandocodigo are there certain rules you have a strong opinion on?
