### ISSUE TITLE
Help! Pagination auto-scrolls page to bottom

### ISSUE THREAD

**Issue by andeschurr** [picandocodigo/List-Category-Posts#225]
Hi,

I am displaying a list of 10 posts within my chosen category. At the end of that list, there are 4 more pages to click on. 

Each time I click on one of those pages, (which opens the same page with the next 10 posts listed), it automatically jumps/scrolls down the page as if there's an Anchor pulling it down each time.

The site is still off-line but as an example, when clicking on the page two box on the Paginator, Firebug gives me this:

`<a href="http://ethicalism.org/ethics/harm-no-one-intentionally/?lcp_page0=2#lcp_instance_0" title="2">2</a>
`
Is it this last part which is acting like an anchor? The "#lcp_instance_0"? If so how do I remove this?

Thanks sincerely for any help,

Ande Schurr

**Comment by vacuus** [comment]
That's strange. What's the shortcode you're using so I can try recreating your issue.

**Comment by andeschurr** [comment]
Hi Vacuus, 

Thanks for replying.

The shortcode I'm using is:

`[catlist name=mycategory] `

(Replacing 'mycategory' with a relevant category).

Other options I chose:
Pagination = True
Order by = Date
Posts = 10 (I've tried other numbers too)

The theme I'm using is Avada Fusion. I was putting the shortcode in a text box, within a container (that is within a column!) using the Fusion editor.

Thanks for any insight and your time.

**Comment by vacuus** [comment]
I think this is how the plugin is meant to work. Are you being taken to the beginning of your post listing? Does the browser scroll to an incorrect position?

**Comment by andeschurr** [comment]
It scrolled down so that every time I clicked on a link in this list, I had to scroll up again to actually read the top of the page. So I'm going to stop right here and move on as I have a few other options to list posts on the side bar. Thanks for getting back to me.
