### ISSUE TITLE
Undefined index: tags_as_class

### ISSUE THREAD

**Issue by sewid** [picandocodigo/List-Category-Posts#227]
Hi there,

when using the plugins widget, I get this notification when WP_DEBUG is enabled:

Undefined index: tags_as_class in /X/Y/Z/wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php on line 243

Best regards,
Sebastian

**Comment by vacuus** [comment]
Thanks for reporting this! I should have caught this when I submitted my earlier PR ( https://github.com/picandocodigo/List-Category-Posts/pull/218 ). I can probably write a test to check for these kinds of errors/warnings.

I submitted a pull request to fix this here: https://github.com/picandocodigo/List-Category-Posts/pull/228 .

**Comment by picandocodigo** [comment]
Sorry for the delay in accepting the PR. The plugin's being updated on WordPress.org's svn server as I'm writing this. Version 0.71.1 should be up in a few minutes and fix this. Thanks @vacuus!!!

**Comment by hhenshaw** [comment]
I'm running 0.71.1 and am getting the following: Notice: Undefined index: tags_as_class in /X/wp-content/plugins/list-category-posts/include/lcp-widget.php on line 40.

**Comment by lucadima15** [comment]
By now I've solved substituting this row:

> $tags_as_class = ($instance['tags_as_class'] == 'yes') ? 'yes' : 'no';

with these:

> if(array_key_exists('tags_as_class', $instance))
>        {
>         $tags_as_class = ($instance['tags_as_class'] == 'yes') ? 'yes' : 'no';
>        }
>     else 
>        {
>        	$tags_as_class = '';
>        }
