### ISSUE TITLE
How to display Past one month posts in a page.

### ISSUE THREAD

**Issue by careermedhablog** [picandocodigo/List-Category-Posts#230]
I want to display past 30 days posts in a page how can i do this.

**Comment by picandocodigo** [comment]
You can use the date range parameters for this. Check out [the documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/How-to-select-which-posts-to-show) and look for "date ranges". Posts from the last 30 days would be something like this:
`[catlist after='-30 days']`
