### ISSUE TITLE
title_class AND title_tag missed in wiki

### ISSUE THREAD

**Issue by MisaGu** [picandocodigo/List-Category-Posts#233]
I was looking for these tags and was surprised when found them not in "More parameters", but in "HTML & CSS Customization" (end of the page). Will be nice to add them in Wiki for fututre users.
All the Best.

P.S. - should not be confused with 'conditional_title' and 'conditional_title_tag' !!!

**Comment by picandocodigo** [comment]
I think most (if not all) tag and class parameters are documented in [HTML & CSS Customization](https://github.com/picandocodigo/List-Category-Posts/wiki/HTML-&-CSS-Customization). The `conditional_title` parameters are an exception since they're an exceptional value which is added by the plugin.
