### ISSUE TITLE
Adding tags to Github?

### ISSUE THREAD

**Issue by loganyott** [picandocodigo/List-Category-Posts#235]
Hello!

I started making some changes to code that I would like to apply as a patch. To do so, I'm using Composer to pull down the plugin rather than using the WordPress repo.

It would be really helpful to have the tags released to WP also tagged in Github. If I want to pull version `0.71.1` from Github, I have to use `master` and watch for another update when I'm updating plugins.

If it's not too much trouble for your workflow, could you add those tags to Github as well?

Thanks!

**Comment by picandocodigo** [comment]
Sure! I stopped using tags and releases a while ago, but I can start adding tags to Github too. Thanks!

**Comment by picandocodigo** [comment]
@loganyott I'll close this issue as I am releasing version 0.72 right now with a tag and release and am planning to continue doing so. Thanks!
