### ISSUE TITLE
thumbnail display does not work

### ISSUE THREAD

**Issue by Jstuts5797** [picandocodigo/List-Category-Posts#236]
The widget and shortcode both work great and do exactly what I want/need it to do except no matter what I try, I cannot get it to display the thumbnail image next to each post. Is this a bug? No matter what option I choose in the drop down on the widget for displaying the thumbnail it just doesn't display. And yes I have double checked that I have the box checked as well.

**Comment by ergunkocak** [comment]
posts must have featured image

   [catlist name=xxx thumbnail=yes thumbnail_size=thumbnail]

**Comment by zymeth25** [comment]
What @Jstuts5797 mentioned is not an issue any more, thumbnails do show up in the widget without a problem. The thing is the styling is bad, it needs to go into a block (not inline, anyway) element so that it doesn't cover the title.

**Comment by zymeth25** [comment]
Can be closed.
