### ISSUE TITLE
Adding a break

### ISSUE THREAD

**Issue by BeckyKelly** [picandocodigo/List-Category-Posts#237]
Please can someone help....

I'm using [catlist name="For Sale"  catlist template=div no_post_titles=yes  numberposts=2 orderby=date order=desc excerpt=yes class="lcp_catlist" posts_morelink="Read more..." thumbnail=yes force_thumbnail=yes catlist thumbnail_size=thumbnail ]

And it gives me the output on this page http://www.meadowstables.com/

I'd like to add a break after each post, you can see on http://www.meadowstables.com/sold-horses/ where there are more it looks messy.

**Comment by vacuus** [comment]
I think you could try adding `clear: both` to the paragraphs generated by catlist.

Does adding
```css
.lcp_catlist p {
  clear: both;
}
```
to your CSS fix the issue you're describing?

**Comment by BeckyKelly** [comment]
Thank you so much!! Really appreciate your help fixing this :-)
