### ISSUE TITLE
Custom fields with value 0 not working

### ISSUE THREAD

**Issue by Sarah1101** [picandocodigo/List-Category-Posts#241]
Hello,

I think there is a bug in the plugin.

I have a checkbox for my posts and I want to list all post in which the checkbox isn’t checked but this doesn’t work.

E.g.
[catlist customfield_name=”checkboxfield” customfield_value=”1″] is working
[catlist customfield_name=”checkboxfield” customfield_value=”0″] isn’t working – both posts with 1 and 0 are listed, not only those with 0.

**Comment by picandocodigo** [comment]
Thanks for reporting this! Just fixed it and it'll go out on the next release, coming later today 😄

**Comment by Sarah1101** [comment]
Great, thanks for fixing.

I've noticed another bug, see #243.
