### ISSUE TITLE
Sorting orderby=rand

### ISSUE THREAD

**Issue by briancroxall** [picandocodigo/List-Category-Posts#242]
I'm wanting to use the plugin to display 3 random posts from my blog, including images. That works well, using `[catlist name=project orderby=rand order=asc numberposts=3 thumbnail=yes force_thumbnail=yes]`. What I get is a random 3 blog posts, _but_ they are not in alphabetical order. That of course makes sense as I've asked for a random order, but I had hoped that `order=asc` would then put my 3 posts into alphabetical order.

I realize that asking for both a random _and_ a sorted list might be at odds with each other. But I thought I would ask all the same.

**Comment by picandocodigo** [comment]
Hi @briancroxall, I took a look at this and it seems it's not built into WP. If you look at the [docs for order](https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters), you can see it's possible to add more than one order to the query:
>Display posts sorted by 'menu_order' with a fallback to post 'title', in a descending order:
```php
$args = array(
	'orderby' => 'menu_order title',
	'order'   => 'DESC',
);
$query = new WP_Query( $args );
```

So you can currently pass more than one `order` value to the plugin via shortcode. Just add a space between each one:
`[catlist orderby="rand title"]`
Testing this, I couldn't work out a way to get random posts and order them alphabetically. I get random posts and the `title` attribute, as the documentation says, is just a fallback. So right now this isn't possible.

**Comment by briancroxall** [comment]
Thanks for looking into this. I'm relatively new to GitHub issues on others' repos, so I'm. It sure if this should be closed or left open for future reference.

**Comment by zymeth25** [comment]
I think you can close it @briancroxall as it has been resolved :wink: We cannot add this feature within the current implementation of the plugin.
