### ISSUE TITLE
Catlist with customfield_name / customfield_value isn't working

### ISSUE THREAD

**Issue by Sarah1101** [picandocodigo/List-Category-Posts#247]
Hi,
in my case **[catlist customfield_name="color" customfield_value="green"]** is not working.
It only works in combination with a taxonomy **[catlist taxonomy="creative" terms="colors" customfield_name="color" customfield_value="green"]**.  
According to plugin description this parameters should work also without taxonomy. 
I don't know since when this behaviour is "broken" if it is.

**Comment by zymeth25** [comment]
Maybe the answer is that only posts in the "creative" taxonomy have the customfield "color"?

**Comment by zymeth25** [comment]
Stale issue. Can be closed.
