### ISSUE TITLE
How to make title bigger?

### ISSUE THREAD

**Issue by Reala2017** [picandocodigo/List-Category-Posts#248]
Hi all, thank you to those working on this wonderful plugin.

I'm looking to increase the size of the post titles. Currently they are just standard text and I'd like them to be header size.

Thank you in advance.

**Comment by DanielSanchez94** [comment]
Urgent need to know how to enlarge the titles from catlist.

Regards

**Comment by the7th** [comment]
I think someone have to find way to add the function which is to edit the text size/styling

**Comment by vr-gallagher** [comment]
Just add CSS to your theme's stylesheet. lcp_catlist is the class that all <ul>s have for this plugin. 

ul#lcp_catlist {
    font-size: 18px; 
}

**Comment by picandocodigo** [comment]
You can find the way to edit the text size and styling by reading [the wiki](https://github.com/picandocodigo/List-Category-Posts/wiki/HTML-&-CSS-Customization). If there's any specific part there you don't understand please open a new issue, but I've written [lots of documentation](https://github.com/picandocodigo/List-Category-Posts/wiki) that address -among other things- simple tasks like changing the style of the title.

**Comment by zymeth25** [comment]
Resolved and can be closed.
