### ISSUE TITLE
More categories - show title of post's category

### ISSUE THREAD

**Issue by iholka** [picandocodigo/List-Category-Posts#250]
Hello @picandocodigo ,

I have News in my web and want to use more categories (news, press, video ...). I want to show title of post's category on every post. Is it possible?

Everything iss working fine with 1 caegory, but when i add more categories with **name=news+video+press** , it stops working at all, and i see nothing..

Is it possible to show all posts from these 3 categories and show the title of post's category on every post?

My shortcode:
[catlist name=news+video+press excerpt=yes excerpt_size=30 date=yes catname=yes thumbnail=yes posts_morelink="Prejsť na článok" template=default numberposts=6]
 
Attachment:
![lcp-show title](https://cloud.githubusercontent.com/assets/28444221/25747676/992de50e-31a8-11e7-9385-12b18f9ddca1.jpg)

Thank you for your response :)

**Comment by zymeth25** [comment]
Not possible right now. This should be a low priority feature request I think.
