### ISSUE TITLE
Override category listing in page having catlist short code

### ISSUE THREAD

**Issue by oromand** [picandocodigo/List-Category-Posts#252]
Hey there, 

Thanks for the good work.
I have a use case where I would like to display list of posts of a specific categories; In a page, I would have related articles to this page.

What I had in mind is to have the page support the catlist to be displayed and the widget take this value.
The widget might then continue having its own configuration and be dynamically overriden by the page if a catlist short code is in use.

What do you think ? Is it even doable in the wordpress approach ?

**Comment by zymeth25** [comment]
I don't quite understand what you mean. Could you post an example detailing what you would like to put on a page and what in the widget?

**Comment by zymeth25** [comment]
Can be closed. Stale issue.
