### ISSUE TITLE
Use with Links Manager?

### ISSUE THREAD

**Issue by vr-gallagher** [picandocodigo/List-Category-Posts#253]
I'm trying to use this plugin to list out the links from a Wordpress Links Manager category but it isn't working. 

My Links Manager categories have a post-type of post, so I would think it would work but nothing I try will work. 

I've tried many shortcode combinations but here's an example:

[catlist id='linkcat-256']

Links Manager assigns category as such: id=linkcat-256 taxonomy=link_category post_type=post

It must be because the links within the categories are not posts themselves—thoughts, workarounds?

**Comment by zymeth25** [comment]
The problem is you are using a wrong shortcode parameter. You are using `id` but instead of providing ids you use slugs. Try `[catlist name="linkcat-256"]`

**Comment by zymeth25** [comment]
Stale issue. Can be closed.
