### ISSUE TITLE
Morelink with id from customfield

### ISSUE THREAD

**Issue by hazeways** [picandocodigo/List-Category-Posts#255]
Hi, 
Super Cool plugin! I will have great use of this one.

I would like to add to my list, a link, post_suffix with a variable from customfield. I get the value of the customfield in the list correctly, but how can I move that inside my post_suffix as a link variable?

This is my code to illustrate what I am looking for:
[catlist name=tea orderby=title order=asc numberposts=-1 catlink=yes category_count=yes thumbnail=yes thumbnail_size=32,32 customfield_display=course-id post_suffix="<a href='http://blabla.php?id=[my customfield id]'>Tea Time</a>" customfield_display_name=no]

Can something like this be done or is there better solution to this?

**Comment by zymeth25** [comment]
@hazeways you can't do this using the `post_suffix` parameter. You would have to write a custom tamplate.
