### ISSUE TITLE
posts are breaking words.

### ISSUE THREAD

**Issue by cybergenx** [picandocodigo/List-Category-Posts#256]
The plugin is great. The issue we are having is that the content is breaking words. Parameters we are using are:
[catlist content=full numberposts=15 orderby=title order=asc name="Teams"

Example below:
The first place team was called the Titans. They had several home runs but were not able to acco
mplish anything else.

As you can see the break is incorrect.

Any help would be greatly appreciated. Thank you!

**Comment by picandocodigo** [comment]
This is probably related to the [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) CSS property. It may also be a bug in the plugin but it sounds like it might be related to CSS, can you share a link to the website?
