### ISSUE TITLE
No 'Continue Reading' shown when using explicit 'excerpt' or 'more' tag

### ISSUE THREAD

**Issue by jdenning** [picandocodigo/List-Category-Posts#257]
If I use an explicit 'excerpt' or 'more' tag in my posts, on the blog archive page(s) while I see the excerpt text, I do not see any sort of 'continue reading' link. When in this happens it may appear to the reader that the entire post text is just the excerpt. I have tried several combinations of parameters without making the link appear. Also, if I don't have an explicit excerpt I DO see a 'Continue Reading' link if the post word count exceeds the limit. Am I not understanding how to use this shortcode??

**Comment by zymeth25** [comment]
You need to use the `posts_morelink` parameter if you want to always display your 'Continue reading' link.

Can be closed.
