### ISSUE TITLE
Child Categories are not shown

### ISSUE THREAD

**Issue by dellis453** [picandocodigo/List-Category-Posts#258]
You suggest that all child categories will be displayed by default. This does not seem to be the case.
I have a category called drinks, within that there is a sub category called sloe gin. The blog post on sloe gin is not displayed despite it being displayed correctly.

If I add a category to the page of sloe gin, the blog post does display. Is there a way round this rather than listing every sub category?

**Comment by zymeth25** [comment]
Can you share the shortcode you are using? I cannot reproduce your issue.

**Comment by zymeth25** [comment]
Stale issue. Can be closed.
