### ISSUE TITLE
I just want links to categories with numbers. [catlist catlink=yes category_count=yes]

### ISSUE THREAD

**Issue by a4jp-com** [picandocodigo/List-Category-Posts#260]
I just want links to categories with numbers.

`[catlist catlink=yes category_count=yes]`

Category A (7)
Category B (11)

Is there a bug or am I doing something wrong?

**Comment by a4jp-com** [comment]
Can this plugin do this?

**Comment by picandocodigo** [comment]
I think you might be looking for [this plugin](https://github.com/picandocodigo/List-Categories) instead.

**Comment by a4jp-com** [comment]
Thank you so much for the link ^^ 
It would be so cool if this plugin could do both things.
Is there also a plugin page for the other plugin?
I'd like to help improve the plugin if possible too.
Thank you so much for your work here.

**Comment by a4jp-com** [comment]
That other plugin has a fatal error and doesn't work: 

Fatal error: Cannot declare class ListCategories, because the name is already in use in /home/a4jp/a4jp.com/public_html/1/advertshops/wp-content/plugins/List-Categories-master/list-categories.php on line 28

**Comment by picandocodigo** [comment]
@a4jp-com It looks like you might have installed the plug-in twice? Just in case, uninstall it and install it from WordPress' dashboard. It's available in the [WordPress official plugin site](https://en-gb.wordpress.org/plugins/list-categories/), but you can find it from the dashboard's "Add Plugin" menu if you search for "List Categories".

I may be wrong, but it looks like you might have installed that version and the GitHub version (they're the same code at the moment). If this doesn't solve the issue, let me know and I'll try to find some time to check it out and see if I can reproduce the error. Thanks!

**Comment by picandocodigo** [comment]
Closing this issue since there's been no response for over a month. Feel free to open an issue in the other plugin's repository if you find any further problems.
