### ISSUE TITLE
Update Vagrant machine

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#265]
Update Vagrant machine to `ubuntu/xenial` and make sure everything is still working. Most importantly for using updated and supported versions of PHP and MySQL.

**Comment by zymeth25** [comment]
I can do it. ubuntu/xenial32 I assume? or do you want ubuntu/xenial64?

**Comment by picandocodigo** [comment]
@zymeth25 Thanks! That would be awesome. I think we should go for 64 bits since it's more widely used right now.
