### ISSUE TITLE
Version 0.74 breaking site after update.

### ISSUE THREAD

**Issue by bwklein** [picandocodigo/List-Category-Posts#266]
## Error thrown Call to undefined method CatListDisplayer::get_pagination()

**I see this block of text at the top of my admin area.**
`show_pagination($params['pagination'])){ $lcp_paginator = ''; $pages_count = ceil ( $params['posts_count'] / # Avoid dividing by 0 (pointed out by @rhj4) max( array( 1, $params['numberposts'] ) ) ); $pag_output = ''; if ($pages_count > 1){ for($i = 1; $i <= $pages_count; $i++){ $lcp_paginator .= $this->lcp_page_link($i, $params['page'], $params['instance']); } $pag_output .= "
"; // Add "Previous" link if ($params['page'] > 1){ $this->prev_page_num = intval(intval($params['page']) - 1); $pag_output .= $this->lcp_page_link($this->prev_page_num , $params['page'], $params['instance'], $params['previous'] ); } $pag_output .= $lcp_paginator; // Add "Next" link if ($params['page'] < $pages_count){ $this->next_page_num = intval($params['page'] + 1); $pag_output .= $this->lcp_page_link($this->next_page_num, $params['page'], $params['instance'], $params['next']); } $pag_output .= "
"; } return $pag_output; } } // `char` is the string from pagination_prev/pagination_next private function lcp_page_link($page, $current_page, $lcp_instance, $char = null){ $link = ''; if ($page == $current_page){ $link = "
$current_page
"; } else { $server_vars = add_magic_quotes($_SERVER); $request_uri = $server_vars['REQUEST_URI']; $query = $server_vars['QUERY_STRING']; $amp = ( strpos( $request_uri, "?") ) ? "&" : ""; $pattern = "/[&|?]?lcp_page" . preg_quote($lcp_instance) . "=([0-9]+)/"; $query = preg_replace($pattern, '', $query); $url = strtok($request_uri,'?'); $protocol = "http"; $port = $server_vars['SERVER_PORT']; if ( (!empty($server_vars['HTTPS']) && $server_vars['HTTPS'] !== 'off') || $port == 443){ $protocol = "https"; } $http_host = $server_vars['HTTP_HOST']; $page_link = "$protocol://$http_host$url?$query" . $amp . "lcp_page" . $lcp_instance . "=". $page . "#lcp_instance_" . $lcp_instance; $link .= "
prev_page_num) { $link .= "class='lcp_prevlink'"; } elseif ($page === $this->next_page_num) { $link .= "class='lcp_nextlink'"; } $link .= ">"; ($char != null) ? ($link .= $char) : ($link .= $page); $link .= "
"; } // WA: Replace '?&' by '?' to avoid potential redirection problems later on $link = str_replace('?&', '?', $link ); return $link; } }`

![image](https://user-images.githubusercontent.com/12104446/33354410-aed08120-d467-11e7-8ea4-ae0f98137946.png)

**And instead of any content, this block of text on my homepage where I have a catlist shortcode.**

`show_pagination($params['pagination'])){ $lcp_paginator = ''; $pages_count = ceil ( $params['posts_count'] / # Avoid dividing by 0 (pointed out by @rhj4) max( array( 1, $params['numberposts'] ) ) ); $pag_output = ''; if ($pages_count > 1){ for($i = 1; $i <= $pages_count; $i++){ $lcp_paginator .= $this->lcp_page_link($i, $params['page'], $params['instance']); } $pag_output .= "
"; // Add "Previous" link if ($params['page'] > 1){ $this->prev_page_num = intval(intval($params['page']) - 1); $pag_output .= $this->lcp_page_link($this->prev_page_num , $params['page'], $params['instance'], $params['previous'] ); } $pag_output .= $lcp_paginator; // Add "Next" link if ($params['page'] < $pages_count){ $this->next_page_num = intval($params['page'] + 1); $pag_output .= $this->lcp_page_link($this->next_page_num, $params['page'], $params['instance'], $params['next']); } $pag_output .= "
"; } return $pag_output; } } // `char` is the string from pagination_prev/pagination_next private function lcp_page_link($page, $current_page, $lcp_instance, $char = null){ $link = ''; if ($page == $current_page){ $link = "
$current_page
"; } else { $server_vars = add_magic_quotes($_SERVER); $request_uri = $server_vars['REQUEST_URI']; $query = $server_vars['QUERY_STRING']; $amp = ( strpos( $request_uri, "?") ) ? "&" : ""; $pattern = "/[&|?]?lcp_page" . preg_quote($lcp_instance) . "=([0-9]+)/"; $query = preg_replace($pattern, '', $query); $url = strtok($request_uri,'?'); $protocol = "http"; $port = $server_vars['SERVER_PORT']; if ( (!empty($server_vars['HTTPS']) && $server_vars['HTTPS'] !== 'off') || $port == 443){ $protocol = "https"; } $http_host = $server_vars['HTTP_HOST']; $page_link = "$protocol://$http_host$url?$query" . $amp . "lcp_page" . $lcp_instance . "=". $page . "#lcp_instance_" . $lcp_instance; $link .= "
prev_page_num) { $link .= "class='lcp_prevlink'"; } elseif ($page === $this->next_page_num) { $link .= "class='lcp_nextlink'"; } $link .= ">"; ($char != null) ? ($link .= $char) : ($link .= $page); $link .= "
"; } // WA: Replace '?&' by '?' to avoid potential redirection problems later on $link = str_replace('?&', '?', $link ); return $link; } }
Error thrown
Call to undefined method CatListDisplayer::get_pagination()`

![image](https://user-images.githubusercontent.com/12104446/33354416-b60fda30-d467-11e7-8f62-3e38a79be0d6.png)

**Comment by leros** [comment]
Same here. problems(and benefits) gone when deactivating the plugin.

**Comment by tim1600** [comment]
Upgrading to V 0.74 broke each page which featured LCP custom code. Have deactivated plugin (hopefully a very temporary measure) until the issue gets fixed. Trouble is, as per above comments, pages now display raw html code.

**Comment by lokedavid** [comment]
Same issue here. Will be deactivating the plugin temporarily.

**Comment by xresidentx** [comment]
In lcp-paginator.php line 1,  "<?"  should be  "<?php" that fixes php code being displayed in the page.

Anyways, my template is still broken since "get_pagination" method was removed in this version (0.74).
Fatal error: Uncaught Error: Call to undefined method CatListDisplayer::get_pagination()

**Comment by bwklein** [comment]
As a note to all here, I was able to get to my admin pages and disable the plugin, then I used [WP Rollback](https://wordpress.org/plugins/wp-rollback/) to return to the previous release.  This brought my site back to normal again while waiting for the fix and next release.

**Comment by shrijan00003** [comment]
@bwklein  thanks sir able to recover the site.

**Comment by picandocodigo** [comment]
Can everyone please test version 0.74.1 and let me know if this is still an issue for you please? Thanks!

**Comment by bwklein** [comment]
@picandocodigo I just updated to version 0.74.2 and everything works as expected. Thank you!

**Comment by picandocodigo** [comment]
Awesome, thanks @bwklein!
