### ISSUE TITLE
Empty categories automatically hidden

### ISSUE THREAD

**Issue by lucadima15** [picandocodigo/List-Category-Posts#271]
Hello.
In the last release, empty categories in the widget are no more choosable, while before it was possible to do it.

Please, reintroduce the possibility.

I did it manually changing line 70 in file lcp-widget-form.php from:
$categories=  get_categories();
to
$categories=  get_categories(array('hide_empty' => false));

**Comment by picandocodigo** [comment]
Thanks for reporting it @lucadima15! I've fixed it and should be available in the next version of the plugin.
