### ISSUE TITLE
How to Change Ul Li bullet or circle is none.

### ISSUE THREAD

**Issue by princegupta0144** [picandocodigo/List-Category-Posts#272]
After this code ----> 
**[catlist currenttags="yes" name="Fashion" numberposts="5"]**
Show  result 
Example-
Result-
**
- Lectus neque pellentesque
- Feugiat purus maecenas vitae
- Volutpat tristique sed libero
- Eget porttitor lacus cursus**

I don't need to add bullet list in this example.
Tell me **how I change or list-style-type:none;**

**Comment by picandocodigo** [comment]
Hi @princegupta0144, just add this to your theme's CSS:
```css
.lcp_catlist li{
	list-style: none;
}
```

This will change the list style to none in every instance of List Category Posts you use. If you want to do this for just this list in particular, add a class to your shortcode:
`[catlist currenttags="yes" name="Fashion" numberposts="5" class="lcp_fashion"]`
And add this to your theme's CSS file:
```css
.lcp_fashion li{
	list-style: none;
}
```

**Comment by princegupta0144** [comment]
and how to change font colour

**Comment by picandocodigo** [comment]
@princegupta0144 Just customize the CSS for the `lcp_catlist` or `lcp_fashion` classes. If you need help with getting started with CSS, I recommend checking [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS).
