### ISSUE TITLE
Pagination is gone with update to 0.74.2 

### ISSUE THREAD

**Issue by laserjobs** [picandocodigo/List-Category-Posts#274]
Updated the plugin from 0.73.1 to 0.74.2 and pagination is gone. 

shortcode is setup as follows
[tabs]
[tab title="aaa"][catlist id=2811][/tab]
[tab title="bbb"][catlist id=2801][/tab]
[tab title="ccc"][catlist id=2802][/tab]
[tab title="ddd"][catlist id=2803][/tab]
[/tabs]

**Comment by laserjobs** [comment]
Looks like I have to as pagination=yes for it to work

**Comment by picandocodigo** [comment]
Hi @laserjobs, you always had to set `pagination=yes` in the shortcode for it to work. That's how it's supposed to work at least. Is it working for you now using this parameter?

**Comment by zymeth25** [comment]
@picandocodigo  I think what @laserjobs  means is that the default pagination setting that a user can define in the backend doesn't work anymore. And I think he's right. If there is no `pagination=yes` in the shortcode but "Pagination" is set to true in the backend, pagination won't be displayed and PHP would log a Notice:
`Notice: Undefined variable: lcp_pag_present in /vagrant/include/lcp-paginator.php on line 30`

I looked at the code and indeed, there is a bug ;)

**Comment by picandocodigo** [comment]
Oh, ok, now I get it! Thanks @zymeth25! I'll check that out and review your PR's later today 🤘
