### ISSUE TITLE
Code hanging out on my page since last upgrade

### ISSUE THREAD

**Issue by suesutcliffe** [picandocodigo/List-Category-Posts#275]
Here is the page.... https://www.suesutcliffe.com/hosting/

My hosting company wrote...

from the looks of this one error, there seems to be an issue with the plugin List category posts. Line 30 reads "       ($lcp_pag_present &&" which looks like it is attempting to join something, but I don't know this plugin enough to fix the issue. All I can suggest is reaching out to Fernando at the WordPress Support for the plugin: https://en-ca.wordpress.org/plugins/list-category-posts/

I use this plugin in many spots and have recommended it to many, so removing it is a big problem I don't need today. Is someone able to help?

**Comment by suesutcliffe** [comment]
I just noticed this problem, and like the author, when I deactivate the plugin the error message comes back...  https://www.suesutcliffe.com/hosting/

My hosting company wrote...

from the looks of this one error, there seems to be an issue with the plugin List category posts. Line 30 reads " ($lcp_pag_present &&" which looks like it is attempting to join something, but I don't know this plugin enough to fix the issue. All I can suggest is reaching out to Fernando at the WordPress Support for the plugin: https://en-ca.wordpress.org/plugins/list-category-posts/

I use this plugin in many spots and have recommended it to many, so removing it is a big problem I don't need today. Is someone able to help quickly, or should I have everyone deactivate the plugin?

**Comment by zymeth25** [comment]
This issue was already discussed in #274. But even without it being fixed your website shouldn't be printing this message. It seems you have Wrdpress Debug mode turned on. Please have a look at the `wp-config.php` file and make sure it includes the line `define( 'WP_DEBUG', false );` If you don't know how to do this, ask your hosting provider for assistance.

**Comment by zymeth25** [comment]
I see your website looks fine now @suesutcliffe , you can close this issue.

**Comment by suesutcliffe** [comment]
My new webmaster turned off the WordPress debug mode and the message disappeared.
I'm guessing my last webmaster turned it on but forgot to turn it off?
Thank you so much for your help @zymeth25
