### ISSUE TITLE
Templates - location of the tag in the shortcodes

### ISSUE THREAD

**Issue by differentieel** [picandocodigo/List-Category-Posts#281]
thank you for doing a great job developing this plugin

Using the **template option** to show the other posts in a category (see https://ferrie.audio/2017/12/elevator-voices/ at the bottom of the blogpost) I found out that the template system only works when the first tag in the row is the template tag as:
[catlist **template=albumextra** catname=yes catname_class=h2 excludeposts=this category_description=yes categorypage=yes . . . . . . ]

First: It maybe nice to have this **order thing** in the description on the Template Using Page

And second: would you be so kind to improve the template system?
Or put it on a higher position of your TO-DO list ;)

Thank you, ferrie

**Comment by picandocodigo** [comment]
Hi @differentieel. I didn't know this was happening. This is probably a bug, it shouldn't be necessary for the template parameter to be the first one in the shortcode for it to work.

Regarding any improvements, is there anything specific you would like to have in the template system?

**Comment by differentieel** [comment]
thank you for responding - - it would be nice to have insight how the template system works - - 

is there a "header" (on my blog the "Album Name" and the "Album Description" - - which is a category) - - what can you place there - - if possible make it draggable to change the order
 
is there an order to follow or may i decide myself what comes first in the "body" (on my blog the tracks)

then i would like to have more templates and have all the parameters inside - - - like to have tracks of a certain year - - tracks used in Art Works - - probably sorted on tags

that kinds of things - - if you need more specific details please mail me - or use my contact page on my website - - that one is safe to use ;)

**Comment by differentieel** [comment]
about the "improvements" question - - i have been thinking about a sample where you could look at Fernando - - it might useful to have a look at the admin structure of the [Crelly Slider](https://github.com/fabiorino/crelly-slider) plugin - - this is for non-coders like me - a very understandable way of treating templates without the need to know how to use WP-code with all its rules

_BTW - ask me to make you a complex piece of music and i am happy to do that for you - but don't ask me to code an inch ;)_

**Comment by zymeth25** [comment]
Cannot reproduce this. Templates work regardless of where the parameter is placed.

**Comment by differentieel** [comment]
sorry to hear this Klemens @zymeth25 - i had hoped there was a reason
on my website the mix between a template and short codes keep on working - although i am still missing the "category description" - - - it would be a change to explain where the album (the category) is about

anyway - thank you for investigating - can i send you a piece of music?
if yes, DM me your emailaddress
