### ISSUE TITLE
How to Change permalink appending "AMP" at the end 

### ISSUE THREAD

**Issue by emanuelcelano** [picandocodigo/List-Category-Posts#287]
I have created a new template for AMP pages.
I need to list all pages appending the "/amp/" at the end.

Please can you tell me what i need to add before :
$lcp_display_output .= $this->get_post_title($post, 'h3', 'lcp_post');

I try with this :
  foreach($post as $id){
  $link = get_permalink($id).'/amp/';
  $title = get_the_title($id);
  $post.= '<a href="'.$link.'">'.$title.'</a>'.'<br/>' ;
}
but not work

Thanks

**Comment by zymeth25** [comment]
Not supported by the plugin. [str_replace](http://php.net/manual/en/function.str-replace.php) could get it done though.
