### ISSUE TITLE
Can't make even a basic listing show up

### ISSUE THREAD

**Issue by aMoofie** [picandocodigo/List-Category-Posts#290]
Server is using PhP 7.0.22, and I'm using an up-to-date WP. 

Downloaded the plugin, and began with a minimalistic [catlist] ... however when I preview the results, they're blank.  I've tried using the text box in the regular WP editor, and also the tinymce text editor included in the SiteOrigin plugin/widgets ... and I get the same result no matter what I try. I've also tried using category names and/or ID's, eg: [catlist name=meditations], [catlist id=1] ...

If it makes a difference, I'm working on Windows 8.1, using the latest version of Opera.

**Comment by zymeth25** [comment]
Hi @aMoofie 

Have you tried with with debug mode on? If so, can you see any error messages in the debug log or in the display?

**Comment by aMoofie** [comment]
@zymeth25 Hey! I would love to do that ... but here I have to admit to being completely in the dark. Where do I find the "debug mode"? And perhaps you could also give me some advice on what I'm looking for once I find and utilize it ...

Really appreciated!

I'm noting that now there's another plugin which works well when using it in a provided "widget", but then shows nothing on the screen when used as a shortcode ... and I'm beginning to wonder if the same issue is causing both.

Thanks for your reply! Waiting to see if you can tell me how to implement your advice.

**Comment by zymeth25** [comment]
Ok @aMoofie first of all could you send a link to a website where you are using the shortcode and encountering problems?

To turn on WordPress debug mode, find the `wp-config.php` file that is located in your website's main directory and look for `define('WP_DEBUG', false);`, change it to `define('WP_DEBUG', true);`, save and close the file. Now if there are any error messages generated by the server you should be able to see them on your website.

**Comment by aMoofie** [comment]
Okies ... I have debug enabled ... and this was the visual output in a preview: 

I have - _left square bracket_ advMenu title="a title" _right square bracket_ right here -->  <--

In the between the arrows is where I had the shortcode. No errors were generated, unfortunately.

The website's addy is [philippians123.org](url), and I haven't got any published pages which have the advMenu shortcode on them, since it doesn't work, however I have lots of pages in which I used the advMenu widget, [http://philippians123.org/food-for-the-journey/poem/pgmv1/](url) is one of them, with the advMenu being the one on the left side of the page.

I appreciate your help!

**Comment by zymeth25** [comment]
Looks like something is interfering with shortcode rendering since neither `[advMenu]` or `[catlist]` work. There could be many reasons causing this, bad theme design or a conflicting plugin. To make sure there are no plugin conflicts you can try disabling all plugins but the List Category Posts and see of the `[catlist]` shortcode works. If not, it is likely that your theme is causing the problem.

**Comment by aMoofie** [comment]
I will do that today ... and if I can nail down the culprit (or not), I'll come back and let you know what it is. advMenu and catlist are the only two shortcodes that aren't working, however I recently loaded up on shortcode plugins, so one of them could certainly be causing the issue.

Thanks again! On my way to try to sort things out ...

**Comment by aMoofie** [comment]
I deactivated _all_ of my other plugins with the exception of _Wordfence Security_, and neither of my non-working shortcodes worked. I then deactivated advMenu while catlist was activated, and vice-versa, and it made no difference. The only difference I could see was that when any of the plugins were deactivated, I could see the actual shortcode - `[advMenu]` or `[catlist title="a title"]` when previewing the results.

... Sincerely hoping you have more suggestions .... I really thought that a plugin conflict would be a good candidate for causing the issue ...

**Comment by zymeth25** [comment]
I tested your theme (Ultra) and it works with the LCP plugin, so you can rule that out as well.

One question: what is the **post type** of the posts you want to list?

**Comment by zymeth25** [comment]
@aMoofie  try `[catlist post_type="any"]` and tell me what happens.

**Comment by aMoofie** [comment]
Well! 10 random posts showed up!!! I've set the unlinked page to _public_ so that you could see the results.

Wow! Progress! :o)

**Comment by aMoofie** [comment]
And forgot to put in the link ... [http://philippians123.org/prayers/](url)

**Comment by zymeth25** [comment]
Ok, finally, I should have thought about it earlier...

So the problem is the `[catlist]` shortcode lists posts of type "post" by default. Only. To list other posts types you need to use the `post_type` shortcode parameter. All of this is described in the documentation:

> post_type - The type of post to show. Available options are: post - Default, page, attachment, any - all post types. You can use several types, example: [catlist post_type="page,post" numberposts=-1]

It didn't work because what you want to list is not of post type "post". I assume it's "page" but you can also use "any" as in my example and then select specific posts with `id` or `name` shortcode parameters, or any other of the vast amount of options this plugin has.

**Comment by aMoofie** [comment]
I'm going to run with this ... and see what I can sort out. You have no idea how much I appreciate your help! And yes, it is type "page" ... one of the reasons I installed the plugin was because it said it worked with both pages and posts. 

Even  after having read the documentation, I was still vague on what was needed. I've had a nearly 20 year hiatus from web design, and have only started again in the last month ... and it's a steep learning curve for an old lady like me, especially since so much has changed. I'm still thinking in old HTML and CSS terms ... plugins and so on are _wonderful_, but I haven't quite got the hang of it all yet.

Thanks so much for your time and trouble. I'm going to go from the example you've given me, and try to work up from there.

**Comment by zymeth25** [comment]
Yes, the plugin supports "posts", "pages" and actually any other post type you can think of. But by default only lists "post". And I think this should be mentioned somewhere at the top of the documentation...

Anyway, good luck with your website and don't forget to close this issue 🙂

**Comment by aMoofie** [comment]
Thanks again!!!
