### ISSUE TITLE
"this" for custom taxonomy term

### ISSUE THREAD

**Issue by pjv** [picandocodigo/List-Category-Posts#293]
Similar to `categorypage` for standard categories and `currenttags` for tags, it would be convenient if we could specify a custom taxonomy and then something like `terms=this` to use the terms in the specified taxonomy that the current post has applied to it for selecting other posts.

e.g. `[catlist taxonomy='person' terms=this]` would select posts that had terms applied to them from the person taxonomy that matched any terms from that taxonomy that are applied to the current post.

**Comment by zymeth25** [comment]
That would be a nice new feature 🙂

**Comment by dbjpanda** [comment]
@pjv Did you get any alternative or workaround ?

**Comment by pjv** [comment]
@dbjpanda the workaround is just manually applying all the necessary terms to each post and then explicitly listing them in the category post shortcode. It works fine but it's less elegant than it could be.

**Comment by klemens-st** [comment]
A comment on this from the forums:

https://wordpress.org/support/topic/current-taxonomy-terms/#post-15130245

**Comment by klemens-st** [comment]
@pjv @dbjpanda Just letting you know this feature has been merged and included in 0.88
