### ISSUE TITLE
Centering Post Title

### ISSUE THREAD

**Issue by Linda990** [picandocodigo/List-Category-Posts#297]
I am helping an artist friend with a website. She posted some poetry and I wanted to show it all on one page. Your plugin is wonderful! 

I am curious if there is a way to center the post title?

This is the page: http://karengines.com/poetry/ so you can see what I am talking about.

Thank you so so much
Linda

**Comment by picandocodigo** [comment]
Hello @Linda990,
For that particular page, you can add this to your theme's CSS:
```css
.lcp_catlist p{
	text-align: center;
}```

This will center every paragraph, including titles.

**Comment by Linda990** [comment]
Thanks! But what if we create other category list pages of regular blogs
that are not needed to be centered? That is planned down the line, so
looking ahead.

Linda

**Comment by picandocodigo** [comment]
I think you can use the `instance` parameter to identify each list. So if you use:
`[catlist instance=poems]`
It will print the list with an id like this:
`id=lcp_instance_poems`
And then in your CSS you could do:
```css
#lcp_instance_poems p{
  text-align: center;
}
```
And it would only apply that style to that particular instance. Or you can set an ID or class to whatever is wrapping the list and set the style only to the lcp_catlist class when it belongs to that particular wrapper.

**Comment by Linda990** [comment]
YES! That worked, thank you ever so much!
