### ISSUE TITLE
Category AND Tag

### ISSUE THREAD

**Issue by jjrharper** [picandocodigo/List-Category-Posts#298]
I might have mis-understood how it works but is there a way to show posts that have a specific category **and** tag in the shortcode?

I have a common tag ('updates') but a different category for each product. 

I want to be able to list posts relating to updates for a specific product however I am getting all the 'updates' tagged posts appearing on each product list.

Going with this approach I had the idea in mind to have a 'Updates' page listing all updates too.

**Comment by zymeth25** [comment]
It is possible. Please read the docs cerefully. You need to use the `tags` parameter and the `id` (or `name`) parameter.

**Comment by jjrharper** [comment]
I think that is what I have in my shortcode:

This is the shortcode on the 'Trade POS' product page
`[catlist name="sashapps-tradepos" tags="sashapps-updates" date=yes orderby=date order=desc]`

This is the shortcode on the 'POS Label' product page
`[catlist name="sashapps-poslabel" tags="sashapps-updates" date=yes orderby=date order=desc]`

I have a post with the 'sashapps-tradepos' category and the 'sashapps-updates' tag. However this post is also listed on the 'POS Label' product page. I assume that is becuase of the tag? Its like the shortcode is `name` OR `tag` but I want `name` AND `tag` if that makes sense?

**Comment by zymeth25** [comment]
I cannot replicate your issue. The plugin *does* use the AND relationship in this case and what you are describing shouldn't be happening. I created the exact scenario you described and it worked as expected on my end.

So let me ask some further questions, please specify:
* WP version, Plugin version
* post type of the post that is being displayed incorrectly
* does the post have any other categories or tags?
* have you tried disabling all other plugins and testing with a default theme?

**Comment by jjrharper** [comment]
I have solved it! The category hadn't been setup so no slug existed for 'sashapps-poslabel' - so it appears as this didn't exist but the tag did it this caused the post to show up.

**Comment by zymeth25** [comment]
Resolved and can be closed.
