### ISSUE TITLE
starting_with parameter problem

### ISSUE THREAD

**Issue by Beartm1992** [picandocodigo/List-Category-Posts#299]
Hello,

I have a problem with **starting_with** parameter. Starts with E, but does not perform filtering with starting_with="e" enabled.

This works: [catlist tags="amiga" pagination=yes numberposts=5 date=yes], 
but it does not show: [catlist tags="amiga" starting_with="e" pagination=yes numberposts=5 date=yes].

![2018-02-23_131038](https://user-images.githubusercontent.com/36763978/36593957-66ecc3a4-189c-11e8-9d54-1211b3242bc6.png)
![2018-02-23_130847](https://user-images.githubusercontent.com/36763978/36593966-718f76e4-189c-11e8-9a45-1407ff5f1b33.png)

Thanks for your help.

**Comment by zymeth25** [comment]
Fixed in #289

This is most probably an issue with character sets. You can try the code drom the PR mentioned above to make sure it is so.

**Comment by Beartm1992** [comment]
working fine, thank you.

**Comment by zymeth25** [comment]
Great! You can close the issue.
