### ISSUE TITLE
Issue with CSS on mobile, using catlist

### ISSUE THREAD

**Issue by davidlefebvre** [picandocodigo/List-Category-Posts#300]
Hi

I think my problem is coming from the catlist code. I use a child for my Wordpress theme. I have a line of code : .withthumb .lcp-container {margin-left: 220px;}. It is, I guess, for the desktop webpage. But when I go on mobile, the visualization is totally messed up. Even if I put margin-left: 0px, it doesn't work.

You can see here my test (use the menu and go to Actualité) 
http://mobiletest.me/iphone_5_emulator/?u=http://www.montheatre.qc.ca/espace

Is there a way to fix this ?

![image](https://user-images.githubusercontent.com/36776128/36616709-bc7adfac-18b2-11e8-8542-e1dcb25ba744.png)

![image](https://user-images.githubusercontent.com/36776128/36616757-e2d948c8-18b2-11e8-9fbd-97855a03a76f.png)

**Comment by zymeth25** [comment]
Have you already fixed this? I've just tested your site on mobile and desktop and it flies 🙂

**Comment by davidlefebvre** [comment]
@zymeth25 You're right.. ! I don't know what happened, to be blunt. I guess it took some time to the child to manisfest itself... ! Thanks !
