### ISSUE TITLE
Show post category name

### ISSUE THREAD

**Issue by Beartm1992** [picandocodigo/List-Category-Posts#302]
Sorry, but I have another question ...

After the entries are listed, I can display the date of the post but not the category of the post.  I can write the category ID, but I should have the name of the category. I'm just trying to set the catlink and catname parameters, not the category after typing.

My other question would be how to insert a character between the name and date of the upgraded entry, eg | mark?

This code is currently: [catlist name=cheat pagination=yes numberposts=30 date=yes]

Thanks and sorry if my question was too simple, I could not find the right answer in the wiki and the issues that were closed.

**Comment by zymeth25** [comment]
Re both your questions: this is not supported by the plugin out of the box. It can be done in a custom template very easily though. You can [read the docs about this](https://github.com/picandocodigo/List-Category-Posts/wiki/Template-System) and then try building your template.
