### ISSUE TITLE
Orderby parameter not working

### ISSUE THREAD

**Issue by Liuhuparta** [picandocodigo/List-Category-Posts#307]
I've added the plugin to my website and it mostly works. However, I can't seem to get the _orderby_ parameter to work. It always lists all posts by ID no matter what. Ordering (asc/desc) does work. I've tried adding the _orderby_ parameter to the shortcode and to the general settings with no success.

### Expected behavior
- A title (created on 17.3.2018)
- B title (created on 16.3.2018)
- C title (created on 18.3.2018)

### Actual behavior
- C title (created on 18.3.2018)
- A title (created on 17.3.2018)
- B title (created on 16.3.2018)

### Shortcode used and steps to reproduce the behavior
[catlist name=mycategory orderby=title]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WordPress, Version 4.9.4
List category posts, Version 0.76.1

**Comment by Liuhuparta** [comment]
I tried deactivating all plugins. It made no difference. Is there something else I could do in order to troubleshoot the problem?

**Comment by zymeth25** [comment]
Try switching to a default theme (Twentyseventeen). Can you specify the server's PHP version?

**Comment by Liuhuparta** [comment]
I tried switching to Twentyseventeen. The problem persists.

Server's PHP version is **7.0.25-0ubuntu0.16.04.1**

If I turn debug mode on there are multiple identical notices. It appears to be linked to using multiple categories (with a +). The notices go away, if I use only a single category. It's not linked to my problem I believe.
`Notice: Trying to get property of non-object in /var/www/wiki.daimyria.fi/html/wp-includes/class-wp-query.php on line 3502`

**Comment by zymeth25** [comment]
Yes, this PHP Notice is not ralated to the problem.

Where is the shortcode located? Have you tried other sections (like a widget)?

**Comment by SherylMartin** [comment]
I'm having the same problem; can not get posts to sort by date desc. Disabled all other plugins, no help. Theme is responsive-mobile (current), WP version 4.9.4. Don't have access to the actual server, still attempting to get the PHP version. But it's regularly updated to the latest version.

Any ideas? 

shortcode: [catlist category="featurehighlights" template=div class="sidebarHL" conditional_title="Featured Highlights" orderby=DATE order=DESC date=yes numberposts=15 pagination=yes]

**Comment by zymeth25** [comment]
@SherylMartin try `orderby="date"`, lowercase.

Let me know if it helps.

**Comment by SherylMartin** [comment]
nope; didn't help

**Comment by SherylMartin** [comment]
is 'date' the 'published' date set on the post, or is it reading some other date? because I have to set that date manually to a date related to the content of the post, not what date I created the post. (if that makes sense)

**Comment by zymeth25** [comment]
`date` is the post's publish date. To achieve what you described you would have to store your custom date numerically in a custom field and then use `customfield_orderby` to order by this custom field. More on this in the documentation.

**Comment by zymeth25** [comment]
Or you could manually change "publish" date, that would work too

**Comment by SherylMartin** [comment]
ok, so it's reading the publish date which is what I had assumed. so that's not the problem. I'll try playing with a custom field, see if I can get it to sort that way. Thanks, and if you think of anything else i can try please post. If I figure it out, i'll post.

**Comment by SherylMartin** [comment]
it works if I use the id for the category instead of the name; sorts by date desc

**Comment by Liuhuparta** [comment]
I tried again with using IDs instead of names. Didn't help. _Order_ works (asc/desc) but _orderby_ does absolutely nothing. They're always arranged based on their IDs (order they were created).

The shortcode is located in the content of a simple page.

**Comment by SherylMartin** [comment]
we may have two different problems.  this is the shortcode that works for me: [catlist id=17 template=div class="sidebarHL" conditional_title="Featured Highlights" orderby=date order=DESC date=yes numberposts=15 pagination=yes]

**Comment by Liuhuparta** [comment]
I tried that (stripped out all unneeded stuff) `[catlist id=2 orderby=title order=ASC date=yes]` and it doesn't work. It doesn't matter what I put into the `orderby`, it always orders them by date.

**Comment by zymeth25** [comment]
Thanks for all the details. It seems the problem might have to do with WordPress itself rather than the plugin. I'm in the middle of researching this but it looks like `Wp_Query` orderby (which is what the plugin uses) doesn't deliver expected results sometimes. I'll let you know when I know more.

**Comment by zymeth25** [comment]
Ok, so it's clear that those are two separate problems

@SherylMartin This is pretty weird, I'll take a closer look later.

@Liuhuparta There must be something modying `WP_Query`, here's what you should try:

Go to `wp-content/plugins/list-category-posts/include/`, open file `lcp-catlist.php`.
Find this piece of code (starting on line 78):
```php
// for WP_Query compatibility
// http://core.trac.wordpress.org/browser/tags/3.7.1/src/wp-includes/post.php#L1686
$args['posts_per_page'] = $args['numberposts'];
```
and just below it add this line:
```php
$args['suppress_filters'] = true;
```
Save and exit. Try opening your page once more and see if anything changed.

**Comment by zymeth25** [comment]
@SherylMartin I looked at your shortcode and the answer is simple, you tried:
`[catlist category="featurehighlights" template=div class="sidebarHL" conditional_title="Featured Highlights" orderby=DATE order=DESC date=yes numberposts=15 pagination=yes]`
but there is no such shortcode parameter as `category`, you should have used `name`.

**Comment by Liuhuparta** [comment]
I tried adding `$args['suppress_filters'] = true;` to `lcp-catlist.php` but it change anything.

**Comment by zymeth25** [comment]
Ok, one more thing: go back to lcp-catlist.php and just after line 83 add this line:
```php
var_dump($wp_query->request);
```

Then post here what the output was.

**Comment by Liuhuparta** [comment]
The dump is `NULL NULL NULL`. It's the same if `$args['suppress_filters'] = true;` is there or not.

**Comment by zymeth25** [comment]
So let me recap this:
* you added `var_dump($wp_query->request);` just after line 83 in lcp-catlist.php
* all other plugins were deactivated
* default theme was on
* you opened a page with the `[catlist]` shortcode and you saw `NULL` as the result of `var_dump`

If all of the above are true it means something is wrong with your WP installation or its environment. It's very hard to say. If you feel like goig further with this, try creating a fresh WP install.

**Comment by Liuhuparta** [comment]
I did more testing and for a reason or another the listing now works correctly with all plugins activated with the default theme. With my current theme ([WikiWP](https://wikiwp.com)) the listing goes always by ID. The theme is old so that's probably the reason. Do you have any tips on how I could still use the theme and fix the problem?

`var_dump($wp_query->request);` still prints `NULL` even with the default theme and all plugins deactivated. `$args['suppress_filters'] = true;` doesn't do anything.

**Comment by Liuhuparta** [comment]
That fixed the problem. Thank you! I highly appreciate your help. 🙂
