### ISSUE TITLE
Count the posts

### ISSUE THREAD

**Issue by jpdupont** [picandocodigo/List-Category-Posts#308]
Is it possible to count the number of post to display ?
To put half part in first column, and half part in second column, with offset?

**Comment by zymeth25** [comment]
You would have to use `numberposts` and `offset` and set them manually in two separate shortcodes.

However, this question has been asked before and in my opinion the best way to solve aby layout issues is CSS. You can just use `[catlist numberposts="-1"]` to retrieve all posts and then adjust layout in CSS code. It's not difficult and column display can be achieved in many different ways ob CSS.
