### ISSUE TITLE
display does not respect post_type parameter

### ISSUE THREAD

**Issue by jonathanasbell** [picandocodigo/List-Category-Posts#309]
[catlist name="Buy" post_type="page" post_status="publish"]

I still get Post types when I should ONLY get Page types

**Comment by jonathanasbell** [comment]
also [catlist id="48"] does not work at all. I get nothing

**Comment by picandocodigo** [comment]
Is 48 the id for a page? Did you try `[catlist id=48 post_type="page"]`?

**Comment by jonathanasbell** [comment]
Yes. See page asbell.staging.wpengine.com and your shortcode is in the buy and sell section

**Comment by jonathanasbell** [comment]
FYI 
I tried using id number, category name
I tried with and without double quotes
I tried post_type="page,page"
and when I tried I tried post_type="page,post" I got the same result as I tried post_type="page"
Oddly enough, in the preview screen of the page builder it looks like it works

**Comment by zymeth25** [comment]
>Oddly enough, in the preview screen of the page builder it looks like it works

This indicates you may be using a caching plugin that interferes with LCP, but to make sure follow this procedure:

1. Make sure you have the latest versions of WP and LCP installed
2. Enable debug mode in `wp-config.php` and make sure there are no errors displayed on your test page
3. Deactivate all plugins but the LCP plugin.
4. Switch to a default theme
5. Check if the issue still exists. If it does, let me know. If it doesn’t:
6. Start activating your installed plugins (and theme) one by one. Before each element is enabled, check if your issue occurred.
7. Let me know which plugin (or maybe theme) triggered the issue

**Comment by zymeth25** [comment]
Can be closed. No answer for a long time.
