### ISSUE TITLE
Listing posts/pages with post id?

### ISSUE THREAD

**Issue by kulturwork** [picandocodigo/List-Category-Posts#310]
Hi there - 
Many thanks for this great plugin and your very helpful documentation. Now, **is there a way to list posts with post ids**? Similar to the excludeposts function, only 'include'? Couldn't find the option anywhere - apologies if I should have!

**Comment by zymeth25** [comment]
No, this is not supported. But why not just add a tag or category (or a custom taxonomy) to the posts you want to list and use it in the shortcode?

**Comment by kulturwork** [comment]
Thanks, yes - have just started to work in this direction. Trying to list upcoming events separately, but it'll do for now. Many thanks!
