### ISSUE TITLE
Pagination and page numbers

### ISSUE THREAD

**Issue by johnwillimas** [picandocodigo/List-Category-Posts#311]
### Actual behavior

Not clear if this can be achieved by editing the CSS but what I am trying to do is to have pagination on a list of posts but to only allow the forward and back buttons or a "<<, page n+1, page n+2, page n+3, >>, Last Page" style of navigation rather than the whole long list of page numbers.

**Comment by zymeth25** [comment]
It is not possible with just CSS right now. I agree that pagination is not the friendliest feature and needs to be improved. Your suggestion is very good.

**Comment by johnwillimas** [comment]
Thanks for letting me know. Cheers. John.
