### ISSUE TITLE
catlink for taxonomies

### ISSUE THREAD

**Issue by lizeidsness** [picandocodigo/List-Category-Posts#313]
I would like to use this shortcode to make a listing of custom post types showing their custom taxonomy as headings.  like catlink, but for taxonomies.  Not currently possible.  Is there another way?

like this:
`[catlist post_type='customtypename' catlink=yes]`

My customposttype does not have 'categories', but a custom taxonomy.

**Comment by zymeth25** [comment]
You can create a [custom template](https://github.com/picandocodigo/List-Category-Posts/wiki/Template-System) and implement the [get_term_link](https://developer.wordpress.org/reference/functions/get_term_link/) function.
