### ISSUE TITLE
numberposts=4 

### ISSUE THREAD

**Issue by hybridstudios** [picandocodigo/List-Category-Posts#315]
### Expected behavior
Only 4 posts to be visible

### Actual behavior
All are visible. 

### Shortcode used and steps to reproduce the behavior
[catlist name=ceo-updates numberposts=4 excerpt=yes excerpt_strip=no posts_morelink="Read more" posts_morelink_class=basic-link title_tag=h3 date_tag=div date_class=full-meta-data date=yes]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP 4.9.6, LCP 0.76.1  -- set the variable in settings to 4 as well as used numberposts=4

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by zymeth25** [comment]
I can't recreate this. This shortcode runs ok in my tests. Have you tried disabling all other plugins?
