### ISSUE TITLE
For some categories not all post shown

### ISSUE THREAD

**Issue by parthi2929** [picandocodigo/List-Category-Posts#319]
### Expected behavior
All posts under particular category to be shown

### Actual behavior
For 'Misc' category, not entire list of posts under it are shown (shown in logged in mode, but general mode or without login, that is what is viewable to public, it is not appearing)

### Shortcode used and steps to reproduce the behavior
Not sure what steps are causing it, because other category lists ok.

Here is the full list..
![2018-07-08_09h52_13](https://user-images.githubusercontent.com/11896263/42416775-736c2850-8295-11e8-8104-018f89b3d273.png)

..which is missing in link below in actual link 
https://www.rparthiban.com/articles/blog/

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
4.9.6 | 0.77 

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by parthi2929** [comment]
I am silly, just discovered those posts are private. Sorry.

**Comment by parthi2929** [comment]
I could not close this issue myself. Sorry for inconvenience.

**Comment by zymeth25** [comment]
You can close it yourself. There should be a button somewhere below the field where you can type.
