### ISSUE TITLE
Read More to go to the whole post instead of the category

### ISSUE THREAD

**Issue by TS-GIT-Beta** [picandocodigo/List-Category-Posts#325]
Hi, I am at www.timothysteward.com and for the front page, I would like for the 
Read More to go to the rest of the article. Instead it takes them to a category page,
and isn't intuitive on how to read the rest of the article, or that there is more of the 
article to read.

Is there a way around this? I tried using other plugins, but they messed up the
excerpt formatting. This one is very close to what I need.

It is good to be able to click on the main category and that go to the category, 
but would like to have some kind of option for the Read More to go to the whole
post so they could read the rest of it.

**Comment by zymeth25** [comment]
Hi

First, what is the exact shortcode you tried? Which version of WP and LCP are you running?

**Comment by TS-GIT-Beta** [comment]
Hi, thanks for responding - I am using it as a widget on the home page. I have attached some images of my settings. -

![capture - widget 1](https://user-images.githubusercontent.com/1629411/42828545-49439fa2-89ae-11e8-978d-d3b48f3ed05e.PNG)
![capture - widget 2](https://user-images.githubusercontent.com/1629411/42828548-49d9fd4e-89ae-11e8-8f5c-016d340b5d7e.PNG)

**Comment by zymeth25** [comment]
What you need is possible but not using the LCP widget. I strongly recommend using a regular Text widget and putting an LCP shortcode in it. I know it takes away the user interface, but as of now the shortcode has much more functionality than the widget.

Try this shortcode, I created it based on your widget settings:
`[catlist name="Faith Blog" orderby=date order=desc date=yes author=yes excerpt=yes excerpt_size=350 posts_morelink="Read More >>"]`

The `posts_morelink` option only exists in the shortcode, but not in the widget. And it will output the link as you want it.

**Comment by TS-GIT-Beta** [comment]
Thank you sir!!!

This might be a cool option to add to the catlist widget - "[ ] Read More goes to full post"

It ended up stripping out the html, so I added the "excerpt_strip=no" and the tag ended up being:

[catlist name="Faith Blog" orderby=date order=desc date=yes
author=yes excerpt=yes excerpt_strip=no excerpt_size=350 posts_morelink="Read More
&gt;&gt;"]

Works great! Thanks!
