### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by chickenlittlecocoa** [picandocodigo/List-Category-Posts#329]
Hey all. I don't know much about coding...can't get this to line up properly. Is it a simple fix?
I either want all the wording to the right of the image, or below it.
This is my coding:
[catlist name = "critters" pagination=yes numberposts=10 title_tag=h3 excerpt=yes excerpt_strip=yes thumbnail=yes force_thumbnail=yes thumbnail_class="acprog"]

this is the jumbled mess I get:
http://chickenlittlecocoa.com/critters/

I also got rid of the bullet points before, but changed my theme and they are back. I think that is as easy as going into the theme CSS.

**Comment by picandocodigo** [comment]
Hi @chickenlittlecocoa,
I think adding this CSS to your theme's style.css file should do the job:

```css
.acprog{
  float: left;
}

.lcp_catlist li{
  display: block;
  clear: both;
}
```

**Comment by chickenlittlecocoa** [comment]
Much better! Thanks! The spacing is still off...but it's just little tweaks, that of course I don't know how to do. How does one learn how to do the coding for this? I've read through all the details on the plugin and the wiki page. I can't figure out how to move the description a few pixels away from the image.

**Comment by picandocodigo** [comment]
@chickenlittlecocoa the language is CSS, and it's used for presentation in websites (colors, margins, paddings, fonts, layout, etc). I would suggest you start with [MDN's CSS documents](https://developer.mozilla.org/en-US/docs/Web/CSS) which are really good. Every WordPress theme has some `.php` files, which show the information in your blog (`header.php`, `single.php`, etc.). The CSS files are in charge of the appearance of your blog. The [WordPress Theme Handbook](https://developer.wordpress.org/themes/getting-started/) could be a good resource to learn more too.

**Comment by chickenlittlecocoa** [comment]
I'm on it! Thanks so much.

**Comment by picandocodigo** [comment]
Cool, I'll close this issue then.
Cheers.

**Comment by chickenlittlecocoa** [comment]
Last thing, I have it formatted and it looks great on Desktop and Tablet, but the mobile is all jumbled. Can you change CSS just for mobile? I noticed when I switch it for mobile, it changes for all 3.

**Comment by picandocodigo** [comment]
Great, glad to know it worked. You **can** change the CSS just for mobile. Check out the guide on [Media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries), and maybe also read about [CSS Grids](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) which are a new and pretty cool way to define your website's layout in a responsive way.
