### ISSUE TITLE
plugin works, BUT IN ADDITION started to show an error

### ISSUE THREAD

**Issue by lenchuk** [picandocodigo/List-Category-Posts#330]
the plugin works, BUT IN ADDITION started to show an error:

Notice: Undefined index: pagination_bookmarks in /home/dflaw/domains/df-law.co.il/public_html/wp-content/plugins/list-category-posts/include/lcp-catlist.php on line 438

it worked fine, still works, we didn't change anything. and suddenly an error message.
i inserted it to the page with a widget, not as shortcode

you can see it here: [https://www.df-law.co.il/%D7%AA%D7%97%D7%95%D7%9E%D7%99-%D7%A4%D7%A2%D7%99%D7%9C%D7%95%D7%AA/%D7%A0%D7%96%D7%A7%D7%99-%D7%92%D7%95%D7%A3/] (https://www.df-law.co.il/%D7%AA%D7%97%D7%95%D7%9E%D7%99-%D7%A4%D7%A2%D7%99%D7%9C%D7%95%D7%AA/%D7%A0%D7%96%D7%A7%D7%99-%D7%92%D7%95%D7%A3/)

the shortcode [catlist] stopped working.

wp 4.9.7
List category posts 0.78

**Comment by zymeth25** [comment]
Fixed in #326

This is a small bug, but still you shouldn't be seeing that message. You see it because you are running your site with [WP Debug mode on](https://codex.wordpress.org/WP_DEBUG). Always make sure it is **off** once you have finished testing and setting up your WP installatian

**Comment by picandocodigo** [comment]
Hi @lenchuk, just released version 0.78.1 with #326 included. Please update and let us know of the results. Thanks @zymeth25 for fixing this!

**Comment by zymeth25** [comment]
Resolved and can be closed.
