### ISSUE TITLE
Using List category posts plugin and pre_get_posts to add query filters

### ISSUE THREAD

**Issue by armando-basile** [picandocodigo/List-Category-Posts#335]
Hi all, i trying to use in a page this plugin adding only this code
`[catlist name="Agenzia Immobiliare" template=katia thumbnail=yes force_thumbnail=yes thumbnail_size=thumbnail excerpt=yes excerpt_size=30 posts_morelink="Leggi..." ]`

but i need to add other filters to query (not all "Agenzia Immobiliare" category posts) using custom fields, so i used a custom pre_get_posts in functions.php
```

function my_pre_get_posts( $query ) {
    // validate
    if( is_admin() ) {
        return;
    }

    if( !$query->is_main_query() ) {
        return;
    }

    // add first filter
    if( !empty($_GET['filtro1']) ) {
        $filtro1Array = array(
            'key'       => 'categoria_immobile',
            'value'     => $_GET['filtro1'],
            'compare'   => '='
        );
    }

    // generate meta query
    $meta_query = array(
        'relation' => 'AND',
        $filtro1Array
    );

    // set meta query
    $query->set('meta_query', $meta_query);	
    return;
}
add_action('pre_get_posts', 'my_pre_get_posts');
```
but when i try to use
`http://my_website/my_page?filtro1=somethings`
i receive a 404 Not Found message. Instead, if i recall category with parameter, filter work fine but not using List category posts so layout is wrong
`http://my_website/archives/category/agenzia-immobiliare?filtro1=somethings `

problem stands into meta_query set, because if i recall page without filter it work fine
`http://my_website/my_page` 

Could you help me ?

Regards
Armando

**Comment by zymeth25** [comment]
Change
```php
if( !$query->is_main_query() ) {
    return;
}
```
to
```php
if( $query->is_main_query() ) {
    return;
}
```

**Comment by armando-basile** [comment]
Great :) it work fine. Many Thanks
