### ISSUE TITLE
Is there a limit?

### ISSUE THREAD

**Issue by ampotty** [picandocodigo/List-Category-Posts#337]
### Expected behavior
To show all my blog posts.

### Actual behavior
Show nothing.

### Shortcode used and steps to reproduce the behavior
[catlist name=example numberposts=2000] <- Show nothing
[catlist name=example numberposts=500] <- Show something
Got categories with more then 500 posts.

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP 4.9.8
LCP 0.78.1

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by zymeth25** [comment]
Try `numberposts=-1`

If it still doesn't work turn WP Debug Mode on and post here any output it might give.
