### ISSUE TITLE
Suggestion (with code): Search for terms within multiple taxonomies

### ISSUE THREAD

**Issue by Crag-Monkey** [picandocodigo/List-Category-Posts#339]
The below edit allows for terms to be searched within multiple taxonomies, such as when custom post types are used.
For example, `[catlist post_type="posttype1,posttype2" taxonomy="posttype1_tags,posttype2_tags" terms="termA,termB, termC"]` would return any posts of post types "posttype1" or "posttype2", having tags termA, termB, or termC.

_lcp-parameters/php ~line 165:_
_**Current:**_
>       $args['tax_query'] = array(array(
>        'taxonomy' => $params['taxonomy'],
>        'field' => 'slug',
>         'terms' => $terms,
>         'operator' => $operator
>      ));

**_Proposed:_**
>       $args['tax_query'] = array('relation' => 'OR');
>       foreach(explode(',',$params['taxonomy']) as $taxonomy){
>            $args['tax_query'][] = array(
>              'taxonomy' => trim($taxonomy),
>              'field' => 'slug',
>              'terms' => $terms,
>              'operator' => $operator
>            );
>       }

Actual use case:
The WPGeodirectory plugin uses custom post types "gd_place" and "gd_event" and the respective taxonomies for tags are "gd_place_tags" and "gd_event_tags". I wanted to use List Category Posts to display a combined list of Places and Events which shared certain tags. The above edit achieves that while retaining reverse-compatibility.

`[catlist post_type="gd_place,gd_event" taxonomy="gd_event_tags,gd_place_tags" terms="salsa"]`

**Comment by zymeth25** [comment]
I like your solution but we already support multiple taxonomies. The information was missing from the [documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/How-to-select-which-posts-to-show) though, so I've just updated it.

Here is how you can achieve what you want without changing any files:

`[catlist post_type="gd_place,gd_event" taxonomies_or="gd_event_tags:{salsa};gd_place_tags:{salsa}"]`

**Comment by Crag-Monkey** [comment]
Ooh, that's event better! Thanks

**Comment by zymeth25** [comment]
Issue can be closed.
