### ISSUE TITLE
Sticky posts are listed incorrectly

### ISSUE THREAD

**Issue by Sarah1101** [picandocodigo/List-Category-Posts#342]
### Expected behavior
List shows all posts with color=green.

### Actual behavior
List shows all posts with color=green AND sticky posts even with color=red, for example.

### Shortcode used and steps to reproduce the behavior
[catlist customfield_name="color" customfield_value="green"]
(I think this behaviour only occurs with customfield parameters)

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP 4.9.8
LCP 0.78.1

**Comment by zymeth25** [comment]
Confirmed. We should add a shortcode parameter to allow ignoring sticky posts.
