### ISSUE TITLE
Multiple custom fields

### ISSUE THREAD

**Issue by Sarah1101** [picandocodigo/List-Category-Posts#344]
Hello,
do have plans to introduce supporting multiple custom fields? 
This would be an awesome feature.

**Comment by zymeth25** [comment]
You can show multiple custom fields by separating them with a comma like so:
`customfield_display="customfield1,customfield2"`

**Comment by Sarah1101** [comment]
Maybe I've expressed myself incorrectly. I would like to filter the results regarding two or more different custom field keys and values.
 
At the moment I can only use the parameters customfield_name="color" customfield_value="green,red". It would like to use a second parameter "pair" e.g. customfield2_name="size" customfield2_value="small" or better analogous to the logic of multiple taxonomies:
OR – customfields_or="color:{green,red};size:{small}"
AND – customfields_and="color:{green,red};size:{small}"

**Comment by zymeth25** [comment]
I think that would be a good new feature. Not very complicated to implement.

**Comment by Sarah1101** [comment]
Hello again, is this feature planned to implement this feature? It would be so helpful :-)
