### ISSUE TITLE
Feature: condition for displaying list

### ISSUE THREAD

**Issue by zymeth25** [picandocodigo/List-Category-Posts#347]
https://wordpress.org/support/topic/feature-condition-for-displaying-list/

**Comment by picandocodigo** [comment]
This is an odd request. It's quite specific, I don't see how it would be that useful. Do you think it would be worth adding?

**Comment by zymeth25** [comment]
I just copied it from the forum because it's much easier to track and discuss things here. You are right, it's too specific to add it as a feature, a few lines in a template should suffice.

**Comment by picandocodigo** [comment]
Ah, good. Yeah I use GitHub everyday so it's worth bringing stuff over and discuss it here :+1:
