### ISSUE TITLE
Declare for array to suppot PHP 5.3 and lower

### ISSUE THREAD

**Issue by sebaram** [picandocodigo/List-Category-Posts#349]
in 'lcp-category.php:86', 'lcp-catlist.php:137', 'lcp-widget.php:87', they are using '[]' for declare array.
However, it occurs error on PHP lower than 5.4.
So, I suggest to replace it to use 'array()' which is a more traditional way.

**Comment by sebaram** [comment]
oh...sorry I didn't notice it.
My mistake.

**Comment by zymeth25** [comment]
@sebaram you can close the issue.
