### ISSUE TITLE
Bug: parameters handling in CatListDisplayer::get_post_title

### ISSUE THREAD

**Issue by zymeth25** [picandocodigo/List-Category-Posts#350]
https://wordpress.org/support/topic/get_post_title-has-to-be-improved/

**Comment by zymeth25** [comment]
There are more bugs in this method, I'm afraid I'm gonna have to rewrite it from scratch 😒

**Comment by picandocodigo** [comment]
Oh, I can look into this tomorrow too. Is it the bug that's being reported there or did you find more issues?

**Comment by zymeth25** [comment]
In #288 I didn't refactor `get_post_title` and `get_post_link` because they don't fit the pattern of almost all other methods. This is caused by the exception [described in the docs](https://github.com/picandocodigo/List-Category-Posts/wiki/HTML-&-CSS-Customization). I only replaced the call to `assign_style` with `wrapper->wrap` but this didn't change anything.
 
The problem is it doesn't really work as described in the docs. One thing is the bug reported in this issue. Another thing is how shortcode parameters and method call arguments are handled.

- if we don't pass any `$tag` or `$css_class` to `get_post_title` and only use shortcode paramters `title_tag`, `title_class` then the tags and classes are handled as per the docs.
- if we use both function arguments and shortcode parameters it will first handle shortcode parameters and then wrap all of that with the `$tag` and `$class` passed as arguments.

This is because shortcode parameters and function arguments are handled separately in this method, whereas they should be handled togetether following the rule that shortcode parameters take precedence over arguments. Right now lines 228-254 deal with shortcode params and then lines 256-258 handle arguments, completely separately.
