### ISSUE TITLE
Update to 0.79 broken? 

### ISSUE THREAD

**Issue by dowdinsk** [picandocodigo/List-Category-Posts#353]
### Expected behavior
Update would be successful

### Actual behavior
Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '[' in /var/www/web139/web/wp/wp-content/plugins/list-category-posts/include/lcp-widget.php on line 87

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
Update to 0.79 killed my WP 4.9.8, I had to delete and revert to 0.78 to restore the site

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by zymeth25** [comment]
What PHP version are you running?

**Comment by picandocodigo** [comment]
@dowdinsk The plugin now requires PHP version 5.4 or more. Check [this issue in the support forum](https://wordpress.org/support/topic/fatal-error-after-update-today-10-oct-2018/) to read more.
