### ISSUE TITLE
Post with multiple categories - exclude all but main

### ISSUE THREAD

**Issue by EWSB-Chris** [picandocodigo/List-Category-Posts#355]
I love this plugin - it accomplishes so much that I've been trying to do!

I'm just having one small issue. I'm using the widget in the sidebar of my posts pages, and I have the category set to "Current Category." For posts that are only linked to one category it works great. However, I have a couple categories (Featured, Slider, etc) that are used as additional categories on certain posts that should be included in other groupings elsewhere on the site. I would like to completely ignore these categories in the LCP plugin.

I've tried doing this by adding those category IDs in the "Exclude categories (id's)" however those posts are still showing up in the LCP area of the sidebar.

Am I going about this incorrectly? Thanks in advance for any help you can offer.

**Comment by zymeth25** [comment]
@EWSB-Chris Currently it's not possible to exclude categories while using the current category feature. When you use current category in the widget, or `categorypage=yes` in a shortcde, it grabs all post's categories and displays posts that have **ANY** of these categories.

@picandocodigo in #327 we changed how `categorypage=yes` works (which is what the widget uses).  Now that it grabs all post's categories, maybe we could make it work with `id` parameter to handle excludes. So if I have posts with categories 1, 2 and 3 I can use `[categorypage=yes id=-2]` and it will never show category 2.

Or maybe this is too specific?

**Comment by EWSB-Chris** [comment]
@zymeth25 Not at all too specific, and it answers my question perfectly. Thanks so much for your fast response! And your last suggestion about using [categorypage=yes id=-2] would be exactly what I'm trying to do, but now I know why it's not working at the moment. Have a great day!
