### ISSUE TITLE
Use theme pagination mechanism

### ISSUE THREAD

**Issue by pled** [picandocodigo/List-Category-Posts#356]
Enhancement Request - It would be nice that the plugin uses the theme pagination mechanism (next/previous pages), to integrate better with the theme selected.

For example, when using twentyfourteen theme (provided by wordpress team), the pagination is pretty nice and sophisticated, and of course perfectly integrated with the theme. 
The "List Category Posts" use his own simple mechanism, not so nice in my opinion... Even if you can customize the CSS, I don't find how to easily use the theme pagination mechanism (I am not a dev guy).
-=-
I don't know if this is feasible, easy or hard, but I think it would be a nice feature to add.

**Comment by zymeth25** [comment]
To answer your question: this is not feasible because every theme implements pagination in its own specific way, so we cannot depend on theme provided pagination. We have to write code that works with every theme, or at least with a vast majority, this is why we use our own pagination.
