### ISSUE TITLE
display bug  in pagination?

### ISSUE THREAD

**Issue by lenchuk** [picandocodigo/List-Category-Posts#357]
hi

i create a page with pagination.
the page numbers and arrows don't look good.
on click on a number (or the arrows) the surrounding box becomes very tall.
see image:
![image](https://user-images.githubusercontent.com/42026359/47664265-5b256980-dba7-11e8-94b9-94cca57e229f.png)
in addition, in order for the pagination to work i have to click the number (or the arrows) twice

can i control the design of te numbers and arrows?
can i keep them same size all the time? avoid them getting tall?
can i surf clicking only once?

site still in developement.
url: http://new.ornet.net/?page_id=219 (site is in hebrew)
wp - 4.9.8
LCP: 0.79
shortcode:
[catlist name=123 orderby=id order=desc excerpt=no pagination=yes numberposts=3 thumbnail=yes  thumbnail_size=60,60 thumbnail_class=thumbs]

thanksss

**Comment by zymeth25** [comment]
I see the behavior on your website but can't reproduce it in local tests. Can try switching to a different WP theme and see if the issue still exists? I

**Comment by zymeth25** [comment]
@lenchuk I have located the source of the problem. It's neither the plugin nor any other element of WordPress. The problem is in the inline CSS you have added to your website. The following line is causing this:
```css
#lcp_instance_0 a, a:visited, a:focus {line-height: 100px !important; }
```
If you change it to:
```css
#lcp_instance_0 a {line-height: 100px !important; }
```

it will work nicely.

Cheers

**Comment by lenchuk** [comment]
thankssssssss
i'll try in a second.
thanks

*- - - - - - - - - **- - - - - - - - - **- - - - - - - - - *
*- - - - - - - - - *


*לני מידן - עיצוב והקמת אתרי אינטרנט*
אימייל:   lenny@metafora.co.il
אתר:     www.metafora.co.il
משרד:   0777-80-80-70
נייד:      052-6433030


‫בתאריך יום ב׳, 12 בנוב׳ 2018 ב-14:43 מאת ‪Klemens Starybrat‬‏ <‪
notifications@github.com‬‏>:‬
