### ISSUE TITLE
LCP has lost all linkages

### ISSUE THREAD

**Issue by Coxworld** [picandocodigo/List-Category-Posts#358]
Can't be specific when but all post links to other posts have disappeared.

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
Wordpress 4.9.8 and LCP 0.79

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by picandocodigo** [comment]
You need to be more specific than that. Was it when you updated the version of the plugin/WordPress? What does it mean that all post links have disappeared? In one instance of the shortcode? Everywhere? Do you see any logs with WP_DEBUG enabled?

**Comment by Coxworld** [comment]
Good morning Fernando, nice to talk with you.

 

I have been using the plug in for a long time now and have been very pleased with it.

At the end of each post I put the following text and script : -

Similar or related subjects : -

[catlist categorypage="yes" excludeposts=this]

I have been overseas for 3 weeks and as far as I know it was working OK when I left and wasn’t when I returned.

All I see now on each post is my text and a blank space where the related list should be.

Similar or related subjects : -

I am running :-

 

WordPress 4.9.8 running  <http://altrish.co.uk/wp-admin/themes.php> Twenty Seventeen theme.

Running PHP version: 5.4.16

 

My plugins have not changed other than upgrades and are as follows : -

 



 

I have tried disabling each one but doesn’t seem to have any effect on the problem.

 

LCP Settings as follows : -

 



 

Slight concern over the first line on this regarding Yoast.

Yoast Premium deactivated some time ago because they wanted a small fortune to continue it ….

 

I hope that helps give you a better picture.

 

Kind regards

 

Alan

www.altrish.co.uk <http://www.altrish.co.uk>

**Comment by Coxworld** [comment]
Minor update Fernando – my ISP has updated the PHP to 5.6.38 but this has not solved the problem.

They have also enabled WP_DEBUG but I apologise I do not know how to use this ….

 

Alan

**Comment by picandocodigo** [comment]
@Coxworld can I ask you to update the information in GitHub? It looks like you've tried to attach images to your e-mail replies, but they don't arrive in GitHub.
https://github.com/picandocodigo/List-Category-Posts/issues/358

**Comment by Coxworld** [comment]
OK didn’t realise this was the case.

Will see what I can do.

 

Alan

**Comment by Coxworld** [comment]
![image](https://user-images.githubusercontent.com/44877305/48276673-81b59100-e440-11e8-9168-db3bde1aa417.png)
![image](https://user-images.githubusercontent.com/44877305/48276733-a4e04080-e440-11e8-83fe-b68d3c933684.png)

Hope that is OK

Alan

**Comment by Coxworld** [comment]
I have found one blog entry that is working
http://altrish.co.uk/2018/11/02/golf-caddy-locks-and-ring-lights/

This is weird.

**Comment by Coxworld** [comment]
debug still running if you need it

**Comment by Coxworld** [comment]
Edit that - the 'visit site' way of viewing when logged into the site shows the links in place but a direct viewing of the site from the web shows the links disappeared.

**Comment by zymeth25** [comment]
@Coxworld I have tested your site and the plugin seems to be working on all posts. Below I'm listing the posts I have tested:

* http://altrish.co.uk/2018/09/11/notes-on-imts-2018-in-chicago/
* http://altrish.co.uk/2018/10/19/kona-ironman-harvesting-albre-cad/
* http://altrish.co.uk/2018/11/10/halloween-steaming-of-the-polly/
* http://altrish.co.uk/2018/11/02/golf-caddy-locks-and-ring-lights/

Do you still need help with this issue?

**Comment by Coxworld** [comment]
Now I am confused ... if I follow your links to the posts then I see the links.
If I go via a Google search direct to the site the links aren't there
If I go via WP from the dashboard to view the site the links aren't there.
Similar from other devices I have here.
Any ideas ?   
(Debug is still on)

**Comment by Coxworld** [comment]
IE giving same results

**Comment by Coxworld** [comment]
Further comment - If I go to the site and see no links but then go to a post via the Recent Posts navigation I see the links.
If I then navigate from post to post using the LCP listing all the links appear.
It is something about accessing the site direct that messes things up ?

**Comment by zymeth25** [comment]
Tu sum it up:

* if you visit single post pages, links appear
* if you visit your home page, which is the main blog page, links don't appear.

Is this correct?

**Comment by Coxworld** [comment]
Yes I agree.
Following a precise link works but generically to the home page does not.
Once on the home page if I select a Recent Post it works and I can then follow LCP links and all links show.
If I then go to Home page links disappear.
It is a bit weird ...

**Comment by zymeth25** [comment]
I'll look into it, it looks like I overlooked this feature while updating the `categorypage` feature.

**Comment by Coxworld** [comment]
No problem

**Comment by zymeth25** [comment]
Ok, the solution is now available in #363, you can either wait until it gets pushed to WP plugin directory or apply this small code change yourself now.

**Comment by Coxworld** [comment]
OK, thanks for your support.  Not sure how to do code changes so will wait for push through.
Have a good evening.
Alan aka Coxworld

**Comment by Coxworld** [comment]
Hi Fernando

 

List Category appears broken again ….

 

Alan

**Comment by picandocodigo** [comment]
Hi Alan, 
I'm sorry about this. Could you please open a new ticket describing which version you're using, when the error started happening and what is behaving wrong with more detail?
Thanks!

Fernando

**Comment by Coxworld** [comment]
Hi Fernando

The problem is as per the previous problem in that LCP does not list the matching categories on posts when I use the following criteria at the end of each post.

[catlist categorypage="yes" excludeposts=this]

It is however slightly different in that before I lost listings from historic posts as well as the current one whereas now it has occurred only a new post.

I notice that the plugin updated just a few days ago and this is the first post I have made since the update.

WordPress 5.2 running Twenty Seventeen theme.
Running PHP version: 5.6.40 
LCP 0.80.3

Tried to roll back to 0.80.1 from my Updraft backup but this didn't fix it which was a bit weird.

Hope that helps

Alan


Alan

**Comment by picandocodigo** [comment]
Ok, let's go into more detail. I first tested the same shortcode `[catlist categorypage="yes" excludeposts=this]` in my dev blog and it appears to be working fine. For a category with 5 posts, it lists the 4 posts which are not the current one.

I then checked your website, and if we're still talking about http://altrish.co.uk/ (cool content btw!), the first post is "Droning On and another Toy" which doesn't list any posts because it's the only post in [the drone category](http://altrish.co.uk/category/drone/).

The second post is "Decision Making Process for buying a New Workshop Asset", which is showing 10 posts (both in the homepage and the post) which belong to the categories of the post: Comment and Workshop Tooling. The rest of the posts in the first page also show posts from the related category.

Is it just the new post that has no posts listed?
Thank you for your patience!

**Comment by Coxworld** [comment]
Oh dear Fernando, huge red face at this end.
Should have engaged brain first and realised when I back loaded the earlier version it was not as it seemed.
You are quite correct that there are no other posts listed because this is the only Drone category post.
I am truly sorry for wasting your time.

(Glad you liked my content).

Kind regards

Alan

**Comment by picandocodigo** [comment]
Haha, no worries at all! It happens to all of us! I'm glad it was just that.

Cheers,
Fernando

**Comment by Coxworld** [comment]
Thanks Fernando and apologies again
Have a good evening.

Alan

**Comment by Coxworld** [comment]
Hi Fernando,

 

A small funny on the site that I think is an interaction with the Disable Gutenberg plugin.

 

I create a post and put your snippet at the bottom

Save as draft

Re-open to edit and all the pagination is lost (no carriage returns)

I clean up and save again as draft and all then seems fine going forward.

I have tried this with and without the snippet and it definitely only happens when the snippet is there.

See transcript from WP forum below.

 

Not sure about the ‘getting it sorted’ bit ……..

 

Kind regards

 

Alan

 

 <https://wordpress.org/support/users/husthwaite/> husthwaite 

(@husthwaite)

 <https://wordpress.org/support/topic/good-but-issue/#post-11646458> 12 minutes ago

Good point Jeff

I add the following to the foot of every post as part of the List Category Post plugin code for post analysis.

Similar or related subjects : –

[catlist categorypage=”yes” excludeposts=this]

I have just tried a draft post with and without this footer and as far as I can see your plugin works fine when I don’t put the footer in.

It looks like a fairly innocuous piece of code but clearly causes a problem. Once I have corrected the format messing it then seems OK going forward no matter how many edits.

Alan

Plugin Author <https://wordpress.org/support/users/specialk/>  <https://wordpress.org/support/users/specialk/> Jeff Starr 

(@specialk)

 <https://wordpress.org/support/topic/good-but-issue/#post-11646484> 5 minutes ago

Yeah it sounds like maybe the plugin that provides the [catlist] shortcode is doing something to the post content, like filtering it to detect the shortcode. Either way, glad you got it sorted, and thanks again for the good rating and feedback.

**Comment by picandocodigo** [comment]
Oh, I use the [Classic Editor Plugin](https://en-gb.wordpress.org/plugins/classic-editor/) in all of my sites. It's an official plugin to get the old editor back, and I haven't had issues with it. But I'll look into this when I get some time!

**Comment by Coxworld** [comment]
Don’t spend time on it Fernando, I will investigate the one you use.

 

Alan

**Comment by Coxworld** [comment]
Hi Fernado

 

Well I followed your suggestion and installed the Classic Editor Plugin.

First new post was looking good on saving to draft until I put the magic bit at the bottom for Category Posts …

Saved the draft.

Reopened and all the carriage returns were gone ….

 

There is something weird going on

 

[catlist categorypage="yes" excludeposts=this] 

 

Kind regards

 

Alan
