### ISSUE TITLE
File: lcp-paginator.php 

### ISSUE THREAD

**Issue by dkalog** [picandocodigo/List-Category-Posts#366]
### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by dkalog** [comment]
Expected Behavior
The last line pf paginator has hyperlinks to next /previous pages 

Actual Behavior:
The last line pf paginator has hyperlinks to next pages which do not work . they just scroll to the top of the Page/screen.

Latest version of Plugin 0.79

File Lcp-Paginator.php: 94 commented line which restored the functionality
//if ($bookmark !== "no") $page_link .= "#lcp_instance_" . $lcp_instance;

**Comment by zymeth25** [comment]
Use `pagination_bookmarks=no`. No code changes required.
