### ISSUE TITLE
Variable id with reusable block

### ISSUE THREAD

**Issue by leifnel** [picandocodigo/List-Category-Posts#369]
Feature request.

In shortcode-block:
[set $kat=79]
In reusable block:
[catlist id=$kat .... a lot of options]

The idea is to setup a reusable block with numerous parameters, then reuse the block on different pages, just set the variable somewhere previous to the block.

I don't know if the template system allows it.

**Comment by zymeth25** [comment]
The template system doesn't allow it. It would have to be implemented from scratch. Something simpler and already partly implemented is discussed in #177.
