### ISSUE TITLE
Customize HTML tags and CSS classes doesn't work

### ISSUE THREAD

**Issue by RubyBadlands** [picandocodigo/List-Category-Posts#380]
### Expected behavior

Expecting behaviour as described in documentation:

_Or you just want to style the displayed date, you could wrap it with a span tag:
[catlist name=blog date=yes date_tag=span date_class=lcp_date]
This would produce the following code:

<span class="lcp_date">March 21, 2011</span>

Elements without a specified tag, but a specified class, will be wrapped with a span tag and its class. For example this:
[catlist id=7 date=yes date_class="lcp_date"]
Will produce the following:

<span class="lcp_date">October 23, 2013</span>_

### Actual behavior

No matter which option I try, the date is not being wrapped by a class or even a tag.

### Shortcode used and steps to reproduce the behavior

[catlist name=xy conditional_title="" date_tag=span date_class="lcp_date" orderby=date order=desc numberposts=40  date=yes author=yes date_class=lcp_date thumbnail=yes thumbnail-size=large excerpt=full excerpt_strip=no posts_morelink="Mehr zum Beitrag" template=perfectlist]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)

WP 5.1, LCP 0.79

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by zymeth25** [comment]
I know this is far too late to serve as an answer 😄 but this behaviour is intended because `date_class` and other similar parameters are not supposed to work in custom templates. A custom template is a file where you manually customise such things.

Can be closed.
