### ISSUE TITLE
Adding catname to post line (even in template?)

### ISSUE THREAD

**Issue by palyne** [picandocodigo/List-Category-Posts#384]
Feature request? Or just advice request. 

Note there are a few entries with this question, none answered, all referring to use a template, so it keeps coming up. I can't figure out how to do it with a template either. It isn't in the examples of the default it seems.

catname="yes" (or catname="true", either) doesn't work to make the category name show up in the post list. For example when ordering a list by date, putting the category for each line item on the line with the title and date. 

It knows the value, so surely there is some way to do this. (Been whackin my head about this for a long time now.)   Like:

* catname PostTitle date
or
* PostTitle date catname
(gosh I don't care, if I could just get it to show up anywhere I'd be happy)

It seems like doing this would be easy but... it's not. This is an awesome plugin and I know there's already tons of options, but might I at least get advice about how to make that functionality noted happen? I feel like I must be missing something obvious.

Many thanks,
PJ

**Comment by klemens-st** [comment]
Implemented in #478
