### ISSUE TITLE
I want to list all posts authored by the current logged in user. Anyway?

### ISSUE THREAD

**Issue by anthonyrlocke** [picandocodigo/List-Category-Posts#387]
I want to use one page called my-account to be blank, unless you are logged in and then your own posts are listed. The only posts which show up are the ones created by the current user.

What will work? 

These ideas failed: 
[catlink author="wp_get_current_user"]

Does anything work?

**Comment by picandocodigo** [comment]
Hello @anthonyrlocke, this had to be implemented. I just added this [here](https://github.com/picandocodigo/List-Category-Posts/commit/8d580586c48b2d89458431ae09bfbe7e59258b78). Once the new release goes out, you'll be able to use:
```
[catlink author='current_user']
```

**Comment by anthonyrlocke** [comment]
Could you so kindly send me a copy of the updated plugin? Or tell me which
file to update on my site?




<https://www.linkedin.com/in/anthonyrlocke/>   [image: National Service
Charity Business Card.png] <https://nationalservicecharity.org/>

770-940-9959 Tony@TechSavvySystems.com

https://www.TechSavvySystems.com <https://www.facebook.com/anthonyrlocke>

[image: Facebook 131.jpg] <https://www.facebook.com/anthonyrlocke>  [image:
Twitter 131.jpg] <https://twitter.com/AnthonyRLocke>  [image: Linkedin
131.jpg] <https://www.linkedin.com/in/anthonyrlocke/>

**Comment by picandocodigo** [comment]
@anthonyrlocke You can get version 0.81 from the wordpress.org plugin directory. If you visit the plugins page in your WordPress admin dashboard, it should show List Category Posts is ready to be updated.

**Comment by anthonyrlocke** [comment]
I did the update.
Is my code wrong? [catlink post_type="client" author="current_user"]
I am using a custom post type. Plus, the code is inside a tab system built
by Beaver Builder which is a page builder
https://visitingchaplains.com/my-account/
[image: image.png]





<https://www.linkedin.com/in/anthonyrlocke/>   [image: National Service
Charity Business Card.png] <https://nationalservicecharity.org/>

770-940-9959 Tony@TechSavvySystems.com

https://www.TechSavvySystems.com <https://www.facebook.com/anthonyrlocke>

[image: Facebook 131.jpg] <https://www.facebook.com/anthonyrlocke>  [image:
Twitter 131.jpg] <https://twitter.com/AnthonyRLocke>  [image: Linkedin
131.jpg] <https://www.linkedin.com/in/anthonyrlocke/>

**Comment by anthonyrlocke** [comment]
I changed the shortcode: [*catlist* author="current_user"]
It shows all the posts, instead of just posts for the current logged in
person.
Not sure it is working.

[image: image.png]




<https://www.linkedin.com/in/anthonyrlocke/>   [image: National Service
Charity Business Card.png] <https://nationalservicecharity.org/>

770-940-9959 Tony@TechSavvySystems.com

https://www.TechSavvySystems.com <https://www.facebook.com/anthonyrlocke>

[image: Facebook 131.jpg] <https://www.facebook.com/anthonyrlocke>  [image:
Twitter 131.jpg] <https://twitter.com/AnthonyRLocke>  [image: Linkedin
131.jpg] <https://www.linkedin.com/in/anthonyrlocke/>

**Comment by anthonyrlocke** [comment]
Figured out the problem
[catlist post_type="client" author="current_user"]
Shows all the posts.
If I delete post_type="client" then it shows all the wp-posts.
Right now it isn't choosing the author, but the post type.
Sorry, not full squared away yet.
A freind of mine got it to work using this, but i am not technical enough
to make it work for me.

if ( is_user_logged_in() ):

    global $current_user;
    wp_get_current_user();
    $author_query = array('posts_per_page' => '-1','author' =>
$current_user->ID);
    $author_posts = new WP_Query($author_query);
    while($author_posts->have_posts()) : $author_posts->the_post();
    ?>
        <a href="<?php the_permalink(); ?>" title="<?php
the_title_attribute(); ?>"><?php the_title(); ?></a>
    <?php
    endwhile;
else :

    echo "not logged in";

endif;



<https://www.linkedin.com/in/anthonyrlocke/>   [image: National Service
Charity Business Card.png] <https://nationalservicecharity.org/>

770-940-9959 Tony@TechSavvySystems.com

https://www.TechSavvySystems.com <https://www.facebook.com/anthonyrlocke>

[image: Facebook 131.jpg] <https://www.facebook.com/anthonyrlocke>  [image:
Twitter 131.jpg] <https://twitter.com/AnthonyRLocke>  [image: Linkedin
131.jpg] <https://www.linkedin.com/in/anthonyrlocke/>

**Comment by anthonyrlocke** [comment]
Probably add this too

$author_query = array(
   'posts_per_page' => '-1',
   'author' => $current_user->ID,
   'post_type'=>'your custom post type name');





<https://www.linkedin.com/in/anthonyrlocke/>   [image: National Service
Charity Business Card.png] <https://nationalservicecharity.org/>

770-940-9959 Tony@TechSavvySystems.com

https://www.TechSavvySystems.com <https://www.facebook.com/anthonyrlocke>

[image: Facebook 131.jpg] <https://www.facebook.com/anthonyrlocke>  [image:
Twitter 131.jpg] <https://twitter.com/AnthonyRLocke>  [image: Linkedin
131.jpg] <https://www.linkedin.com/in/anthonyrlocke/>
