### ISSUE TITLE
[Feature] Offset catlist by set number using new parameter

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [picandocodigo/List-Category-Posts#388]
Would it be possible to have a new shortcode parameter for offsetting the posts by a set number?

Use case for me would be having a full post at the top with the following settings:
```
[catlist name=News pagination=yes numberposts=1 excerpt=full  excerpt_size=5000 excerpt_strip=no]
```
Then a slimmer list underneath on the same page:
```
[catlist name=News pagination=yes numberposts=10 excerpt=yes  excerpt_size=100 excerpt_strip=yes]
```

**Comment by picandocodigo** [comment]
Do you mean like the one that's already there?

> **offset** - You can displace or pass over one or more initial posts which would normally be collected by your query through the use of the offset parameter.

It's in the [complete docs](https://github.com/picandocodigo/List-Category-Posts/wiki/How-to-select-which-posts-to-show) in the wiki.

**Comment by Caffe1neAdd1ct** [comment]
Ah perfect, thanks very much! 

Didn't spot it on the additional parameters page I ended up on earlier... Cheers again I'll take a look :)
