### ISSUE TITLE
PageNavi with unexpected border in WP-theme 'Clean Gallery'

### ISSUE THREAD

**Issue by 6chu** [picandocodigo/List-Category-Posts#390]
I was expecting to an add PageNavi to the 'Cateloge List' Page I newly created, with a 'WP-PageNavi' css style.

The navi-bar turned out to be with an unexpected `1px #181818` border. `#181818` is actually my post text color... Donno why it appears here and I cannot get rid of it.

The short code I used is [catlist id=30 numberposts=30 pagination=yes]

Pagination css style:
`/* LCP-PageNavi
-------------------------------------------------------------- */
.lcp_paginator{clear:both;text-align:center;}
.lcp_paginator a,.lcp_paginatorspan{text-decoration:none;background:#eeeeee !important;border:1px solid #dddddd !important;padding:6px;margin:2px;display:inline-block;color:#444444 !important;line-height:1;border-radius:2px;}
.lcp_paginator a:hover,.lcp_paginator a:focus,.lcp_paginator span.current{background:#dddddd !important;border:1px solid #cccccc !important;color:#000000 !important;}
.lcp_paginator span.current{font-weight:normal;background:#dddddd !important;border:1px solid #cccccc !important;color:#000000 !important;}`

Related entry-content css:
`.entry-content{margin:0 0 10px;color:#181818;font-size:16px;}`

Plz help me :...( Thx

WP version: 5.2.3–en_US
LCP version: 0.81
WP Theme: Clean Gallery v1.0.7

**Comment by 6chu** [comment]
Problem solved after a nice sleep XD

**Comment by picandocodigo** [comment]
@6chu glad you could figure this out! I use WP-PageNavi myself and have different styles for both paginations too :+1:
