### ISSUE TITLE
How to show post title after post image

### ISSUE THREAD

**Issue by rcwebd** [picandocodigo/List-Category-Posts#391]
### Expected behavior
Want to show post title below the post image

### Actual behavior
showing post title above the post image 

### Shortcode used and steps to reproduce the behavior
[catlist thumbnail=yes force_thumbnail=yes name=mycat]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
Wordpress version 5.2.3 and LCP plugin version 0.81

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by four2six** [comment]
Just a quick reply from a fellow user:
The answer is "template system": https://github.com/picandocodigo/List-Category-Posts/wiki/Template-System
Alter the default template as described and switch the post thumbnail and the and the post title in it.
