### ISSUE TITLE
Suggested new feature: Skip X number of posts.

### ISSUE THREAD

**Issue by zushiba** [picandocodigo/List-Category-Posts#402]
I have an area where I'd like to show the latest post as a featured post, then the rest of the posts in a different area. This requires 2 places for me to place the short code. 

If there was a way to tell the shortcode to skip the first post in it's sequence then I could simply put my Latest post in the special area and the next say, 5 or 6 news posts in another, skipping the first post as it's already posted elsewhere.

Something like skip=1 to skip the first post or however many.

**Comment by picandocodigo** [comment]
@zushiba You can use the `offset` parameter for this:

> **offset** - You can displace or pass over one or more initial posts which would normally be collected by your query through the use of the offset parameter.

See more [here](https://github.com/picandocodigo/List-Category-Posts/wiki/How-to-select-which-posts-to-show)
