### ISSUE TITLE
List becomes an endless loop

### ISSUE THREAD

**Issue by eikito** [picandocodigo/List-Category-Posts#403]
### Expected behavior
List Posts as expected

### Actual behavior
When I generate a post list in a page or post that contains posts that also contain an LCP list in their code, the list becomes an endless loop. I read the information in the wiki about the parameter 'content=yes'. It's similar, but I don't use the 'content' parameter.

### Shortcode used and steps to reproduce the behavior
[catlist name=kmu excerpt=yes excerpt_size=20 template=list-category-posts-eikito-1 orderby=date excludeposts=this order=asc posts_morelink=Mehr]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP 5.4.1, LCP 0.82,  PHP 7.4.6

Do I have to take any other settings maybe? Otherwise the plugin runs great!

**Comment by eikito** [comment]
Hi Klemens, sorry for this very late answer, I did not notice that there was already a reply to my question. I attached my template. 
[list-category-posts-eikito-1.zip](https://github.com/picandocodigo/List-Category-Posts/files/5068843/list-category-posts-eikito-1.zip)

**Comment by zymeth25** [comment]
Hi @eikito 

I have tested the scenario you described with the template you shared, with no other plugins active and a default theme. I wasn't able to reproduce the issue.

Please disable all other plugins and confirm that this solves the issue, then start enabling plugins one by one and see which of them causes the issue. If this doesn't help, try a default theme.

Also, please enable WP Debug mode and check if there are any errors.

Let me know how it goes.
