### ISSUE TITLE
Listing Pages in Category

### ISSUE THREAD

**Issue by StaffHerb** [picandocodigo/List-Category-Posts#424]
I know the plugin i titled "List Category Posts" but does this plugin only look at Posts that fit into a category?  I'm using a plugin to add categories to some of my pages and I'm finding that it does not include Pages, only Posts.  Is there a way to include Pages that fall into a category or have a certain Tag?

### Expected behavior

Return a list of all Posts or Pages that fall into a category or have the specified tag

### Actual behavior

Only returns Posts that fall into a category or have the specified tag

### Shortcode used and steps to reproduce the behavior

[catlist id=30]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)

Wordpress Version 5.4.2 LCP Version 0.83.1

**Comment by picandocodigo** [comment]
Hi @StaffHerb, yes you can list pages too. Check out [the documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/How-to-select-which-posts-to-show) and the `post_type` parameter which lets you select pages too.

**Comment by StaffHerb** [comment]
Not sure how I missed that but that was exactly it!  Once I added post_type="page" the pages with those categories showed up.  Thank for the quick response and for this plug-in.  It does everything I need it to and I love it's flexibility!
