### ISSUE TITLE
Select all posts with any customfield_value

### ISSUE THREAD

**Issue by gendzo** [picandocodigo/List-Category-Posts#428]
To use custom fields, you must specify two values: customfield_name and customfield_value. Both parameters must be defined, or neither will work.

New feature: If I don't specify a customfield_value display all posts that have ANY value in this particular customfield_name. Or use some special characters instead of "any" like customfield_value="%".

**Comment by zymeth25** [comment]
That would be relatively easy to implement.

**Comment by zymeth25** [comment]
@picandocodigo I will change #328 to be more robust and allow all possible comparison types including the one requested in this issue. Then I will refactor the entire Meta Query to a trait. Sounds good?

**Comment by picandocodigo** [comment]
@zymeth25 sounds good to me! I'll try to make some time to work on the plugin stuff asap :smile:
