### ISSUE TITLE
Order of elements in the list

### ISSUE THREAD

**Issue by gendzo** [picandocodigo/List-Category-Posts#429]
The order of elements in the list is fixed via template file (templates/default.php), like:
1. the title and link to the post
2. comments
3. date
4. date modified
5. author
...

You can make your own template what is really great, but it would be good to be able to change the order of printing of these elements by some parameter in the shortcode.

**Comment by zymeth25** [comment]
There's no way to integrate this with the current template and display code. Would require a rewrite.
