### ISSUE TITLE
Feature request: 'Ajax- Load More' along with current pagination system

### ISSUE THREAD

**Issue by VinodKKumar** [picandocodigo/List-Category-Posts#435]
The feature was requested earlier also (around 2 years ago according to some support threads on wordpress.org), but has not been implemented since yet. Kindly add 'Ajax- Load More' and/or Infinite Scroll option in your plugin for multiple instance/ single instance on a webpage.

**Comment by zymeth25** [comment]
Hi @VinodKKumar 

This is largely due to our reluctance to add JS to the LCP plugin :wink: There was once a solution for this - pairing LCP with another plugin but it's no longer supported. I think we might add JS code but as an add-on plugin.

**Comment by VinodKKumar** [comment]
Thanks for your Reply. Kindly release new add-on for this feature as soon as possible. Any timeline for the add-on plugin?

**Comment by picandocodigo** [comment]
@VinodKKumar We're not going to officially work on an add-on to add JavaScript pagination for the moment. You might want to check if there are any specific JS plugins or libraries you can integrate with List Category Posts, but we're not going to support it officially in this repository for now. Thanks!

**Comment by VinodKKumar** [comment]
@picandocodigo This was not expected. You might have other priorities as of now but completely abandoning this feature request is not a good idea. I was desperately looking for this feature from a long time. There are no other plugin/ library which support this function. If you have came across any, you can mention here. I'm ready to support this plugin for this feature in monetary terms, if you agree.

**Comment by zymeth25** [comment]
As @picandocodigo said this is not going to become part of this repository. As I mentioned earlier it could be a separate add-on plugin, in a separate repository. I have already written one such JS based add-on plugin called [GUI for List Category Post](https://github.com/zymeth25/gui-for-lcp) so if you are willing support the feature you need I could write it for you.

**Comment by VinodKKumar** [comment]
@klemens-st Please write the separate add-on JS plugin code for me so that 'Ajax- Load More' can be implemented.  Also tell me how to support you?

**Comment by VinodKKumar** [comment]
Also provide features like option to choose no. of posts to load in single click, continuous scrolling, ability to change text for load more button, etc. It should be lite on resources also.

**Comment by klemens-st** [comment]
Ok, is there a website or email address I can contact you at @VinodKKumar?

**Comment by VinodKKumar** [comment]
@klemens-st Leave your email address at this form [https://forms.gle/rcCNDqKUL93ZB3tq8](https://forms.gle/rcCNDqKUL93ZB3tq8) . I will reply you.
