### ISSUE TITLE
Can't display List with all Custom Post Type Categories and Posts

### ISSUE THREAD

**Issue by nist24** [picandocodigo/List-Category-Posts#438]
Hi!

I created a custom post type called "exercises". Also created a couple of categories and posts for it. I now want to display a sitemap with all the "exercises" categories and its posts.

I used the following shortcode, which does not work:
[wp_sitemap_page post="exercises" display_category_title_wording="false" display_title="false"]

It only works when using it for pages:
[wp_sitemap_page post="page" display_category_title_wording="false" display_title="false"]
Then it displays a list with a category element and subelements with all the posts as expected.

This shortcode displays all "exercises" posts, but without showing the categories:
[wp_sitemap_page post="exercises"]

WP version 5.6
LCP plugin version 0.83.1
PHP 7.4

**Comment by zymeth25** [comment]
Hi @nist24 

The `wp_sitemap_page` shortcode is not part of our plugin. It comes from the [WP Sitemap Page](https://wordpress.org/plugins/wp-sitemap-page/) plugin. Consult their support with this issue.

Cheers

**Comment by nist24** [comment]
Hi @zymeth25 

Haha it must have been to late. I'm sorry for that thumb post. I kind of mixed these two plugins up.
I anyway had two write my own code for what I wanted to achieve. Works fine for me now.

Thanks
