### ISSUE TITLE
Plugins Conflict - "List Category Post" breaks "Wysija" (Newsletter Plugin)

### ISSUE THREAD

**Issue by ecovirtual** [picandocodigo/List-Category-Posts#44]
Hi, the plugin works great! but when I use the shortcode in the same page that I use "Wysija"(Newsletter Plugin), this last one stop working at all.

Anyone knows how to prevent the interference between "List Category Post" and "Wysija"?

Thank you for your great work.

**Comment by mmatthews1981** [comment]
closing this issue. it seems to have resolved itself.

**Comment by picandocodigo** [comment]
@mmatthews1981 Cool, thanks!!!!
