### ISSUE TITLE
Excerpt=full with More tag doesn't apply excerpt filters

### ISSUE THREAD

**Issue by StefanXRoos** [picandocodigo/List-Category-Posts#442]
### Expected behavior
If we have a post with a 'More' tag and LCP has the parameter set to excerpt=full the output should be rendered the same as Wordpress, with all the post being correctly formatted up to the More tag.

### Actual behavior
The text of the post is correctly output, but all of the <p> tags are missing between each line of the post.

### Shortcode used and steps to reproduce the behavior
[catlist id=28 numberposts=1 orderby=date order=desc excerpt=full]
Create a post with multiple paragraphs using the above category, but then insert a 'More' tag somewhere in the post. When viewing the post via LCP, note that all the paragraphs are concatenated, without any <p> tags around them.

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
0.83.1

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

Possible solution:

Look at the file include/lcp-catlist.php

Go to section starting at line 368 - public function get_excerpt($single)

Add the line in bold below line 380:

379          $lcp_excerpt = explode($matches[1], $lcp_content);
380          $lcp_excerpt = $lcp_excerpt[0];
ADD         **$lcp_excerpt = apply_filters('the_excerpt', $lcp_excerpt);**

**Comment by zymeth25** [comment]
You are right, there is no reason why `excerpt=yes` is run through 'the_excerpt' filters but `excerpt=full` is not. This is clearly an uninteded omission.

My only worry is this has been so for many years and if we change it, layout of many users' pages will change. And we know very well how users hate when this happens.

But there really is no sensible way to introduce the change and make it backwards compatible so perhaps we should roll it out with a visible warning.

**Comment by zymeth25** [comment]
@StefanXRoos Can you create a pull request with this change?

**Comment by StefanXRoos** [comment]
Hi Klemens,

 

I’ve not used GitHub before, but I think I have managed to create a pull request (#443).

 

Regards

 

Stefan

**Comment by picandocodigo** [comment]
That's a good catch. I'll merge the PR and add a note to the README. I seem to recall WordPress had a way of notifying users about update changes on their dashboards before updating a plugin, I'll look into that too.

**Comment by zymeth25** [comment]
From what I recall the code that displays that message would have to be already present in the older version, so no luck here :wink: I guess changelog will have to suffice.

**Comment by picandocodigo** [comment]
I'm pinning this issue until we add documentation about the change and a new version is released with the changes in the merged PR.

**Comment by klemens-st** [comment]
Fix included in the latest release and docs updated, thanks @StefanXRoos.
