### ISSUE TITLE
Incompatibility with HERALD theme

### ISSUE THREAD

**Issue by i3mega** [picandocodigo/List-Category-Posts#458]
### Expected behavior
Hi, i used the plugin for a while with no issue. I've just change the theme for [HERALD ](https://themeforest.net/item/herald-news-portal-magazine-wordpress-theme/13800118) and when i put the shortcode, the page is broken with no content.

### Actual behavior
I deactivated all the plugins to be sure and the issue is still here.
I've tried to reactivate the older theme and then it works.

### Shortcode used and steps to reproduce the behavior
[catlist id=62]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP : Version actuelle : 5.7.1
LCP : 0.84.1
PHP: 7.3

I can provide a staging site to test if you want.

Best regards

**Comment by klemens-st** [comment]
> I can provide a staging site to test if you want.

It's a premium plugin so yes, please do, otherwise we cannot test.

>I've just change the theme for HERALD and when i put the shortcode

How exactly are you using the plugin? Where did you put the shortcode? Was it regular post content, a widget or something else?

**Comment by i3mega** [comment]
> How exactly are you using the plugin? Where did you put the shortcode? Was it regular post content, a widget or something else?

Yes, a simple wordpress page.
Where can i put the credentials for the staging site?

**Comment by klemens-st** [comment]
You can send in an [email](mailto:zymeth25@protonmail.com). Make sure [WP Debug](https://wordpress.org/support/article/debugging-in-wordpress/) is enabled on the staging site.

**Comment by i3mega** [comment]
Done ;)

**Comment by klemens-st** [comment]
I run some test, I can confirm that the LCP plugin's code runs without issues and returns a proper post list. This is never displayed, however, because there is something on the theme's side that prevents it. I suggest contacting the theme's support, they should be aware of the many filter and action hooks their theme uses and should be able to point at what in the theme causes this bug.

**Comment by i3mega** [comment]
Ok thank you. I will let you know what they say for other people

**Comment by i3mega** [comment]
To display the catégory on HERALD theme, you have to use the MODULE FORMAT PAGE in the editor et put the shortcode as attachment. It works fine ! 
[url=https://zupimages.net/viewer.php?id=21/17/034n.jpg][img]https://zupimages.net/up/21/17/034n.jpg[/img][/url]

**Comment by klemens-st** [comment]
Thanks for sharing!
