### ISSUE TITLE
Service Unavailable by using exerpt

### ISSUE THREAD

**Issue by p-view** [picandocodigo/List-Category-Posts#460]
when i using exerpt=yes i get the Error "Service Unavailable " after 20 sec of loading.
Problem ist since WP 5.7 (before runs fine)

my actual system: WordPress 5.7.1 , Version 0.84.1

**Comment by klemens-st** [comment]
I cannot reprocuce this, works ok in my tests.

Try enabling WP Debug and see if there are any arrors logged.

https://codex.wordpress.org/WP_DEBUG

Remember to use WP_DEBUG_DISPLAY too.

**Comment by p-view** [comment]
I get no Debuuging Error. Only the server brings "Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', true);
is in the config

**Comment by klemens-st** [comment]
Have you checked the `wp-content/debug.log` file?

**Comment by p-view** [comment]
Yes
the only entry about is:
[25-Apr-2021 15:14:44 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /html/wordpress/wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php on line 177
Ist this the thint?

**Comment by klemens-st** [comment]
Now we are getting somewhere.

What is the exact shortcode you are using?

**Comment by p-view** [comment]
[catlist id=20 numberposts=10 pagination=yes instance=1 excerpt=yes excerpt_size=20 template=list ]
placed in a normal page. I can give you a login on dev system. Any chance to  write a pm to you?

**Comment by klemens-st** [comment]
> I can give you a login on dev system. Any chance to write a pm to you?
Only if there is no other way to debug it and if I judge that it could be an issue with the plugin. Because it could also be caused by a conflict with a specific theme or plugin or simply by misconfiguration. And as an open source contributor I don't offer such support. 

For now, please paste the full code of the template `list` that you are using in your shortcode.

**Comment by p-view** [comment]
<?php
/*
Plugin Name: List Category Posts - Template "Default"
Plugin URI: http://picandocodigo.net/programacion/wordpress/list-category-posts-wordpress-plugin-english/
Description: Template file for List Category Post Plugin for Wordpress which is used by plugin by argument template=value.php
Version: 0.9
Author: Radek Uldrych & Fernando Briano 
Author URI: http://picandocodigo.net http://radoviny.net
*/

/* Copyright 2009  Radek Uldrych  (email : verex@centrum.cz), Fernando Briano (http://picandocodigo.net)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or 
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/**
 * The format for templates changed since version 0.17.
 * Since this code is included inside CatListDisplayer, $this refers to
 * the instance of CatListDisplayer that called this file.
 */

/* This is the string which will gather all the information.*/
$lcp_display_output = '';

// Show category link:
$lcp_display_output .= $this->get_category_link('strong');

//Add 'starting' tag. Here, I'm using an unordered list (ul) as an example:
$lcp_display_output .= '<div class="lcp_catlist">';

/**
 * Posts loop.
 * The code here will be executed for every post in the category.
 * As you can see, the different options are being called from functions on the
 * $this variable which is a CatListDisplayer.
 *
 * The CatListDisplayer has a function for each field we want to show.
 * So you'll see get_excerpt, get_thumbnail, etc.
 * You can now pass an html tag as a parameter. This tag will sorround the info
 * you want to display. You can also assign a specific CSS class to each field.
 */
foreach ($this->catlist->get_categories_posts() as $single){
  //Start a List Item for each post:
  $lcp_display_output .= "<div>";

  //Show the title and link to the post:
  $lcp_display_output .= ' <h2>' .$this->get_post_title($single).'</h2> ' ;

  //Show comments:
  $lcp_display_output .= $this->get_comments($single);

  //Show date:
  $lcp_display_output .= ' ' . $this->get_date($single);

  //Show author
  $lcp_display_output .= $this->get_author($single);

  //Custom fields:
  $lcp_display_output .= $this->get_custom_fields($this->params['customfield_display'], $single->ID);



  /**
   * Post content - Example of how to use tag and class parameters:
   * This will produce:<p class="lcp_content">The content</p>
   */
  $lcp_display_output .= ' <div class="col-md-12"> ' .$this->get_content($single, 'p', 'lcp_content').' </div>';
   
/**
   * Post content - Example of how to use tag and class parameters:
   * This will produce:<div class="lcp_excerpt">The content</div>
   */
  $lcp_display_output .= '<div class="row"> <div class="col-md-12"> ' .$this->get_excerpt($single, 'div', 'lcp_excerpt').' </div>';
 //Post Thumbnail
  
//$lcp_display_output .= ' <div class="col-md-3"> ' .$this->get_thumbnail($single).' </div></div>';
  //Close li tag
  $lcp_display_output .= '</div>';
}

$lcp_display_output .= '</div>';

// If there's a "more link", show it:
$lcp_display_output .= $this->catlist->get_morelink();

//Pagination
$lcp_display_output .= $this->get_pagination();

$this->lcp_output = $lcp_display_output;
