### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by Bmadd** [picandocodigo/List-Category-Posts#470]
Hi There,

I get a problem with the plugin on my site, as it inserts a # into the widget pagination links for some reason. This makes the widget pagination links not work. 

Example url of a pagination link:

https://mydomain.com/current-page/?lcp_instance_listcategorypostswidget-2&lcp_pagelistcategorypostswidget-2=2#lcp_instance_listcategorypostswidget-2

I've fixed this by appending the below code to your get_pagination function:

$pag_output = str_replace("#","", $pag_output);

this then works as expected.

I'm not sure why its adding this #, but it would be great if you could add this to the official repository so Idont have to hack it anymore :)

**Comment by klemens-st** [comment]
Hi, no need to change anything in the code. Please read [the documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/Pagination#bookmarks-in-pagination-links).

**Comment by klemens-st** [comment]
The issue is the widget doesn't support this feature. But maybe you can use the shortcode in a text widget instead of the old LCP widget?

We no longer develop the widger anyway and encouragement everyone to use shortcodes or the GUI plugin.
