### ISSUE TITLE
Feature Request: Display category / categories shortcode on every post

### ISSUE THREAD

**Issue by ady001** [picandocodigo/List-Category-Posts#473]
This is a great plugin, but it lacks a **shortcode** to display the **category name** or multiple category names on each post. This is used mainly on news / blog sites that have posts in multiple categories and want to better highlight the  topics. 
The code should be post_catname and/or post_catlink (display categories with links to them)
Thank you!

**Comment by picandocodigo** [comment]
Hi @ady001, do you mean like the parameter `catlink` we already support? See [the docs](https://github.com/picandocodigo/List-Category-Posts/wiki/More-parameters-you-can-use):
>* **catlink** - Show the title of the category with a link to the category. Use the **catlink_string** option to change the link text. Default is 'no'. Ex: `[catlist catlink=yes]`. When using more than one category a title of each of them is displayed.
You can set a css class and an html tag to wrap the link in with `catlink_class` and `catlink_tag` (see [HTML & CSS Customization](https://github.com/picandocodigo/List-Category-Posts/wiki/HTML-&-CSS-Customization)). Tag defaults to `strong`.

**Comment by klemens-st** [comment]
I think what @ady001 meant is something like #103 but for categories. `catlink` doesn't show the links for each post separately.

**Comment by ady001** [comment]
Wehn using catlink=yes, only a title with the selected category appears at the top of the posts list
EG:
**Category Name (with link)**
- post 1 title, date thumb
- post 2 title, date thumb
- post 3 title, date thumb
I want to have the **category displayed with each post**, also with all the categories a post has attached 
EG:
- Post 1 Title, thumb, date, Category 1, Category 2
- Post 2 Title, thumb, date, Category 3, Category 1
- Post 3 Title, thumb, date, Category 5
- Post 3 Title, thumb, date, Category 1, Category 6

**Comment by ady001** [comment]
For example and reference I'm using the plugin **Display Posts** – Easy lists, grids, navigation, and more, By Bill Erickson.
That plugin has the requested feature. :)

**Comment by klemens-st** [comment]
@ady001 I already have an implementation ready for a very similar feature for tags in #476 and I could add a similar one for categories. But I've just realised it would be better to include everything in one feature that supports all taxonomies: categories, tags and any custom taxonomies.

The question is: do you think it's enough if users can select just one taxonomy, say categories, or should I allow displaying more, say categories and tags at the same time?

**Comment by ady001** [comment]
@klemens-st I think that the more flexible the better. Having the option to display categories and/or tags at the same time is ideal
Great work so far !

**Comment by klemens-st** [comment]
The display tags feature has been merged, I have refactored the code to be cross compatible with other taxonomies.

So now it's enough to add shortcode parameters for categories and reuse the code I've already added. The shortcode parameters will be analogous to those for tags, working exactly the same.
