### ISSUE TITLE
Displaying Post titles instead of list of Categories

### ISSUE THREAD

**Issue by mdun234** [picandocodigo/List-Category-Posts#480]
When using the shortcode `[catlist id=53]` I am expecting it to spit out a list of the categories that match with that category ID (including it's child categories). However, instead of categories, it's producing a list of ALL of the post titles (including ones that don't have that category selected). 

WP 5.9.1
LCP 0.86.1
PHP 8.0

Thanks!

**Comment by klemens-st** [comment]
It is producing a list of post as it is expected to do. The LCP plugin lists posts, not categories. Nowhere in the documentation does it indicate to the contrary. I'm afraid you will have to look for a plugin that is designed to list categories.
