### ISSUE TITLE
Custom Order by Intuitive Custom Post Order

### ISSUE THREAD

**Issue by benhartwich** [picandocodigo/List-Category-Posts#483]
Hi,

I tried to configure a custom ordering, which is made by the Intuitive Custom Post Order plugin (https://de.wordpress.org/plugins/intuitive-custom-post-order/). This plugin creates a new column to the table _posts which is called menu_order (nummeric values). I tried the following shortcode, but it seems that your plugin can´t see this custom database field, because no posts are displayed:

`[catlist  post_type="traffic" name=verkehr,baustelle,behinderung,blitzer,geisterfahrer,stau,unfall excerpt=full link_titles=no template=div title_class=lcp_title title_tag=h5 customfield_orderby="menu_order" order=asc customfield_orderby_type=NUMERIC]`

Is there any chance to get this kind of ordering working or a similar custom order plugin, which you support?

**Comment by klemens-st** [comment]
Try using `orderby` instead of `customfield_orderby`.

**Comment by benhartwich** [comment]
Thanks, this seems to work:
`[catlist post_type="traffic" name=verkehr,baustelle,behinderung,blitzer,geisterfahrer,stau,unfall excerpt=full link_titles=no template=div title_class=lcp_title title_tag=h5 orderby="menu_order" order=asc orderby_type=NUMERIC]`
