### ISSUE TITLE
How to change • to 1,2,3

### ISSUE THREAD

**Issue by cendrid** [picandocodigo/List-Category-Posts#489]
I am using this shortcode 
[catlist name=category orderby=date order=asc numberposts=-1]

But next i want to become like this

1: apple
2: vegetable
3: fruit

instead of 
• apple
• vegetable
• fruit

Display the number at the front, how to do that?

**Comment by klemens-st** [comment]
The answer to your question is in the [documentation](https://github.com/picandocodigo/List-Category-Posts/wiki/More-parameters-you-can-use). Look for the `template` parameter.
