### ISSUE TITLE
Problem with pagination of posts

### ISSUE THREAD

**Issue by soniathetravelist** [picandocodigo/List-Category-Posts#492]
Hi everybody,
i have a problem with List Category posts.
I need a very simple pagination of posts of the same category on one page with the small image and the title under it.

Is there  way to customize this way?
Thank you

**Comment by klemens-st** [comment]
Start with `[catlist name=yourcategory thumbnail=yes]`. Read the documentation about different options for thumbnails (images) and adjust with CSS to your liking.
