### ISSUE TITLE
Pagination 'no' doesn't list all posts

### ISSUE THREAD

**Issue by pageiana** [picandocodigo/List-Category-Posts#493]
### Expected behavior
Should display ALL posts from the category as in the shortcode I added pagination='no'

### Actual behavior
Only shows 30 posts. Even though there are 400 in that category 

### Shortcode used and steps to reproduce the behavior
[catlist name="french-articles" pagination='no']

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)

Latest 
(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by klemens-st** [comment]
> Should display ALL posts from the category as in the shortcode

This is not true. Read the documentation carefully. By default the plug-in lists a predefined number of posts. You can change it with the `numberposts` parameter. To get all posts set it to `-1`.
