### ISSUE TITLE
Warning: Attempt to read property

### ISSUE THREAD

**Issue by yangqiceng** [picandocodigo/List-Category-Posts#506]
Warning: Attempt to read property “cat_ID” on null in /home/www/wp-content/plugins/list-category-posts/include/lcp-widget.php on line 93

Warning: Attempt to read property “name” on null in /home/www/wp-content/plugins/list-category-posts/include/lcp-widget.php on line 94

I searched on Google, and find some website show this too.

Default category. ID 1. Other category is ok.
Version 0.89 Wordpress 6.3.1

**Comment by klemens-st** [comment]
So I assume you are using the widget and see this error only when selecting category id 1?

**Comment by yangqiceng** [comment]
yes, and I use the old version, it's normal.

**Comment by klemens-st** [comment]
Sorry, 'old version'? What do you mean?

**Comment by yangqiceng** [comment]
previous version is ok

Klemens Starybrat ***@***.***> 于 2023年11月8日周三 16:26写道：

**Comment by klemens-st** [comment]
Can you be more specific? What old version, what number?

**Comment by yangqiceng** [comment]
0.88.1 is ok

Klemens Starybrat ***@***.***> 于 2023年11月9日周四 03:45写道：

**Comment by klemens-st** [comment]
I can't reproduce it. I think the reason is related to where exactly the widget is placed. Is it in the footer, sidebar or something else? Does the error appear on all pages or just specific ones?

**Comment by yangqiceng** [comment]
sidebar, you may search it on Google, some website may show this error

Klemens Starybrat ***@***.***> 于 2023年11月13日周一 17:47写道：

**Comment by klemens-st** [comment]
Ok, I see but still can't reproduce. Can you post a screenshot of your LCP widget configuration?

**Comment by klemens-st** [comment]
I was able to reproduce, will prepare a fix

**Comment by yangqiceng** [comment]
Awesome, thank you so much!

Klemens Starybrat ***@***.***> 于 2023年11月13日周一 21:03写道：
