### ISSUE TITLE
CSS functionality and documentation review

### ISSUE THREAD

**Issue by dday76** [picandocodigo/List-Category-Posts#507]
**Expected behavior**
CSS functionality is fully compliant or better explained, specifically for thumbnails.

**Actual behavior**
CSS does not seem to function for thumbnails, which appear awkardly at the end of the title line.

**tag example**
[catlist orderby=date date=yes name="featured" numberposts=20 excerpt=full thumbnail=yes thumbnail_class=float:inline-start class=margin-bottom:10px]

_expected result_ for this tag would be 20 featured posts with date and thumbnail on the left, with a 10px margin after each line item.

ps. use of "" or not for tag parameters is inconsistent in documentation. tried css with or without ""

**Comment by klemens-st** [comment]
Use of quotes and double quotes is universal across the entire shortcode system of WP, this is why we do not document it. It is documented by WordPress. In short, quotes are necessary when the value contains white space(s)"

>  thumbnail_class=float:inline-start class=margin-bottom:10px
This is not the documented method. Please read the LCP plugin's documentation. You can use the `class` parameter to assing a CSS class e.g. `class=my-super-class` and then style it using CSS.
