### ISSUE TITLE
Attempt to read property "ID" on string in lcp-catlistdisplayer.php

### ISSUE THREAD

**Issue by micrology** [picandocodigo/List-Category-Posts#509]
### Expected behavior
No Warning

### Actual behavior
Warning:
```
PHP Warning:  Attempt to read property "ID" on string in /data/cecanltd/wp-content/plugins/list-category-posts/include/lcp-catlistdisplayer.php on line 198
```
line 198 is
```
197       case 'customfield':
198       $info = $this->catlist->get_custom_fields($this->params['customfield_display'], $post->ID);
199       break;
```

### Shortcode used and steps to reproduce the behavior
Shortcode:
```
[catlist id=6 template=cardview thumbnail=yes thumbnail-size="large" numberposts=10 pagination=yes customfield_display="meta,presenters" customfield_display_name="no" customfield_display_glue=" | "]
```
Webpage that uses this is at [https://www.cecan.co.uk/training/cpd-courses/](https://www.cecan.co.uk/training/cpd-courses/)

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP 6.4.1
LCP 0.89.1
PHP 8.2.9

**Comment by klemens-st** [comment]
I will try to reproduce this although it must be said that PHP 8.2 is [still in beta support](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/).

Can you share your custom template?

**Comment by micrology** [comment]
The template is attached.  The file is `cardview.php`, but GitHub won't acceptd PHP files, so I have renamed it to `cardview.txt`
[cardview.txt](https://github.com/picandocodigo/List-Category-Posts/files/13333964/cardview.txt)
)

**Comment by klemens-st** [comment]
You have an error in your custom template:
```php
//Custom fields:
   $lcp_display_output .= $this->get_custom_fields('meta','presenters', $post->ID, 'span', 'newsdate');
```
This method does not accept names of custom fields you want to display, you do it in your shortcode (as you did properly). For each of the methods used inside the loop, `$post` **must** be the first argument after which you may specify two additional arguments for tag and class, respectively. See the [default template](https://github.com/picandocodigo/List-Category-Posts/blob/master/templates/default.php) for reference.

Secondly, I do not know why you tried `$post->ID`, it does not work and is not documented. 

Suggested fix:
```php
//Custom fields:
   $lcp_display_output .= $this->get_custom_fields($post, 'span', 'newsdate');
```

**Comment by micrology** [comment]
Thank you for your help with this.  And many apologies for raising this as an issue.  The code you suggested works.
