### ISSUE TITLE
Pagination problem for anonymous user

### ISSUE THREAD

**Issue by OllieA** [picandocodigo/List-Category-Posts#512]
I reported a pagination problem (https://github.com/picandocodigo/List-Category-Posts/issues/511) recently that was addressed with v. 0.89.5. However, that fix only seems to have addressed logged in users. Pagination does not work for anonymous users.

### Expected behavior
Clicking the >> button at the bottom of a page should open a page like the following url:
https://www.arboretumfriends.org/gallery-test/?lcp_page0=2#lcp_instance_0

### Actual behavior
While that works for me while I am logged in to my site's dashboard, when I close my log in, I stay on the initial page and the browser url window shows:
https://www.arboretumfriends.org/gallery-test/#lcp_instance_0

If I manually edit the url in the browser to include the ?lcp_page0=2, the browser stays on the initial page and changes the url window to the erroneous form shown above.

### Shortcode used and steps to reproduce the behavior
[catlist name=photogallery date=no dateformat="m/d/Y" author=no excerpt=no title_class=lcp_title title_tag=h3 pagination=yes numberposts=5 content=full template=photo-gallery ]

### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WordPress 6.4.2
PHP 7.4.3-4ubuntu2.19
List Category Posts 0.89.5

(If you want to submit a feature request, delete the sections above and describe the suggested feature.)

**Comment by klemens-st** [comment]
I cannot reproduce this, latest release works fine in my tests. Maybe it is a cache issue on your side? Common cache techniques by default serve cached content to regular visitors and do not use cache for logged in users.

**Comment by OllieA** [comment]
Thanks for response. I am leaning that way too since LCP works fine (logged in or not) on another of my sites. Now to track down the caching problem.
