### ISSUE TITLE
Post Title without link

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#58]
Output post title not wrapped in link.

**Comment by scannermobs** [comment]
Has this been done yet? I'd really like to have only one link per item, with image and title, etc, inside. Thanks!

**Comment by zulkamal** [comment]
I've implemented this in my fork's a6630341d8f20a0fa0dc55f42540aa0ea97452fb, feel free to merge it in

**Comment by picandocodigo** [comment]
@zulkamal would you mind doing a PR for each of your fixes? Thanks!

**Comment by zulkamal** [comment]
submitted!

**Comment by picandocodigo** [comment]
Thanks @zulkamal for the PR, this issue is now completed :smiley:
