### ISSUE TITLE
Issue with using [category] more than once on a page

### ISSUE THREAD

**Issue by bberkov** [picandocodigo/List-Category-Posts#70]
I thought I submitted this previously but it seems to have disappeared or never been posted.  If I want to have two lists of say Category A and Category B, I seem to have to use the id for the second category or the list of posts has posts from other than Category B.   I note that the first category is a single word whereas the second has the title Directories & More.

Any insights appreciated.

**Comment by a4jp-com** [comment]
Nice advice. I'm gonna be doing the same thing.
