### ISSUE TITLE
Numberposts value not honored

### ISSUE THREAD

**Issue by jaromil** [picandocodigo/List-Category-Posts#71]
As reported on many forums, the 'numberpost' argument (either when set as default or in the catlist tag) doesn't have any effect.

I'm not sure this depends from the fact I'm using multiple [catlist] tags on the same page? I'm also using the latest Wordpress (3.8 at the time of writing).

I'm looking into fixing this myself, but any hint from people with more experience of this issue would be useful at this stage. Thanks.

**Comment by zymeth25** [comment]
Can be closed, issue no longer present.
