### ISSUE TITLE
Featured image is pulling a lower res version in the plugin

### ISSUE THREAD

**Issue by thaddeushunt** [picandocodigo/List-Category-Posts#72]
Hey, I'm trying to nail down where this problem is coming from and I apologize if it's not your plugin.  For some reason when I request the featured image with List Category short code, it is automatically pulling one of the lower res (medium size) images from media library. I can actually see that it's medium sized image when I look at the source code. Normal posts and pages are grabbing the original image no problem, but not the short-code from your plugin.   This causes the featured image to be blurry and distorted in the short code output, but not once you click through to the linked page, where it is rendering properly.

Thanks for any suggestions or guidance you could give,

Tad

**Comment by zymeth25** [comment]
Stale issue, solved, can be closed.
