### ISSUE TITLE
Excerpt disappears in Genesis 2.02 framework

### ISSUE THREAD

**Issue by leojn** [picandocodigo/List-Category-Posts#77]
Since upgrading to Genesis 2.02 the excerpt disappears on the landing page only.
In the right sidebar menu there is a widget that shows "Attitude of Gratitude Tip of the Week" (below "about me" above "favorite posts").  http://www.nosmallthing.net. The excerpt part of the widget is truncated only on the home page. (It is the partial text that should display and isn't). If you click on other pages from the top menu the widget appears correctly on all those pages. I can't find anything about this from the developer or genesis. If I rollback to 1.92 it works. I will leave 2.02 on the site for now so it can be seen. Has anyone else run into this problem?

URL http://nosmallthing.net

Child Theme: Prose

**Comment by zymeth25** [comment]
Can be closed, the issue is stale.
