### ISSUE TITLE
No tags issue

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#80]
When the post has no tag, or a page is opened (which has no tags by nature), the error message is fixed, but the list is not empty, but full, it seems to take "nothing" for "everything". Maybe a little "if posthavetag" or something could avoid this. I think if there is no match, it needs to be empty.

http://wordpress.org/support/topic/detecting-current-tags?replies=8#post-5214337

**Comment by picandocodigo** [comment]
Bump

**Comment by zymeth25** [comment]
@picandocodigo Instead of bumping you can add the 'pinned' label and stale won't close the issue.

https://github.com/picandocodigo/List-Category-Posts/blob/2092969914693f2b0f57cee9bc5e12183c87fc41/.github/stale.yml#L7

**Comment by picandocodigo** [comment]
@zymeth25 Right! Thank you! :smile:
