### ISSUE TITLE
Pagination -  reduce amount of pages when there are many pages.

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#83]
http://wordpress.org/support/topic/pagination-with-lots-of-pages

**Comment by oiooio** [comment]
Are there any plans to implement this feature in the near future? It would make an awesome improvement!

**Comment by picandocodigo** [comment]
Yes, it's on my To-do list.

**Comment by zymeth25** [comment]
Here is something I drafted some weeks ago

https://github.com/zymeth25/List-Category-Posts/commit/ea9c61a4f96544bc08a86e78a6a999335c3722a7

**Comment by picandocodigo** [comment]
@zymeth25 tested your code ([in production](https://picandocodigo.net/software-libre/?lcp_page0=1#lcp_instance_0) :joy:) and it's :+1: 
We should use this and make the padding a parameter :raised_hands:

**Comment by zymeth25** [comment]
OK! I'll clean it up and create a PR. What should the default padding be?

**Comment by picandocodigo** [comment]
I guess 5 is a good default?

**Comment by zymeth25** [comment]
Yeah, that would be up to 11 dynamic pages. Sounds good.
