### ISSUE TITLE
List posts from a category's subcategories

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#84]
Modify the plugin to show the SUBCATEGORY posts from the current parent category. Utilizing the parent category as the Widget title would be a great feature too.

**Comment by timaji** [comment]
agree with you, 

you have any idea how to fix this ?

**Comment by zymeth25** [comment]
>Modify the plugin to show the SUBCATEGORY posts from the current parent category

This is already implemented, isn't it?
