### ISSUE TITLE
The <! -- more -- > is completely ignored

### ISSUE THREAD

**Issue by Gixx** [picandocodigo/List-Category-Posts#85]
I use the  tag for almost every post and it works well on the home (list) page. But when I use the List-Category-Post plugin on a page it completely ignores this tag, so the whole content of the posts in the listed category will be visible and that's not good.

Check this page: http://blog.gixx-web.com/fotoblog/

P.S.: I cannot remove the < P > tag from around the , because it is not in the editor, something else encapsulates it...

**Comment by Sophist-UK** [comment]
It is working for me - in fact it is working too well for me so I have just submitted an enhancement to allow for display of full-posts which have a &lt;!--more--&gt;.

**Comment by picandocodigo** [comment]
Working for me too so I'm closing the issue. Thanks!
