### ISSUE TITLE
Return empty list in certain cases?

### ISSUE THREAD

**Issue by picandocodigo** [picandocodigo/List-Category-Posts#86]
Should I return posts or show that the tag/category or whatever posts combination that I called has no posts? By default I've always returned the latest posts because that's what the query does when the params are "wrong". But could make for a better user experience if I returned an empty list in certain cases.

https://github.com/picandocodigo/List-Category-Posts/commit/ba145bf54ced8651d36a275fbf606c02839fdf45#diff-050d578cde63ad090de2bc3064ce0eabR171

**Comment by zymeth25** [comment]
Maybe add an option in the backend where the user can choose whether to display recent posts in such cases or an empty list? Then pass it to `lcp_should_return_posts`. Next step would be to allow the user (in the backend) to specify a default fallback behaviour , e.g. another shortcode, that would be displayed unless overridden by `no_posts_text`.
