### ISSUE TITLE
Incompatibility with add-rel-lightbox plugin

### ISSUE THREAD

**Issue by NikolausDemmel** [picandocodigo/List-Category-Posts#87]
If I use list-category-posts on a page, it seems to cause add-rel-lightbox [1] to malfunction. This plugin adds the_content and the_excerpt filters with priority 12. With a list-category-posts shortcode included in the page, it seems that the content filtered by the add-rel-lightbox plugin comes directly from the listed posts, not the actual output of the current page. I'm not sure about the inner workings of all this, but if I change the priority in add-rel-lightbox to 11, it seems to work.

[1] https://plugins.trac.wordpress.org/browser/add-rel-lightbox/trunk/add_rel_lightbox.php

**Comment by zymeth25** [comment]
Can be closed, this is a compatibility issue with a fix included in the initial post 😉
