### ISSUE TITLE
How to List Posts From Catagory & Tags

### ISSUE THREAD

**Issue by faraz37** [picandocodigo/List-Category-Posts#90]
Firstly, would like to thank you for your hardwork in making our lives easier!
My Question:
I have a catagory "All Songs" which has posts of songs from different artists with specific Tags on each post e.g. "Artist A", "Artist B", "Artist C" etc.
Now, I want to list posts from catagory "All Songs" which are tagged "Artist A"

I'm using this:
[catlist name='All Songs' orderby=name order=asc Tag='Artist A' numberposts=500]

But unfortunately can't get it to work! Could you please confirm if this feature is availalbe? If not, do you wish to implement it in future?

**Comment by zymeth25** [comment]
Can be closed, @faraz37 made 2 mistakes in the shortcode: 'Tag' instead of 'tags' and didn't hyphenate the tag.
