### ISSUE TITLE
Can we order the posts by popularity / view count?

### ISSUE THREAD

**Issue by wilsonf1** [picandocodigo/List-Category-Posts#94]
Not much else to say beyond the title. It'd be really awesome to pull out 5 posts by cat or tag but also for the top 5 to be pulled?

Can it be done?

**Comment by zymeth25** [comment]
Wordpress doesn't natively track page views. There are many plugins that do this and to implement it properly you would have to write custom code to hook them into LCP. So the short answer to your question is no, it cannot be done just with WP and LCP, however, there is a rather primitive solution that can be easily set up:
1. Follow the instructions available [here](http://wpsnipp.com/index.php/cache/track-post-views-without-a-plugin-using-post-meta/).
2. In your shortcode sort the posts by the customfield you have set above, example: `[catlist id=1 customfield_orderby="post_views_count"]`

Issue can be closed I think, maybe in the future we can make LCP compatible with a popular tracking plugin and introduce this enhancement...
